### ISSUE TITLE
[General] 4-3：三角形

### ISSUE THREAD

**Issue by YTW817** [coding-coworking-club/python-2020-spring#1]
## 提交連結

https://judge.ccclub.io/status/73ee833725af75010d28b7907dccbb8d

## 程式碼

```python
a=int(input())
b=int(input())
c=int(input())
if abs(a-b)<c<abs(a+b) and abs(a-c)<b<abs(a+c) and abs(b-c)<a<abs(b+c):
    print("Ture")
else:
    print("False")
```

## 問題描述

用任兩邊之差小於第三邊、任兩邊之和大於第三邊的三角形特性設定條件
在jupyter上測試可行，在judge上顯示WA
是否還欠缺什麼條件未設定?

**Comment by Kevinweisl** [comment]
提交連結請貼完整的超連結，方便助教能直接點進去看，感謝。

**Comment by YTW817** [comment]
> 提交連結請貼完整的超連結，方便助教能直接點進去看，感謝。

**Comment by YTW817** [comment]
> 提交連結請貼完整的超連結，方便助教能直接點進去看，感謝。

抱歉，已更正

**Comment by alexypdu** [comment]
要印 `True` 不是 `Ture` 唷！

**Comment by YTW817** [comment]
阿 原來是犯這種低級打字錯誤... 抱歉打擾了
