### ISSUE TITLE
[General] 停車費

### ISSUE THREAD

**Issue by Taylorw-cc** [coding-coworking-club/python-2020-spring#10]
## 提交連結

https://judge.ccclub.io/status/83eff03cd401d41e31951360d2f9e7de
## 程式碼

```python
come = input()
out = input()
d = input()
time = (int(out[0:2]) - int(come[0:2])) * 60 + int(out[3:]) - int(come[3:])
if d == "Y" and time < 30 and time >= 0:
    print(0)
elif d == "Y" and time % 30 == 0 and time >= 30:
    print(int(time / 30 * 20 / 2))
elif d == "Y" and time % 30 != 0 and time >= 30:
    print((int(time / 30) + 1) * 20 / 2)
elif d == "N" and time % 30 != 0 and time > 0:
    print((int(time / 30) + 1) * 20)
elif d == "N" and time >= 0:
    print(int(time / 30 * 20))
```

## 錯誤訊息

![停車費答錯](https://user-images.githubusercontent.com/61939358/76332182-06613980-632b-11ea-8f6f-0d6984fbb1ab.png)

## 問題描述

試了很多次還是答錯，不知道是否有什麼條件遺漏了，懇請助教解惑~

**Comment by dada8397** [comment]
time 的計算方式錯了，可以想想看假設 come = 12:50, out = 15:30
建議都先換算成分鐘再相減

**Comment by jeffery12697** [comment]
print((int(time / 30) + 1) * 20 / 2) 這句如果最後是用‘/’ 輸出會是浮點數，建議可以比較 ‘/’跟‘//’的差別

**Comment by Taylorw-cc** [comment]
修改時間計算方式及用//取代/之後順利答對了! code也變得比較不複雜了! 感謝助教~
