### ISSUE TITLE
[Homework 1] 優惠券

### ISSUE THREAD

**Issue by JefferyMC** [coding-coworking-club/python-2020-spring#102]
## 提交連結

https://judge.ccclub.io/status/9a68dcc4504db0b9893e10c8557d1cde

## 程式碼

```python
first = input().split()
second = input().split()
third = input().split()
fourth = input().split()
fifth = input().split()
price = int(input())

if len(first) == 2:
    price -= int(first[1])
elif len(first) == 1:
    price *= int(first[0])/10

if len(second) == 2:
    price -= int(second[1])
elif len(second) == 1:
    price *= int(second[0])/10

if len(third) == 2:
    price -= int(third[1])
elif len(third) == 1:
    price *= int(third[0])/10

if len(fourth) == 2:
    price -= int(fourth[1])
elif len(fourth) == 1:
    price *= int(fourth[0])/10
    
if len(fifth) == 2:
    price -= int(fifth[1])
elif len(fifth) == 1:
    price *= int(fifth[0])/10

if price <= 0:
    print(0)
else:
    print(int(price))

```

## 問題描述

我的想法是先判斷輸入由空格隔開的話，是幾個物件，再進行運算，提交是正確的。
但由於五張折價券會進行相同的判斷，因此想嘗試以函式寫程式：
```python
def discount(x):
    if len(x) == 2:
        (問題)
    elif len(x) == 1:
        (問題)
```
但遇到兩個問題：
1. 若寫出算式，可能要引入兩個變數，可以嗎？我寫 price 的話它就會顯示
local variable 'price' referenced before assignment
2. 若寫出 return，無法 return 一個運算值，只能是數值，但這樣我就不知道怎麼運用到後續的程式了

請問能給點提示：如果用函式該修改哪裡嗎？或是我的想法是不通的呢？
謝謝

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將標題及內文格式修正。

**Comment by JefferyMC** [comment]
> 請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將標題及內文格式修正。

已修正，不好意思

**Comment by alexypdu** [comment]
1. 函式要有幾個參數都是可以的
2. 你的函式 `discount` 只需把打折後的價格回傳出來即可

**Comment by JefferyMC** [comment]
> 1. 函式要有幾個參數都是可以的
> 2. 你的函式 `discount` 只需把打折後的價格回傳出來即可

後來成功了，謝謝！
