### ISSUE TITLE
[Homework 1] 小明查單字 

### ISSUE THREAD

**Issue by secretrw** [coding-coworking-club/python-2020-spring#103]
## 提交連結

https://judge.ccclub.io/contest/40/problem/041102

## 程式碼

lst1=[x for x in input().split()]
lst2=[]
a=input()
for i in range(0,len(lst1)):
    b=lst1[i]
    for j in range(0,len(a)):
        if b[j]==a[j]:
            continue
        else:
            lst2.append(i)
lst2.reverse()
for i in lst2:
    lst1.remove(lst1[int(i)])
print(" ".join(lst1))

## 錯誤訊息

![image](https://user-images.githubusercontent.com/62045408/77296439-a1daad00-6d22-11ea-92bd-89f8e6d8b414.png)

## 問題描述

不知為何為runtime error

**Comment by secretrw** [comment]
已發現錯誤，謝謝

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。
