### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by ChenPinJu** [coding-coworking-club/python-2020-spring#104]
## 提交連結

https://judge.ccclub.io/status/4e2319cb84a1309ca4c24a684956c6ef

## 程式碼

```python
    a = input()
    lst1 = a.split()
    b = input()
    lst2 = b.split()
    c = str(input())
    if((c in lst1) or (c in lst2)):
        print((c in lst1) or (c in lst2))
    else:
        print((c in lst1) or (c in lst2))
```

## 問題描述

題目要求輸出結果為TRUE或FALSE，而我寫的這個程式被Accepted，但它輸出的結果會是有兩個TRUE或兩個FALSE，請問這樣為什麼會被Accepted呢？又，只輸出一個TRUE或FALSE的寫法是什麼呢？謝謝！

**Comment by chun9425** [comment]
你的程式是對的，並不會跑出兩個 True 或兩個 False，
要不要再試著在 jupyter 執行一次看看?

另外有兩個比較多餘的地方，
首先是第五行
```python
c = str(input())
```
輸入進去的資料本來就預設是 str，
所以不需要轉換為 str。

再來是第6至9行，
其實可以直接使用第七行的程式碼就可以了(也就是下面這行)
```python
print((c in lst1) or (c in lst2))
```
因為這段程式本來就是判斷後直接回傳 boolean
