### ISSUE TITLE
[General] 小明採蘋果

### ISSUE THREAD

**Issue by Gracilis5** [coding-coworking-club/python-2020-spring#106]
## 提交連結

https://judge.ccclub.io/status/5307e7903a74855607bbfe9ea6624361

## 程式碼

```python
apple_number_list = [ int(i) for i in input().split(",") ]
l = []

for i in range(len(apple_number_list)):
    if i == 0: 
        sum_apple = apple_number_list[i] + apple_number_list[i+1]
        l.append(sum_apple)
    elif i == len(apple_number_list)-1:
        sum_apple = apple_number_list[-1] + apple_number_list[-2]
        l.append(sum_apple)
    else: 
        sum_apple = apple_number_list[i-1] + apple_number_list[i] + apple_number_list[i+1]
        l.append(sum_apple)

max_number = max(l)
print (l.index(max_number))
```

## 問題描述

邏輯：
list comprehension後，為每個list中的數字設定if條件

if i == 0: 若是第一個數的話
只要本身的數字加上 [i+1] 的數字即為蘋果總數
elif i == len(apple_number_list)-1: 若是最後一個數的話
只要本身的數字加上 [-2] 的數字即為蘋果總數
else: 其他不是第一或最後一個數的話
就要本身加上左右兩邊的數字才是蘋果總數

每次算完之後的數字都會丟到名為「l」的list中
先算出「l」的最大值，再去找第一個最大值的index

結果跑出runtime error，想請問哪裡出了問題？謝謝～

**Comment by alexypdu** [comment]
Duplicate of #86

**Comment by Gracilis5** [comment]
> Duplicate of #86

了解了！感謝提點！
