### ISSUE TITLE
[Homework 1] 數字數

### ISSUE THREAD

**Issue by b05303111** [coding-coworking-club/python-2020-spring#108]
## 提交連結

a=input() 
listp=list(a.split())
k=0
l=0
for x in listp:
  if str(x).isalpha()==True:
    k+=1
    l+=len(x)
print(k)
print(l)

```python

```

## 錯誤訊息

跑實際程式是對的，但ccclubjudge是錯的，先把list的元素轉為str，利用語法來判別是否為字母，是的話就+1 然後算字數

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將標題及內文格式修正。
