### ISSUE TITLE
[Homework 1] 數字數

### ISSUE THREAD

**Issue by jadechen49** [coding-coworking-club/python-2020-spring#110]
## 程式碼

```python
#數字數
sentence1=input().split()
print(len(sentence1))

sentence2=list(sentence1)
print(sentence2)

chr_num=0
if i in sentence1:
    True==ord(i)      #若可轉換為編碼則不是標點符號
    chr_num+=1
print(chr_num)
```

## 錯誤訊息
在notebook試跑，
出現以下錯誤訊息
<img width="595" alt="Screen Shot 2020-03-24 at 12 03 53 AM" src="https://user-images.githubusercontent.com/62202271/77336775-f69e1800-6d62-11ea-8594-9bccad58a340.png">

## 問題描述
思路是
判斷每個進入迴圈中的i，若可轉換為編碼則不是標點符號，
但在轉換過程中無法成功判斷，
請問ord()/ASCII code是可以再迴圈中使用嗎？
謝謝

**Comment by alexypdu** [comment]
1. 標點符號也是可以用 `ord()` 轉換成 ASCII code 的
2. `ord()` 只能吃一個字元，你給他的是一個長度為 6 的字詞
3. ```python
    True==ord(i)
    ```
    `ord()` 只要回傳非零那這個判斷式就會是 True，然而你前面沒有加上任何 `if/else`，所以這行其實沒有任何作用。

**Comment by jadechen49** [comment]
1.3.了解！謝謝說明～
我想確認一下2.的意思是ord() 沒有辦法在for loop裡使用嗎？
因為for i in loop 意思不是一個一個代進去loop裡嗎？
謝謝

**Comment by alexypdu** [comment]
1. 你附上的程式碼裡面沒有 for loop。
2. `ord()` 當然可以在 for loop 裡面使用，只是看你每次丟進去括號裡面的東西是不是合格的而已。

**Comment by jadechen49** [comment]
好的了解 謝謝！
