### ISSUE TITLE
[General] <problem title>

### ISSUE THREAD

**Issue by mengguo57** [coding-coworking-club/python-2020-spring#115]

**Comment by menghsuan-chou** [comment]
> ## 提交連結
> https://judge.ccclub.io/status/1842e2ba79969aaf5c0e84270aaa5320
> 
> ## 程式碼
> letter=list(input())
> number=list(input())
> lst3=[]
> 
> if len(letter)>len(number):
> number.extend(number[0:len(letter)-len(number)])
> elif len(number)>len(letter):
> del number[len(letter):]
> 
> for i in range (0,len(letter)):
> org_ord=ord(letter[i])
> extra_ord=org_ord+int(number[i])
> final_chr=chr(extra_ord)
> lst3.append(final_chr)
> print("".join(lst3))-->
> 
> ## 錯誤訊息
> ![image](https://user-images.githubusercontent.com/62021733/77403054-96eb4f80-6dea-11ea-86c6-9573575829c3.png)
> 
> ## 問題描述
> 我的作法是先將字串跟數字變成兩個list，再從list中取出元素做轉換。
> 在jupyter跑過兩個題目給的sample都沒有問題，不知道為什麼批改系統會出現runtime error?
