### ISSUE TITLE
[Homework 1] 優惠券

### ISSUE THREAD

**Issue by yachuh** [coding-coworking-club/python-2020-spring#120]
## 提交連結

https://judge.ccclub.io/status/86ca34159c9db4074ac414f713d70c69

## 程式碼

```python
d1 = input()
d2 = input()
d3 = input()
d4 = input()
d5 = input()
discount = [d1, d2, d3, d4, d5]
amount = int(input())

for x in discount:
    if x[0] == '$':
        d_minus = int(x[2:])
        amount -= d_minus
    else:
        d_percent = int(x) / 10
        amount *= d_percent
print(int(amount))
```

## 問題描述

我的解題想法：
1. 把折扣 (d1~d5) 弄成一個 list: `discount`
2. 使用 for 迴圈將 x 帶入 `discount` 這個 list 裡
3. 使用 if 函式判斷 x 是「折價」還是「打折」，判斷方式為：x[0]是否為 '$'
4. 如果 x 是 $ 開頭（比方說 $ 27），
    - 算出要扣多少錢（`d_minus`）：取 x 的第三位 x[2:] 並且轉換成整數
    - 折價後的價錢：`amount -= d_minus`
5. 如果 x 不是 $ 開頭（比方說 7），
    - 算出要打幾折（`d_percent`）：將 x 從字串轉換成整數並且除以 10
    - 打折後的價錢： `amount *= d_percent`
6. 輸出最後的價錢（整數）： `print(int(amount))`

以上在 jupyter notebook 可以成功輸出答案，但在 judge 則顯示為 wrong answer。
不知道是哪裡做錯了呢？

**Comment by chun9425** [comment]
輸出必須是大於零的整數喔，
可以用下面的 input 測試看看：
$ 27
7
8
3
$ 40
259

**Comment by yachuh** [comment]
最後加上了這段 if 來判斷 amount 是否小於 0：
```python
if amount < 0:
    amount = 0
    print(int(amount))
else:
    print(int(amount))
```
這樣就可以了，感謝助教！
