### ISSUE TITLE
[General] 中位數

### ISSUE THREAD

**Issue by tingjia-guo** [coding-coworking-club/python-2020-spring#121]
## 提交連結

https://judge.ccclub.io/status/9a3ed864cfe7e9a4041fa8a0f95f6761
## 程式碼

```python
l = int(input())
list = [int(a) for a in l.split()]

def median(list):
    if len(list) % 2 == 1:
        return float(list[int(len(list) / 2)])
    else:
        return (list[int(len(list) / 2) - 1] + list[int(len(list) / 2)]) / 2.0

print(median(list))
```

## 錯誤訊息

runtime error

## 問題描述

有用jupyter跑過也印出正確答案，但是批改系統都是runtime error
是前面兩行輸入的問題，還是求中位數code有缺漏的地方?  謝謝

**Comment by hyusterr** [comment]
盡量不要用list當變數名
他是內建的函數

TJK-15 <notifications@github.com>於 2020年3月24日 週二，22:01寫道：
