### ISSUE TITLE
[General] 8-2：最長字串

### ISSUE THREAD

**Issue by purcreation0802** [coding-coworking-club/python-2020-spring#122]
## 提交連結

https://judge.ccclub.io/problem/180021
## 程式碼

      
```python
def longest_str(x) :
    list_of_word = []
    for i in range(len(x)) :
        if 0 <= (i+1) < len(x) :
            if len(x[i]) >= len(x[i+1]) :
                list_of_word = []
                list_of_word.append(x[i])
        elif (i+1) == len(x) :
            if len(x[i]) > len(x[i-1]) :
                list_of_word = []
                list_of_word.append(x[i])
    return ''.join(list_of_word)
            
l = input().split()    # apple python Plasma
print(longest_str(l))
```

## 錯誤訊息

於 judge 系統顯示 wrong answer
## 問題描述

思路：
1. 定義 longest_str(x)，x 的資料型態為 list，也就是在倒數第二行的 l = input().split() 
2.  設立一個空串列 list_of_word，並利用 for 在 range(len(x)) 裡跑迴圈
3. 使用 if statement，若 x[i] 字串長度 > x[i+1] 字串長度，就將 x[i] append 到 list_of_word 中
4. 但因為對於 x 中的最後一個元素來說，i+1 會 out of range，因此另立 elif statement 比較　len(x[i]) 和 len(x[i-1])
5. function return ''.join(list_of_word)

問題：
在 jupyter notebook 上用 sample input 測試沒問題，不曉得問題出在哪裡，感謝～

**Comment by purcreation0802** [comment]
不好意思，沒辦法順利在程式碼區塊打出空格

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。

**Comment by purcreation0802** [comment]
> 請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。

感謝，已成功修正

**Comment by jeffery12697** [comment]
這樣寫測不到位置0的單字，可以試試第一個比較多的測資
