### ISSUE TITLE
[Homework 1] 數字數

### ISSUE THREAD

**Issue by ghost** [coding-coworking-club/python-2020-spring#124]
## 提交連結

https://judge.ccclub.io/status/f5c6237e377e4671e85b9dd8308b1508

## 程式碼

```python
sentence = input()

letter = 0

for i in sentence:
    if i.isalpha():
        letter += 1

print(sentence.count(" ") + 1)
print(letter)
```

## 問題描述

除了作業的那兩個測資之外，也試過其他不同的句子，出來的結果都是符合預期。但是丟到系統的時候，跑出Wrong answer。到現在仍找不出原因。
謝謝。

**Comment by jeffery12697** [comment]
這題的空格數加一不一定等於字數，建議用string.split()函式，再去算字數
