### ISSUE TITLE
[General] 2-2：偶數

### ISSUE THREAD

**Issue by Janeohyayaya** [coding-coworking-club/python-2020-spring#13]
## 提交連結

https://judge.ccclub.io/status/6e7179012e39af6acd8b159a04c7f0d2

## 程式碼

```python
a=int(input()), a%2==0

```

## 錯誤訊息

Runtime error

## 問題描述

百思不得其解為什麼會是runtime error >< 還是是因為沒有考慮到甚麼條件?
用jupyter跑的時候感覺很正常。
請教助教或是其他厲害的人的指教><
謝謝!

**Comment by alexypdu** [comment]
你寫的：

```python
a = int(input()), a % 2 == 0
```

其實相當於以下的語法：

```python
a = (int(input()), a % 2 == 0)
```

等號右邊是一個 _tuple_，是 Python 內建的另一種資料型態（就像 `str`、`int` 等等）。

變數賦值的順序是先把等號右邊的 _expression_ 算好再 _assign_ 給等號左邊的 _variable_，
然而等號右邊的 tuple 算到一半時就看到一個不認識的變數 `a`（在 assignment 結束前 `a` 都是不存在的），所以會噴 `NameError: name 'a' is not defined`。

至於你在 Jupyter Notebook 上面會對可能是因為你在其他格子有宣告過 `a` 了，整個 Notebook 是共用記憶體的，每一格的變數都可以在別格取用（也可以複寫）。
