### ISSUE TITLE
[Homework 1] 數字數

### ISSUE THREAD

**Issue by scourgerwill** [coding-coworking-club/python-2020-spring#134]
## 提交連結

https://judge.ccclub.io/status/ed065b86f409e0dbe356baa7560d7384
## 程式碼

```python
a = input()
b = len(str.split(a))
from string import punctuation
c = ''.join(ch for ch in a if ch not in punctuation)
d = len(c)-c.count(" ")
print(b)
print(d)
```

## 錯誤訊息
Wrong Answer

## 問題描述
我在jupyter notebook 跑出一樣的output，請問哪裡寫錯了？

**Comment by cyhsieh264** [comment]
沒有考慮到文章裡可能會有數字的情況喔！

題意是給定一段文章，然而文章當中除了字母，還可能出現各式各樣的字符，若用排除法可能會比較麻煩一點，也難防意外的情況。當然，也可以反過來思考，驗證字元是否為字母，這樣比較不容易出錯，程式效能也會好一些。

**Comment by scourgerwill** [comment]
> 題意是給定一段文章，然而文章當中除了字母，還可能出現各式各樣的字符，若用排除法可能會比較麻煩一點，也難防意外的情況。當然，也可以反過來思考，驗證字元是否為字母，這樣比較不

了解！已修改，謝謝！
