### ISSUE TITLE
[General] 字串加密 II 

### ISSUE THREAD

**Issue by huaitzu** [coding-coworking-club/python-2020-spring#137]
## 提交連結

https://judge.ccclub.io/status/d22650dd371714ccc3f7f3aa8fba8079

## 程式碼

```python
alphabet = input()
number = input()

if len(alphabet) > len(number):
    number = number + number[0 : len(alphabet) - len(number)]
    for i in range(len(alphabet)):
        a = ord(alphabet[i]) + int(number[i])
        print(chr(a),end = "")
elif len(alphabet) == len(number) or len(alphabet) < len(number):
    number = number[0:len(alphabet)]
    for i in range(len(alphabet)):
        a = ord(alphabet[i]) + int(number[i])
        print(chr(a),end = "")
```

## 錯誤訊息

<img width="357" alt="螢幕快照 2020-03-25 下午2 30 52" src="https://user-images.githubusercontent.com/62369916/77508271-48e75200-6ea5-11ea-8d85-f5d06db2c13a.png">

## 問題描述

在jupyter上測試都沒有遇到問題，但在judge上卻出現runtime error，看了很久找不出錯誤，想請助教幫忙解惑，謝謝！

**Comment by jeffery12697** [comment]
`number = number + number[0 : len(alphabet) - len(number)]` 如果字母比數字多很多會不夠補，可以自己測幾個數據
