### ISSUE TITLE
[Homework 1] 小明查單字

### ISSUE THREAD

**Issue by Liao0321** [coding-coworking-club/python-2020-spring#14]
## 提交連結
https://judge.ccclub.io/status/a33210da5c521c3a7d23fb31b1fd5d0c

## 程式碼

```python
words=input()
predix=input()
words=words.split(" ") 
for i in range(0,len(words),1):
    if words[i][0:len(predix)]==predix:
        if i > 0:
            print(" ",end="")
            print(words[i],end = "")
        else:
            print(words[i],end = "")
```

## 錯誤訊息
![查單字](https://user-images.githubusercontent.com/62067023/76431477-92876580-63ec-11ea-9cfa-f742a1619ec2.png)

## 問題描述

解題的思考：
輸入字串和目標前綴後，先以空白斷開字串。
根據字串被斷開後一共有多少個為極限，以i為變數使用for迴圈，以1為間距遞進。

如果那個字的開頭前幾個字元(長度根據前綴長度)跟前綴一樣，
且i>0，不是第一個被篩選出來的字的話，列印出一個空格加上那個單字並刪除掉換行符號。

如果i不大於零，代表是第一個被篩選出來的字，不用印出空格，
直接印出那個單字並刪除換行符號。

問題：
我自己在jupyter上手動檢驗答案看起來是正確的，
但是結果卻是Wrong answer ，不太明白哪裡想錯了。

**Comment by Liao0321** [comment]
程式碼的區塊，我輸入的文字有縮排，也就是4個空格，
但是送出文章後不會顯示空格導致向左對齊。
需要額外改用成 tab來排版嗎？

**Comment by KevinCodePlace** [comment]
## 提交連結
https://judge.ccclub.io/status/3263adfa0f9f9f417fd1884e8fd392c9


## 程式碼



```python
in1=input()  #apple microsoft OSX windows good bad approve disprove
in2=input()  #app

count=0
in1_list=in1.split(" ") #apple microsoft OSX windows good bad approve disprove 分裝到 List

for len1 in range(len(in1_list)): #0-7（in1有 8 個元素）
    for len2 in range(len(in2)):  #0-2(app 三個元素)
        if(len(in1_list[len1])>=len(in2)): #判別每個in1字數是否大於 in2，否則下一行矩陣會爆掉
            if(in1_list[len1][len2]==in2[len2]):#一個一個字元比，比對成功count + 1
                count+=1
        if(count==len(in2)): #假如 app 三個都比對成功，則count=3 意思是前三項相同
            print(in1_list[len1],end=" ")
            count=0 #重新比對
```

## 錯誤訊息
無

## 問題描述

跟上一位同學一樣，在自己的 jupyter上手動檢驗答案看起來是正確的，
但是結果卻是Wrong answer ，不太明白哪裡想錯了

**Comment by jeffery12697** [comment]
我回答第一個同學喔，你寫的邏輯是除了串列位置 0 的資料，其他位置的資料如果符合條件，就會先印空格再印資料，這樣是要建立在位置 0 的資料有符合條件才會對（剛好給的測資都是），假設第一個符合條件的資料在串列位置 1 的地方，前面就會多印一個空格

**Comment by jeffery12697** [comment]
第二個同學，你 count 的歸零是放在比對成功後，那如果今天有一個字串前兩個字母符合條件第三個錯誤，那你 count 就不會跑到歸零那條，就進入下一個迴圈了，可以想想把 count＝0 這個放在哪一個程式區塊內，才會讓每次結束遍歷一個字串就讓 count 歸零
對了～下次建議可以直接開新的 issue，因為如果前一個同學突然想通把 issue close，我們就看不到你的問題嘍
