### ISSUE TITLE
[Homework 1] 小明查單字

### ISSUE THREAD

**Issue by Lola116** [coding-coworking-club/python-2020-spring#140]
## 提交連結

https://judge.ccclub.io/contest/42/problem/001102

## 程式碼

```python
a = input()
b = input() # 開頭

str_lst = a.split()
arr = []

for j in range(len(str_lst)):
    count = 0
    for i in range(len(b)):
#         print(b[i])
        if b[i] == str_lst[j][i]:
            count += 1
#     print(count)
    if len(b) == count:
        arr.append(str_lst[j])
print(" ".join(arr))
```

## 問題描述

在jupyter notebook可以跑出(在附檔)，但放到judge就出現runtime error
不知道是什麼問題qqq
<img width="432" alt="小明查單字" src="https://user-images.githubusercontent.com/62642929/77519603-bce02500-6eba-11ea-8914-1ca5ce31d91e.PNG">

**Comment by jeffery12697** [comment]
`if b[i] == str_lst[j][i]:` 如果要檢查的字首長度比串列裡單字的長度還長，這句會有問題
