### ISSUE TITLE
[Week 4] 數字三角形

### ISSUE THREAD

**Issue by ChuanChuanHsu** [coding-coworking-club/python-2020-spring#146]
## 提交連結
https://judge.ccclub.io/status/66cb7b693491f9820f2f5125969f3415

## 程式碼

```python
n = int(input())
ans = []

while len(ans) != (((1 + n) * n) // 2):
    for j in range(1, 11):
        if len(ans) != (((1 + n) * n) // 2):
            if j != 10:
                ans.append(j)
            else:
                ans.append(0)

for i in range(n):
    for j in range(len(ans)):
        if j <= i:
            print(ans[0], end = "")
            ans.remove(ans[0])
    print()
```

## 錯誤訊息
![圖片](https://user-images.githubusercontent.com/62326373/77548007-eadc5e00-6ee8-11ea-99a3-efb5969c1944.png)

## 問題描述

因為使用while很容易超時，那有辦法用for迴圈或其他方法來縮短嗎？不然只能重寫很難過QAQ

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將標題及內文格式修正。

**Comment by ChuanChuanHsu** [comment]
不好意思，沒注意到標題忘了改！已修正

> 請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將標題及內文格式修正。
