### ISSUE TITLE
[Week 4] 簡易計算機 II

### ISSUE THREAD

**Issue by Janeohyayaya** [coding-coworking-club/python-2020-spring#147]
## 提交連結

https://judge.ccclub.io/status/2cc4ffb7f1f1b8a66bf9f94210c48a98

## 程式碼

```python
def calculator(num1, num2, op):
    if op=="+":
        return int(num1)+int(num2)
    if op=="-":
        return int(num1)-int(num2)
    if op=="*":
        return int(num1)*int(num2)
    if op=="/":
        return int(num1)/int(num2)
num=input().split()
num1=num[0]
num2=num[1]
op=num[2]
print(float(calculator(num1, num2, op)))
```

## 錯誤訊息

Runtime Error
## 問題描述

不好意思~ 想知道為什麼會出現runtime error
(也不好意思討論的時候有事情所以也許有討論到但錯過了><)
想請助教解惑
謝謝!

**Comment by Janeohyayaya** [comment]
`def calculator(num1,num2,op):
    if op=="\"+\"":
        return int(num1)+int(num2)
    if op=="\"-\"":
        return int(num1)-int(num2)
    if op=="\"*\"":
        return int(num1)*int(num2)
    if op=="\"/\"":
        return int(num1)/int(num2)
num=input().split()
num1=num[0]
num1=int(num1)
num1=float(num1)
num2=num[1]
num2=int(num2)
num2=float(num2)
op=num[2]
print(float(calculator(num1,num2,op)))`

不好意思~ 如果改成這樣仍然是runtime error，仍然不知道大概是甚麼問題><

**Comment by Kevinweisl** [comment]
首先，這題是要實作 function ，你不需要自己處理 input()
基本上 function 外的東西你都不需要
也就是說，砍掉以下部分
```python
num=input().split()
num1=num[0]
num2=num[1]
op=num[2]
print(float(calculator(num1, num2, op)))
```

再來，題目是要求 float 但你用 int？
