### ISSUE TITLE
[Week 4] 打字機

### ISSUE THREAD

**Issue by Gracilis5** [coding-coworking-club/python-2020-spring#148]
## 提交連結

https://judge.ccclub.io/status/dfbbed9633a7565343e87e98c648ace8

## 程式碼

```python
string = input ()
string_lst = ['+', '-', '*']
lst = []

for i in range (len(string)):
    if string[i] not in string_lst:
        lst.append(string[i])
    elif (i == 0) and (string[i] in string_lst):
        continue
    else: 
        if string[i] == '+':
            lst.append(lst[-1])
        elif string[i] == '-':
            lst.pop()
        elif string[i] == '*':
            lst = lst*2

print (''.join(lst))
```

## 問題描述

邏輯：按照題目的要求一一寫入條件，在jupyter上面可以寫出正確答案，但丟到judge顯示runtime error，想請問是哪裡出了問題，謝謝～

**Comment by LeeWayne1994** [comment]
'''
n, n_str = input(), ''

for i in range(len(n)):
    if n[i] == "+":
        if n_str != '':
            n_str += n_str[-1]
    elif n[i] == "-":
        if n_str != '':
            n_str -= n_str[:-1]
    elif n[i] == "*":
            n_str = n_str * 2
    else:
        n_str += n[i]
print(n_str)
'''
我也是runtime error...

**Comment by LeeWayne1994** [comment]
https://judge.ccclub.io/status/b9ccb16b104292d7e966fbff753a0bf8

```
n, n_str = input(), ''

for i in range(len(n)):
    if n[i] == "+":
        if n_str != '':
            n_str += n_str[-1]
    elif n[i] == "-":
        if n_str != '':
            n_str -= n_str[:-1]
    elif n[i] == "*":
            n_str = n_str * 2
    else:
        n_str += n[i]
print(n_str)
```
我也是runtime error...

**Comment by jeffery12697** [comment]
你只檢查了第一個位置是不是'+ * -'，那如果是`++OP`這種測資會噴error

**Comment by jeffery12697** [comment]
第二個同學，`n_str -= n_str[:-1]` string 沒有相減的功能，你要做的應該是字串分割，那是這樣
`n_str = n_str[:-1]` 意思讓n_str assign給n_str字串分割的結果

**Comment by LeeWayne1994** [comment]
@jeffery3756 原來如此，將"-="改為"="之後就可以了，感謝你~~

**Comment by mariajhchen** [comment]
@jeffery3756 想問為何
```
print_word = ""
print(print_word[:-1]) #可以印
print(print_word[-1]) #會噴error ```

為何空字串可以index[:-1]但卻不能index[-1]

**Comment by Gracilis5** [comment]
> 你只檢查了第一個位置是不是'+ * -'，那如果是`++OP`這種測資會噴error

了解！修改完成後正確了～謝謝～
