### ISSUE TITLE
[General] 2-2：偶數

### ISSUE THREAD

**Issue by ylho** [coding-coworking-club/python-2020-spring#16]
## 提交連結
https://judge.ccclub.io/status/7e4a3607348120252454380b0057d8f0

## 程式碼

```python
n%2==0
print(n%2==0)
```

## 錯誤訊息

Runtime Error 
## 問題描述

是不是自己邏輯上有問題，試了好幾次都錯了ＱＱ或是我有哪個步驟錯了？

**Comment by alexypdu** [comment]
@ylho 請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正唷！

**Comment by ylho** [comment]
> @ylho 請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正唷！

修改完畢～～～

**Comment by alexypdu** [comment]
你的程式碼缺少讀取輸入的部分唷！

**Comment by ylho** [comment]
成功了！！！！謝謝！！！
