### ISSUE TITLE
[General] def想法問題

### ISSUE THREAD

**Issue by coco31032** [coding-coworking-club/python-2020-spring#161]
## 程式碼

```python
![image](https://user-images.githubusercontent.com/62647847/77626313-22e2b000-6f80-11ea-9595-6caaae43fe99.png)


```

## 問題描述

這是助教的解法，我把他拍起來然後思考！
請問def可以這樣想嗎？
color 是input，lst是output

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。
