### ISSUE TITLE
[Homework 1] 小明查單字

### ISSUE THREAD

**Issue by beanli1202** [coding-coworking-club/python-2020-spring#162]
## 提交連結
https://judge.ccclub.io/contest/42/problem/001102

## 程式碼

```python
word_list = input().split()
prefix = str(input())
found_word = []

for word in range(len(word_list)):
    n = 0
    for p_character in range(len(prefix)):
        w = word_list[word]
        if prefix[p_character] == w[p_character]:
        n += 1       
            
    if n == int(len(prefix)):
        found_word.append(w)
                     
found_word_str = ' '.join(found_word)
print(found_word_str)


```

## 問題描述
![圖片 1](https://user-images.githubusercontent.com/62651986/77650903-faba7780-6fa6-11ea-9600-d853c6fd349d.png)
在jupyter notebook 上結果是對的, 用visualize小工具檢查也找不出問題,但是交作業的時候跑出runtime error

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。

**Comment by beanli1202** [comment]
已修正, 謝謝!

**Comment by alexypdu** [comment]
如果有 `word` 長度比 `prefix` 小呢？

**Comment by beanli1202** [comment]
已解決, 非常感謝!!
