### ISSUE TITLE
[Week 4] 簡易計算機 ll

### ISSUE THREAD

**Issue by Kailey-0324** [coding-coworking-club/python-2020-spring#163]
## 提交連結

https://judge.ccclub.io/contest/45/problem/000401

## 程式碼

def calculator(num1, num2, op):
    if op =="+":
        return num1+num2
    elif op =="-":
        return num1-num2
    elif op =="*":
        return num1*num2
    elif op =="/":
        return num1/num2
num1 = float(input())
num2 = float(input())
op = "+" or "-" or "/" or "*"

```python

```

## 錯誤訊息

Runtime error

## 問題描述

盡自己所能打出希望符合題目的程式，但我不知道錯在哪裡......想請問這個是錯在哪裡?是有什麼地方沒考慮到嗎?還是關於def這個函式是錯的?

**Comment by Kevinweisl** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。
