### ISSUE TITLE
[Homework 1] 數字數 

### ISSUE THREAD

**Issue by b05303111** [coding-coworking-club/python-2020-spring#164]
## 提交連結

https://judge.ccclub.io/contest/42/problem/001103

## 程式碼

a=input() 
listp=list(a.split())
k=0
l=0
for x in listp:
    if x.isalpha() == True: 
      k+=1
      l+=len(x)
print(k)
print(l)

## 錯誤訊息

![image](https://user-images.githubusercontent.com/62551229/77654488-17a57980-6fac-11ea-81c4-54dde9bbc3cd.png)

## 問題描述

 
在實際python跟visualizer 跑是正確的，但ccclubjudge答案是錯的

**Comment by Kevinweisl** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。
