### ISSUE TITLE
[General] python當執行跑[*]重新整理畫面會卡住

### ISSUE THREAD

**Issue by DindinWang** [coding-coworking-club/python-2020-spring#166]
## 程式碼

```python

```

## 問題描述

然後就一直停留在這個畫面

<img width="1181" alt="螢幕快照 2020-03-26 下午10 18 00" src="https://user-images.githubusercontent.com/35460603/77657205-ec248e00-6faf-11ea-83a9-8a0f5f46dcb0.png">

**Comment by Kevinweisl** [comment]
這時候你按上面的 `+` 會發生什麼事？


或是重新開一個 `.ipynb` 檔呢？右邊 `new` -> `python3`
![image](https://user-images.githubusercontent.com/12825883/77694768-923ebb00-6fe5-11ea-8a6f-34ede711c8b8.png)
