### ISSUE TITLE
[Homework 1] 二十六進位

### ISSUE THREAD

**Issue by Jimmy3321** [coding-coworking-club/python-2020-spring#168]
## 提交連結

https://judge.ccclub.io/status/1f2138a0af5f6fa7cb91ca35d554fece

## 程式碼

import math

abc_list = ['A','B','C','D','E','F','G','H','I','J','K','L',
            'M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']

number = int(input())

number_list = []
char_list = []
i = 0

if number < 26:
    number_list.append(number)
else:
    while number >= math.pow(26,i):
        i += 1
        if i == 0:
            k = 1
            number_list.append(k)

    for i in range(i):
        left = number % 26
        divide = number / 26
        number = divide
        if left > 0:
            number_list.append(left)

#print (number_list)
number_list.reverse()
#print (number_list)
result = ''
for i in range(len(number_list)):
    j = number_list[i]
    #print (j)
    result += abc_list[j]

print (result)

## 錯誤訊息

 Runtime Error。 

## 問題描述

執行起來正常，給了兩個測試問題答案也正確，但一直出現錯誤訊息。

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。
