### ISSUE TITLE
[General] 平均成績的另一種算法？

### ISSUE THREAD

**Issue by LeeWayne1994** [coding-coworking-club/python-2020-spring#17]
## 程式碼

```python

Scores = [60, 69, 73, 85, 91]

print((sum(Scores[0:5])//(len(Scores))))

```

## 錯誤訊息

![1](https://user-images.githubusercontent.com/61942248/76489446-53482b80-6463-11ea-8168-c5800898cff6.PNG)

## 問題描述

今天在Udemy上迴圈時，影片以 for i range(len(scores)) 方式要計算成績平均，給定的五科成績為：Scores = [60, 69, 73, 85, 91]

我在想這題能不能用迴圈以外的方式解，所以在jupyter上打了上述的程式碼，五科加總是378，len(Scores)是5，正確答案是75.6，但他跳出來的outcome是75。我後來想說是不是因為預設int，改用浮點數修改程式為：print((sum(Scores[0:5])//(float(len(Scores)))))，但outcome也只是變成75.0。

想請問是哪裡出了問題QQ

**Comment by chun9425** [comment]
// 的運算方式是相除取整數喔，
如果是普通相除的話是用 /

**Comment by LeeWayne1994** [comment]
啊，真是太笨了，感謝你
