### ISSUE TITLE
[General] 最大公因數

### ISSUE THREAD

**Issue by JOE-CHOU88** [coding-coworking-club/python-2020-spring#170]
## 程式碼

```python
def gcd(m,n):
    if n==0:
        return m
    else:
        return gcd(n,m%n)
num1=int(input())
num2=int(input())
print(gcd(num1,num2))
```

## 問題描述

程式碼是出自Medium指定閱讀的，我有兩個問題：
(1)輾轉相除法不是強調用較小的數對另一數取整數嗎，那此行程式碼要如何分辨m,n哪一個比較小?（如10%45和45%10結果明顯不同）
(2)若輸入值有其中一個是0怎麼辦?

**Comment by jeffery12697** [comment]
1. 那你可以先用 if 來判斷大小再做不同處理
2. 這題應該不會有這個情況

**Comment by JOE-CHOU88** [comment]
1. 其實上面的程式碼執行起來能正確判斷最大公因數，我是想問這個程式碼的運算過程中是如何判斷45%10（舉例--大%小），而非10%45（舉例--小%大）?
2. 我有試過輸入10,0，卻可以跑出10?
![最大公因數](https://user-images.githubusercontent.com/62171839/77844586-65072e00-71da-11ea-8dd6-f187622b8e4a.png)
