### ISSUE TITLE
[General] 停車位順位

### ISSUE THREAD

**Issue by Gracilis5** [coding-coworking-club/python-2020-spring#178]
## 提交連結

https://judge.ccclub.io/status/4d85865c76b48de2ac55b1621e5c5070

## 程式碼

```python
n = int (input ())
num = 1
all_lst = []
while num <= n:
    lst = [ str(i) for i in input ().split() ]
    all_lst.append(lst)
    num += 1

def number_type(s):
    if int(s[3]) % 2 != 0:
        number = 0
    else:
        number = 1
    return number
all_lst = sorted(all_lst, key = number_type)

def year(s):
    year = int(s[2])
    return year
all_lst = sorted(all_lst, reverse = True, key = year)

def building(s):
    building = s[1]
    return building
all_lst = sorted(all_lst, key = building)

for i in all_lst: 
    ID = i[0]
    print (ID)
```

## 問題描述

邏輯：從後面的條件一層一層用sorted寫回來（門牌號碼奇偶 -> 年資 -> 棟別），jupyter跑出來答案都是對的，不知道為何是wrong answer，謝謝～

**Comment by jeffery12697** [comment]
可以看一下 https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-f3148ebb33a4 複數條件的排序的地方，試著把三種排序寫在同一個def

**Comment by Gracilis5** [comment]
> 可以看一下 https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-f3148ebb33a4 複數條件的排序的地方，試著把三種排序寫在同一個def

已修改後accepted，謝謝～
