### ISSUE TITLE
[Week 2] 小明審報名表

### ISSUE THREAD

**Issue by yachuh** [coding-coworking-club/python-2020-spring#18]
## 提交連結

https://judge.ccclub.io/status/92629c0346be7c3a44d01f954c7f949b
## 程式碼

```python
s = input()
if s == "":
    print("skip")
elif s == "social science":
    print("A")
elif s == "NTU" or s == "external":
    print("B")
```

## 問題描述

`if` 的思路：
1. 先判斷 input 是否為空，若符合則輸出 skip
2. 再用 `elif` 判斷 input 是否為 social science，若符合則輸出 A
3. 再用 `elif` 判斷 input 是否為 social science 或 external ，若符合輸出 B

不知道這樣哪裡有問題呢？

**Comment by chun9425** [comment]
學員的資訊可能為 social science, NTU, external, undefined 這四種，
所以輸入不會有空字串喔!

**Comment by yachuh** [comment]
@chun9425 瞭解，應該是我看題意誤會了，以為要將「學員沒有填入資訊」用空字串表示。

因為 contest 到期了無法再 submit，不知道改成以下這樣是否正確呢？

```Python
s = input()
if s == "undefined":
    print("skip")
elif s == "social science":
    print("A")
elif s == "NTU" or s == "external":
    print("B")

```

感謝助教！

**Comment by chun9425** [comment]
這樣應該就沒問題了喔~
之後 week2 的題目也會移到 problems 裡面，
可以再試看看 ^ ^

**Comment by yachuh** [comment]
謝謝助教 @chun9425 ！
