### ISSUE TITLE
[General] 檢查日期

### ISSUE THREAD

**Issue by yaen1105** [coding-coworking-club/python-2020-spring#180]
## 提交連結

https://judge.ccclub.io/status/a5fd9f03734abc58e64a8e4943e888cd

## 程式碼

```python
_ = []
while _ != "end":
    _ = input().split(", ")
    _int = [int(item) for item in _]
    for item in _int:
        if item <0:
            print ("error")
            break
    for i in range(0, len(_)):
        if len(_[i]) != 4:
            print ("error") 
            break
        if len(_[i+1]) > 2:
            print ("error")
            break
        if int(_[i+1]) >12:
            print ("error")
            break
        if int(_[i+1]) in [1,3,5,7,8,10,12]:
            if int(_[i+2]) > 31:
                print ("error")
                break
            else:
                print ("OK")
            break
        if int(_[i+1]) in [4,6,9,11]:
            if int(_[i+2]) >30:
                print ("error")
                breal
            else:
                print ("OK")
            break
        if int(_[i+1]) == 2:
            if int(_[i+2]) >28:
                print ("error")
                break
            else:
                print ("OK")
            break
        else:
            print ("OK")
```

## 錯誤訊息

 Runtime Error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-89e440061492> in <module>
      2 while _ != "end":
      3     _ = input().split(", ")
----> 4     _int = [int(item) for item in _]
      5     for item in _int:
      6         if item <0:

<ipython-input-1-89e440061492> in <listcomp>(.0)
      2 while _ != "end":
      3     _ = input().split(", ")
----> 4     _int = [int(item) for item in _]
      5     for item in _int:
      6         if item <0:

ValueError: invalid literal for int() with base 10: 'end'

## 問題描述

用jupyter notebook和visualize python都可以跑出正確答案，
(但輸入end之後，jupyter有顯示上列Value Error)
judge則是顯示Runtime Error

**Comment by alexypdu** [comment]
範例測資並沒有通過唷。

**Comment by yaen1105** [comment]
輸入日期範例之後的輸出是噴對的答案，
但最後輸入end之後會噴Value Error，
我不知道應該要從哪邊改
<img width="663" alt="Screen Shot 2020-03-31 at 8 22 13 PM" src="https://user-images.githubusercontent.com/61906327/78026101-b4419000-738d-11ea-9f63-8400b5fa69b1.png">
<img width="652" alt="Screen Shot 2020-03-31 at 8 23 08 PM" src="https://user-images.githubusercontent.com/61906327/78026105-b60b5380-738d-11ea-97d7-ca50a7fa7b11.png">

**Comment by alexypdu** [comment]
你在做這行：

```python
_int = [int(item) for item in _]
```

之前要檢查一下是不是 `end` 吧。

**Comment by yaen1105** [comment]
https://judge.ccclub.io/status/e22f9aa8dc50288d40dfac683ef9127b
已經對end這個做了修正，
jupyter測試也ok，
但judge還是wrong answer
檢查了很多遍，
還是不曉得漏掉什麼，
請助教幫忙看看，非常感謝！

**Comment by alexypdu** [comment]
年份不一定要是四位數唷。
