### ISSUE TITLE
[Homework 2] 矩陣變形

### ISSUE THREAD

**Issue by explain-saying** [coding-coworking-club/python-2020-spring#181]
## 提交連結

https://judge.ccclub.io/status/505df39af47fe96bb32e9abef9763d45
## 程式碼

```python
M_N=input().split()
O_P=input().split()

line = [[0]*int(M_N[1])]*int(M_N[0])
for i in range(int(M_N[0])):
    line[i] = input().split()
string=""
string1=""
for i in range(0,int(M_N[0])):
    for j in range(0,int(M_N[1])):
        string=string+" "+line[i][j]
string=string.split()

loop=int(O_P[1])-(int(O_P[1])-1)
for i in range(len(string)):
    if loop==int(O_P[1]):
        string1=string1+" "+string[i]         
        print (string1.lstrip())
        string1=""
        loop=1
    else:
        string1=string1+" "+string[i]
        loop=loop+1
```

## 問題描述

1. 請問一下，關於將資料讀進來的語法，這樣寫可以嗎? 因為資料不是固定行數
2. 執行後的結果出現Runtime Error，試了很多矩陣組合，還是找不到bug，再麻煩助教提示，謝謝。

**Comment by chun9425** [comment]
把資料讀進來的方法是對的，
Runtime Error 的原因應該是出在前面這段

```python
string=""
string1=""
for i in range(0,int(M_N[0])):
    for j in range(0,int(M_N[1])):
        string=string+" "+line[i][j]
string=string.split()
```
你的寫法是先把矩陣按照原本的維度讀進來後再把他壓平，
這樣的想法是對的，但有點複雜化了。
既然最後都要把他壓平，
那一開始其實就不需要建構成輸入矩陣的維度了。

也許你可以嘗試看看用串列相加的方式去處理輸入資料的部分。
希望下面這個例子對你有幫助喔 ^ ^
```python
a = []
b = [1, 2, 3, 4]
c = [5, 6, 7, 8]

# a + b 為 [1, 2, 3, 4]
# a + b + c 為 [1, 2, 3, 4, 5, 6, 7, 8]
```

**Comment by explain-saying** [comment]
謝謝助教~
感謝~^0^

> 把資料讀進來的方法是對的，
> Runtime Error 的原因應該是出在前面這段
> 
> ```python
> string=""
> string1=""
> for i in range(0,int(M_N[0])):
>     for j in range(0,int(M_N[1])):
>         string=string+" "+line[i][j]
> string=string.split()
> ```
> 
> 你的寫法是先把矩陣按照原本的維度讀進來後再把他壓平，
> 這樣的想法是對的，但有點複雜化了。
> 既然最後都要把他壓平，
> 那一開始其實就不需要建構成輸入矩陣的維度了。
> 
> 也許你可以嘗試看看用串列相加的方式去處理輸入資料的部分。
> 希望下面這個例子對你有幫助喔 ^ ^
> 
> ```python
> a = []
> b = [1, 2, 3, 4]
> c = [5, 6, 7, 8]
> 
> # a + b 為 [1, 2, 3, 4]
> # a + b + c 為 [1, 2, 3, 4, 5, 6, 7, 8]
> ```

**Comment by explain-saying** [comment]
謝謝助教~
感謝~^0^
