### ISSUE TITLE
[General] 8-1：乘積最大值

### ISSUE THREAD

**Issue by Szu-Wei** [coding-coworking-club/python-2020-spring#185]
## 提交連結

https://judge.ccclub.io/status/3af0ce3c255024c8281d6d77a7e113e1

## 程式碼

```python

def max_mul(l):

    mul_l = [ i * l[l.index(i)-1] for i in l if l.index(i) != 0]
    return max(mul_l)

l = [int(i) for i in input().split()]
print(max_mul(l))

```

## 錯誤訊息

Runtime Error

## 問題描述

這段我用測資在jupyter上跑都是正確的,可是放進judge卻沒辦法accepted...
想知道是哪裡錯誤以及修正的方向,謝謝

**Comment by Neptune2901** [comment]
```Python
l.index(i)
```
這個會找l裡面與i匹配的第一個值的index
所以如果測試資料裡面有任意數跟第一個相同，l.index(i)就會回傳0
```Python
mul_l = [ i * l[l.index(i)-1] for i in l if l.index(i) != 0]
```
這時候後面的l.index(i)會阻止mul_l新增元素

可以測試看看 1 1 1 1 1這組測資
