### ISSUE TITLE
[Homework 2] 小明打魯石

### ISSUE THREAD

**Issue by tom192180** [coding-coworking-club/python-2020-spring#194]
## 提交連結
https://judge.ccclub.io/status/a962a021156b1856a1defcb60355b43e

## 程式碼

```python
#小明打魯石
monster1 = input().split() # 怪物1 X(攻擊) Y(血量)
monster2 = input().split() # 怪物2 W(攻擊) U(血量)

def countfinalhp(win,lose):
    if int(win[2])  % int(lose[1]) == 0:
        return int(int(win[2]) - int(lose[1])*(int(lose[2])//int(win[1])))
    else:
        return int(int(win[2]) - int(lose[1])*(int(lose[2])//int(win[1])+1))

if int(monster1[1]) >= int(monster2[2]): # X >= U
    if int(monster2[1]) < int(monster1[2]): # W < Y:
        print(monster1[0], monster1[1], int(monster1[2]) - int(monster2[1]))
    else: # W >= Y 
        print("tie")
else: # X < U:
    if int(monster2[1]) < int(monster1[2]): # W < Y:
        if int(monster1[2])//int(monster2[1]) == int(monster2[2])//int(monster1[1]):#兩隻平手
            print("tie")
        elif int(monster1[2])//int(monster2[1]) > int(monster2[2])//int(monster1[1]): # 怪物1 win
            print(monster1[0], monster1[1], countfinalhp(monster1,monster2))
        else:
             print(monster2[0], monster2[1], countfinalhp(monster2,monster1))# W > Y怪物2 win  

```

## 錯誤訊息
wrong answer :(

## 問題描述

嗚嗚這題找錯誤找了四個小時><一直找不到錯在哪。
思考模式:
我把兩隻怪物對打的情形，從其中一隻怪物視角出發去推，
對於一隻怪物(say A)而言，A遇到的對手(say B)有兩種可能:

1.A的攻擊大於等於B的血量。此可能又有以下2種子集合:
  (1)A的攻擊大於等於B的血量 且 B的攻擊小於A的血量。 >>>A win
  (2)A的攻擊大於等於B的血量 且 B的攻擊大於等於A的血量。 >>> Tie

2.A的攻擊小於B的血量。此可能又有以下2種子集合:
   (1)A的攻擊小於B的血量 且 B的攻擊小於A的血量。 >> 透過比較(A血量除以B攻擊)與 (B血量除以A 
         攻擊)的商數，商數大的贏，商數小的輸，商數相同則是Tie。
   (2)A的攻擊小於B的血量 且 B的攻擊大於等於A的血量。 >>>B win

程式建模如上><但還是不知道錯在哪，不知道是思考有盲點還是程式有盲點。
已經下了很多測資，還是找不到錯誤QQ再拜託助教了~~

**Comment by jeffery12697** [comment]
不一定是一回合喔，有可能打了Ｎ個回合才分出勝負

**Comment by tom192180** [comment]
助教~我我2(1)有考慮到此點><
就是當A的攻擊小於B的血量 且 B的攻擊小於A的血量，就會有N回合的情況產生。
在此我是用  透過比較(A血量除以B攻擊)與 (B血量除以A攻擊)的商數，商數大的贏，商數小的輸，商數相同且餘數不同時是則再討論~~推測我應該是有情況沒考慮到><謝謝助教!!

**Comment by tom192180** [comment]
助教~~我剛試了1.5HR，真心覺得考慮各種情況不是一種有效率的方式><
至少下了二三十個條件吧...><
我決定砍掉重練換別種方式了~~~

**Comment by tom192180** [comment]
> 不一定是一回合喔，有可能打了Ｎ個回合才分出勝負

助教!!我後來用while迴圈搞定了>< 這題寫了至少7個小時有吧XDDD~~旋轉加跳舞ING XD
這題讓我學到有時候不要太執著一種解法，退後原來是向前XD
