### ISSUE TITLE
[General] 9-1：數字總和排序

### ISSUE THREAD

**Issue by pissaq** [coding-coworking-club/python-2020-spring#197]
##提交連結

https://judge.ccclub.io/status/724b79fb39b3659d4abcc29dd98f1707

## 程式碼

```python
num =[int(i) for i in input().split()]

def calculatesum(num):
    for item in num:
        if len(str(item)) > 1:
            num_lst = list(str(item))
            i = 0
            sum = 0
            while i < len(num_lst):
                sum = sum + int(num_lst[i])
                i = i+1
            else :
                sum = item
    return sum

num = sorted(num,key=calculatesum)
print(int(num))
```

## 錯誤訊息

[image](https://user-images.githubusercontent.com/61981032/77893388-6ef66300-72a6-11ea-91c6-ed3bdab128c1.png)

## 問題描述

不是很理解錯誤訊息，先驗證過函式裡面的邏輯正確，才改成function，但就出現'int' object is not iterable了，想請問該怎麼解決?。

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。

**Comment by pissaq** [comment]
> 請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。

**Comment by pissaq** [comment]
已修改內文格式，謝謝

**Comment by alexypdu** [comment]
```python
for item in num:
```

`num` 是整數 `int` 的話當然不能跑（iterate） for loop。
