### ISSUE TITLE
[Homework 1] 數字數

### ISSUE THREAD

**Issue by hlshao** [coding-coworking-club/python-2020-spring#199]
## 提交連結

https://judge.ccclub.io/contest/42/problem/001103

## 程式碼

```python
s = str(input())
wordlist = s.split(" ")
print(len(wordlist))
print(sum(c.isalpha() for c in s))
```

## 問題描述

感覺已經符合需求，但被判wrong answer
s = str(input())
wordlist = s.split(" ")  ##分解每個單字
print(len(wordlist))  ## 算list內元素數量
print(sum(c.isalpha() for c in s)) ##算list內字母數量

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。

請不要自創標題格式。

**Comment by hlshao** [comment]
renewed context, thanks.

**Comment by alexypdu** [comment]
Duplicate of #32
