### ISSUE TITLE
[General] 無法打開 jupyter notebook

### ISSUE THREAD

**Issue by tom192180** [coding-coworking-club/python-2020-spring#2]
## 程式碼

```python

```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/61943353/76166563-65dc0f80-619a-11ea-8a88-49db4fb42937.png)

## 問題描述
我依照「跟著商管女孩一起學 Python」windows系統安裝，python接續 安裝jupyter notebook的指令都有依照著做，但是最後要打開一直跳出上面的圖。我有依照命令系統說明，用自己手動複製連結，是可以進入notebook的，但是輸入code會一直無法執行。

我上網查有人好像跟我有一樣的情況
https://www.reddit.com/r/learnpython/comments/e9wji2/jupyter_notebook_python_38_terminals_not/famdcny/

但是不知道為什麼還是一直失敗><因此PO文請教，謝謝你們!!

**Comment by alexypdu** [comment]
請問你有使用 Anaconda 安裝 Python 嗎？另外先不要使用 PowerShell，改用 `cmd.exe` 試試看？

**Comment by Kevinweisl** [comment]
在商管女孩中我們是教使用命令視窗（cmd）開啟 jupyter notebook 喔！
方法是 `shift + 右鍵` => `開起命令視窗` ，影片裡片應該有提到（大約在 1:25 的地方）
開啟之後輸入 `jupyter notebook` 應該就可以順利打開你的 jupyter

**Comment by tom192180** [comment]
1.我以前有安裝anaconda!但我重新安裝python 有把它移除。
2.因為昨天按右鍵只看到powershell 沒有看到cmd,我也不知道那根筋以爲它們是一樣的東西（原來不一樣><)我下班會依照影片用cmd試試看的！
3.謝謝兩位的回覆！！

**Comment by pinwenyang** [comment]
我也有同樣的問題>"<
我也是按 shift+滑鼠右鍵，但沒有出現開啟命令視窗的選項，只有開啟PowerShell的選項QQ
請問這種狀況，要從哪裡找到開啟命令視窗的選項呢？

**Comment by alexypdu** [comment]
用 Windows 左下角功能表點開內建的搜尋功能搜尋 `cmd` 應該就有了喔！

**Comment by pinwenyang** [comment]
謝謝您的說明! 我有打開命令視窗了，但是輸入jupyter notebook之後，一樣是出現下面的圖>"< 我是不是應該直接重灌啊?
![image](https://user-images.githubusercontent.com/61964529/76201784-c87eeb00-622e-11ea-9409-27865b979d6f.png)

**Comment by alexypdu** [comment]
@pinwenyang 你打開瀏覽器，網址輸入圖中 `http://localhost:8888/?token=...` 那一串試試看。

**Comment by dada8397** [comment]
這樣應該是有成功 run 起來唷 XD（訊息內寫說 `The Jupyter Notebook is running at:` ）
兩位看起來都有成功
照 @alexypdu 說的複製圖中的那串網址在瀏覽器打開就可以看到 jupyter notebook 了

**Comment by alexypdu** [comment]
@dada8397 你怎麼在這裡 XD

**Comment by dada8397** [comment]
@alexypdu 咦...想說上來看看同學們的疑問如果有可以幫忙的就幫忙 XD
我也是 python 新手就是了 XD

**Comment by tom192180** [comment]
回報結果：
我回家嘗試用cmd還是不能，跟原本貼的畫面是一樣的
另外雖然直接複製ｃｍｄ內的網址，可以進去jupyter notebook, 
但kernel會一直說自己dead，按run也無反應。
只會跑出In[*]的圖號。

不過我後來在我的電腦建立一個新的使用者，依照步驟就可以了!
我的推測是原本的帳戶有可能安裝過Anaconda 或者atom之類的，
雖然重新安裝前有先移除，導致原本的使用者安裝一直失敗的結果。(但也只是推測XD)

不過現在終於可以用囉!覺得開心~
謝謝各位的協助!!

**Comment by sean2249** [comment]
> 我也有同樣的問題>"<
> 我也是按 shift+滑鼠右鍵，但沒有出現開啟命令視窗的選項，只有開啟PowerShell的選項QQ
> 請問這種狀況，要從哪裡找到開啟命令視窗的選項呢？

@pinwenyang
可參考下面網址，將 shift + 滑鼠右鍵 改成 cmd
https://www.itread01.com/content/1544820496.html
