### ISSUE TITLE
[General] 6-1：因數

### ISSUE THREAD

**Issue by loxa1067** [coding-coworking-club/python-2020-spring#20]
## 提交連結

https://judge.ccclub.io/status/c1b0a6b294810a0375349b782fe0b5e1
## 程式碼
      

```python
n=int(input())
for i in range(1,n+1):
    if n%i==0:
        print(n//i)
    else:
        pass

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/61943364/76538988-1a3ba580-64bb-11ea-8ddb-a45d6685c42d.png)

## 問題描述

不知道怎麼讓因數從小排到大

**Comment by Peterorr** [comment]
試圖讓迴圈倒著數？
調整 range 裡面的參數
