### ISSUE TITLE
[Homework 2] 台灣大公園

### ISSUE THREAD

**Issue by sunmi3172** [coding-coworking-club/python-2020-spring#200]
## 提交連結

https://judge.ccclub.io/status/1189d60a06a5d564785400401313b2f5
## 程式碼

```python
M = int(input())
matrix = []
for i in range(M):
    I = input().split()
    matrix.append(I)
dic = dict(sorted(matrix))
alph = input().split()
lst = []
for i in alph:
    if i in dic.keys():
        lst.append([i, dic[i]])       
lst.sort(key =lambda x : x[1])
N = int(input())
result = []
for i in range(N):
    result.append(lst[i][0])
print(' '.join(result))
```

## 問題描述

不知道為什麼在judge是錯的？
邏輯是找出alph (遊客的願望清單) 在matrix的list，並排好印出來
更新輸出格式後還是錯的QQ

**Comment by Gracilis5** [comment]
我也是一樣的寫法結果wrong answer，想知道錯誤出在哪，謝謝～

**Comment by Neptune2901** [comment]
看起來是輸出格式錯誤? 可以參考sample output 2的輸出格式調整
另外
```Python
dic = dict(sorted(matrix, key = lambda x : x[1] ))
```
這邊應該可以少一次排序的動作

**Comment by Gracilis5** [comment]
> 看起來是輸出格式錯誤? 可以參考sample output 2的輸出格式調整
> 另外
> 
> ```python
> dic = dict(sorted(matrix, key = lambda x : x[1] ))
> ```
> 
> 這邊應該可以少一次排序的動作

我原本也以為是因為輸出格式，所以有把答案印在一個list再用join輸出，結果答案還是wrong answer，感覺不是輸出格式的問題 QQ

**Comment by sunmi3172** [comment]
> > 看起來是輸出格式錯誤? 可以參考sample output 2的輸出格式調整
> > 另外
> > ```python
> > dic = dict(sorted(matrix, key = lambda x : x[1] ))
> > ```
> > 
> > 
> > 這邊應該可以少一次排序的動作
> 
> 我原本也以為是因為輸出格式，所以有把答案印在一個list再用join輸出，結果答案還是wrong answer，感覺不是輸出格式的問題 QQ

同意感覺不是輸出格式的問題 QQ
程式碼已更新，有處理減少排序的問題~
但在judge上還是顯示錯誤QQ

**Comment by f629** [comment]
先謝謝助教及同學指導
dict sorted的結果如下
[['A', '1'], ['J', '10'], ['K', '11'], ['L', '12'], ['M', '13'], ['B', '2'], ['C', '3'], ['D', '4'], ['E', '5'], ['F', '6'], ['G', '7'], ['H', '8'], ['I', '9']]
10 ,11,12,13 卻排在 2的前

其中
 lst.append([i, dic[i]]) 
改成
 lst.append([i, int(dic[i])])
試試看

**Comment by Gracilis5** [comment]
> 先謝謝助教及同學指導
> dict sorted的結果如下
> [['A', '1'], ['J', '10'], ['K', '11'], ['L', '12'], ['M', '13'], ['B', '2'], ['C', '3'], ['D', '4'], ['E', '5'], ['F', '6'], ['G', '7'], ['H', '8'], ['I', '9']]
> 10 ,11,12,13 卻排在 2的前
> 
> 其中
> lst.append([i, dic[i]])
> 改成
> lst.append([i, int(dic[i])])
> 試試看

了解了～謝謝

**Comment by sunmi3172** [comment]
終於過了QQ
感謝大家 !!!
