### ISSUE TITLE
[General] 8-1：乘積最大值

### ISSUE THREAD

**Issue by LT-Weng** [coding-coworking-club/python-2020-spring#205]
## 提交連結

https://judge.ccclub.io/status/718062bff05081fa5ed368ed2d5f670f
## 程式碼

```python
def max_mul(l):
    l=input().split()
    L=[int(x) for x in l]    
    for i in range(len(L)-1):
        mul=[]
        mul.append(L[i]*L[i+1])
    print(max(mul)) 
max_mul('1 -2 -3 4 -5 -6')
```

## 錯誤訊息

<img width="309" alt="螢幕快照 2020-03-31 上午10 26 28" src="https://user-images.githubusercontent.com/62595678/77980598-3f913600-733a-11ea-9edc-dfed51118298.png">
<img width="578" alt="螢幕快照 2020-03-31 上午10 25 53" src="https://user-images.githubusercontent.com/62595678/77980601-428c2680-733a-11ea-9934-a1efc440a3f4.png">

## 問題描述

用jupyter notebook跑找不到問題，也試了其他把input做成list的方法，但還是WA，不太知道問題在哪裡。

**Comment by alexypdu** [comment]
你不能沒有處理輸入啊，你現在是直接寫死。
