### ISSUE TITLE
[General] 數字最小值排列

### ISSUE THREAD

**Issue by JefferyMC** [coding-coworking-club/python-2020-spring#207]
## 提交連結
https://judge.ccclub.io/status/e0da5f6ee33960cd61524248f168cbd5

## 程式碼

```python
origin = int(input())
origin_lst = [i for i in str(origin)]
arrange = sorted(origin_lst)
total = 0

for i in arrange:
    if i == "0":
        total += 1
        arrange.remove(i)

arrange = arrange[0:1]+["0"]*total+arrange[1:len(arrange)]
output = "".join(arrange)
print(int(output))
```

## 錯誤訊息
Wrong Answer

## 問題描述
提交連結是 Accept，是我將 po 上來的程式碼中的 for loop 拆成兩個，想請問 po 上來的程式碼中的 for loop 會出現什麼問題嗎？輸出的時候 0 都會不見，但我看不出來有什麼問題......是在跑 loop 的時候不能更改 list 嗎？

**Comment by jeffery12697** [comment]
因為 remove 會更動list的長度，要跑 for-loop 你可以想像有一個標籤在對 list 的按 index 值照順序將內容物指向 i 這個變數，假設現在貼的標籤是停留在 index=3 的位置，remove 會把參數的位置東西清掉，後面的東西會往前遞補，所以原本是 index 5 的東西變到 index 4 ，但跑 for-loop 程式並不知道，所以當他指向完 index = 3 後 他就去指向 index = 4 的東西 ， 但對我們一開始來說那原本是 index = 5 的東西，所以如果在迴圈中跑很多次  remove 函式的話，迴圈數會比你覺得得少很多，最後零也會清不乾淨。

**Comment by JefferyMC** [comment]
> 因為 remove 會更動list的長度，要跑 for-loop 你可以想像有一個標籤在對 list 的按 index 值照順序將內容物指向 i 這個變數，假設現在貼的標籤是停留在 index=3 的位置，remove 會把參數的位置東西清掉，後面的東西會往前遞補，所以原本是 index 5 的東西變到 index 4 ，但跑 for-loop 程式並不知道，所以當他指向完 index = 3 後 他就去指向 index = 4 的東西 ， 但對我們一開始來說那原本是 index = 5 的東西，所以如果在迴圈中跑很多次 remove 函式的話，迴圈數會比你覺得得少很多，最後零也會清不乾淨。

了解，原來真的會這樣，謝謝解答^^
