### ISSUE TITLE
[General] 停車位順位

### ISSUE THREAD

**Issue by yaen1105** [coding-coworking-club/python-2020-spring#208]
## 提交連結
https://judge.ccclub.io/status/6c88b67efd2ad8c2ba088f3b810c6979

## 程式碼

```python
n = int(input())
num = 1
_input = []
all_lst = []
while num <= n:
    _input = input().split()
    num += 1
    all_lst.append(_input)

def multi_sort(l):
    year = int(l[2])//5
    if year >= 2:
        year == 2    
    return (l[1], -(year), -(int(l[3])%2))

all_lst=sorted(all_lst, key=multi_sort)
for i in range(len(all_lst)):
    print (all_lst[i][0])
```

## 問題描述

jupyter測試ok，但judge顯示wrong answer，不曉得是哪個環節漏掉了...
<img width="503" alt="Screen Shot 2020-03-31 at 9 29 12 PM" src="https://user-images.githubusercontent.com/61906327/78031885-beb45780-7396-11ea-8231-158c34759100.png">
<img width="1078" alt="Screen Shot 2020-03-31 at 9 30 24 PM" src="https://user-images.githubusercontent.com/61906327/78031978-df7cad00-7396-11ea-88bb-2d7150727cec.png">

**Comment by cyhsieh264** [comment]
`year == 2` 這一行應該是想表達，若居住年資超過十年，都以十年計算？

如果是這樣的話，將 `year == 2` 改成 `year = 2` 試試。

**Comment by yaen1105** [comment]
改了 = 就可以了，感謝助教！
