### ISSUE TITLE
[Week 4] 打字機

### ISSUE THREAD

**Issue by a0981906660** [coding-coworking-club/python-2020-spring#210]
## 提交連結
不太確定是share這個連結：
https://judge.ccclub.io/status/a201dfd690dcb766677c24a45f7e8d2b

還是這個submission ID：a201dfd690dc

不好意思。

## 程式碼

```python
s = input()
outlst = ""

for i in range(0, len(s)):
    if s[i]!="+" and s[i]!="-" and s[i]!="*":
        outlst = outlst+s[i]
        start = i
        break

for j in range(start+1, len(s)):
    if s[j]=="+":
        if len(outlst) != 0:
            outlst = outlst + outlst[-1]
        else:
            outlst = outlst
    elif s[j]=="-":
        outlst = outlst[:-1]
    elif s[j]=="*":
        outlst = outlst*2
    else:
        outlst = outlst+s[j]

print(outlst)
```

## 錯誤訊息

在批改系統上是Runtime Error

## 問題描述

我在自己的jupyter notebook上可以跑，也自己舉了一些比較極端的例子來測試，
例如：`s = 'bbb---r-t---++f'`等，來確保大部分的例外狀況都可以處理到。

不過由於批改系統並不是回傳Wrong Answer，所以我並不曉得真正的bug出現在哪裡。

我的思路是：
先依序讀進input的字串的每個字元，去找到第一個不是"+,-,*"的字元。
然後利用outlst這個空的字串來存最後輸出的結果。

接下來的迴圈簡單來說，就是接續著剛剛找到的非運算元的字元，
然後之後一位一位地繼續判斷，如果遇到運算元就對`outlst`做處理，看是要增加它最末的字元還是拿掉等等。如果都沒有遇到運算元，就直接利用字串相加更新`outlst`

我認為這個程式應該是可以過的，只是不知道哪邊寫得不夠好，或者我有想得不夠周到的地方嗎？還請助教或者講師大大協助了，感恩！

**Comment by jeffery12697** [comment]
假設是這種測資 `+++`， `start ` 這個變數會沒有 assign 就被使用，jupyter notebook看不出來是它做的優化，你可以在前面令一個 `start = 0`

**Comment by a0981906660** [comment]
> 假設是這種測資 `+++`， `start ` 這個變數會沒有 assign 就被使用，jupyter notebook看不出來是它做的優化，你可以在前面令一個 `start = 0`

十分感謝！原來是我遺漏了`start`，謝謝提醒！
這樣說的話，是不是只要要調用的變數都應該assign一個初始值呢？

**Comment by jeffery12697** [comment]
對喔～
