### ISSUE TITLE
[Homework 2] 小明打魯石

### ISSUE THREAD

**Issue by mengguo57** [coding-coworking-club/python-2020-spring#211]
## 提交連結

https://judge.ccclub.io/status/f6aee4055222fc883dfae8f1c55f4bea

## 程式碼

```python
player1=input().split() 
player2=input().split()

while True:
    player1[2]=int(player1[2])-int(player2[1])
    player2[2]=int(player2[2])-int(player1[1])
    if player1[2]<=0 and player2[2]<=0:
        print("tie")
        break
    elif player1[2]>0 and player2[2]<=0:
        print(player1[0], int(player1[1]), player1[2])
        break
    elif player2[2]<=0 and player2[2]>0:
        print(player2[0], int(player2[1]), player2[2])
        break

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/62021733/78042902-430dd700-73a5-11ea-8ae6-29c815047445.png)

## 問題描述

已經試過題目給的兩個sample都有成功，也有考慮到最後的輸出是一個字串加上兩個整數，但想了很久還是不知道bug在哪裡QQQQQ

**Comment by tom192180** [comment]
非助教路人路過XD
你最後一個elif player2[2]<=0 and player2[2]>0:
是否誤植XD? 都是player2

**Comment by mengguo57** [comment]
> 非助教路人路過XD
> 你最後一個elif player2[2]<=0 and player2[2]>0:
> 是否誤植XD? 都是player2

是耶哈哈哈XDD
真的太感謝你了🙏🙏🙏
那助教可以不用理我了XD
