### ISSUE TITLE
[Week 4] 數字三角形

### ISSUE THREAD

**Issue by shaq2000** [coding-coworking-club/python-2020-spring#212]
## 提交連結

https://judge.ccclub.io/status/7bdb172c05dac09e44a05fa881d19050
## 程式碼

```python
n=int(input())
a=[]
for i in range(n):
    a.append(int(i*(i+1)/2))
for i in range(1,int(n*(n+1)/2)+1):
    if i in a:
        print(i%10,end="\n")
    else:
        print(i%10,end="")
```

## 錯誤訊息

Time Limit Exceeded
## 問題描述

我的想法是算出input之後總共有幾個數字，然後把需要換行的數字算出來弄在a這個串列裡面，遇到的時候就換行
不知道是否有更聰明的辦法
麻煩助教了

**Comment by cyhsieh264** [comment]
目前的做法，的確碰到n很大的情況時運算時間會很久，尤其是前面append()的部分。

另一個思路是，利用巢狀迴圈，一層處理行數，另一層處理數字的輸出與遞增。例如可以在跑迴圈之前，新增一個變數並讓它等於 1 ，即 `count = 1`；接著利用迴圈，對變數進行處理，並且使 `count += 1`。
