### ISSUE TITLE
[Week 4] 十人十色

### ISSUE THREAD

**Issue by b04310041** [coding-coworking-club/python-2020-spring#217]
## 提交連結

https://judge.ccclub.io/contest/47/problem/000404
## 程式碼

```python
def ten_color(name_lst, color_lst):
    ans_name = []
    while True:
        color = input()
        if (color in color_lst) == True:
            for j in range(len(color_lst)):
                if color_lst[j] == color:
                    ans_name.append(name_lst[j])
        else:
            break
    return ans_name

    
print(ten_color(name_lst, color_lst))
```

## 錯誤訊息

runtime error
## 問題描述

我不確定hint那邊的說明，我解讀有沒有錯
是names跟colors兩個串列在編譯器上面測試的時候要打在編譯器上，但是在judge不用是嗎?
我在編譯器測試sample的時候是有跑出正確的output的，但是在judge顯示runtime error

**Comment by r05323045** [comment]
@b04310041 
你的解讀是正確的喔！names跟colors兩個串列在judge上不用打出來，另外，題目有說明Output回傳值為一個串列，所以最後也不用print出來，確認回傳值正確就可以了！

最後，請參考 [GitHub Issue](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 教學將內文格式與標題修正喔
