### ISSUE TITLE
[Week 5] 比賽排名

### ISSUE THREAD

**Issue by Isaac-Chu** [coding-coworking-club/python-2020-spring#218]
## 程式碼

```python
Time_lst = [int(num) for num in input().split()]
Time_lst_order=sorted(Time_lst)
for i in Time_lst_order:
    print(Time_lst.index(i), end="")
```

## 錯誤訊息

![python 問問題](https://user-images.githubusercontent.com/62022637/78170112-0b765c00-7485-11ea-801a-70dc49003267.JPG)

## 問題描述

我的想法是將輸入的數字轉為數字並分割後，再將其排序，然後叫出排序後的數字再原本未排序前的index，但操作起來發現同樣值的數字會出錯，不知道為什麼以及如何解決，如截圖所示。

**Comment by Peterorr** [comment]
@Isaac-Chu 
因為取 index 只會取到最小的那個
例如 Time_lst = [65,16,16]
`Time_lst.index(16) = 1`，你想要的 2 就取不到了
建議用 `enumerate` 去處理喔！
