### ISSUE TITLE
[Homework 2] 矩陣變形

### ISSUE THREAD

**Issue by b05303111** [coding-coworking-club/python-2020-spring#225]
## 提交連結

https://judge.ccclub.io/status/5154076fffedc0708727b543acd5b5e6
## 程式碼

a=list(input().split())
b=int(a[0])
c=int(a[1])
number=list()
newa=list(input().split())
newb=int(newa[0])
newc=int(newa[1])
g=-1
for i in range(0,b):
&nbsp; array1=list(input().split())
&nbsp; for x in array1:
         &nbsp; f=int(x)	
         &nbsp; number.append(f)
for j in range(0,newb):
  &nbsp; for k in range(0,newc):
    &nbsp; g+=1
    &nbsp; print(number[g],end=' ')
  &nbsp; print(end='\n')

```

## 錯誤訊息

<!-- 若有錯誤訊息請提供截圖，若無則請留空。 -->
![image](https://user-images.githubusercontent.com/62551229/78316388-1b2f9680-7592-11ea-8222-14e896cd06d9.png)


## 問題描述

<!-- 請盡量完整地敘述你的問題。 -->
Visualizer 跑出來正確,但卻是錯誤答案,不知道哪裡出了問題

**Comment by chun9425** [comment]
輸出的每一行最後不能有空格喔，
拿 sample 1 的 output 來說，
1 2 3 4 5 6
7 8 9 10 11 12
你的程式跑出來 6 和 12 的後面有空格，
但範例的 6 和 12 後面沒有空格。

**Comment by chun9425** [comment]
另外，請參考 [GitHub Issue](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 教學將內文格式修正。
也請不要自創標題格式。
