### ISSUE TITLE
[General] 9-2：字串反轉排序

### ISSUE THREAD

**Issue by b04310041** [coding-coworking-club/python-2020-spring#227]
## 提交連結

https://judge.ccclub.io/problem/180025
## 程式碼

```python
def reverse(s):
    lower = "abcdefghujklmnopqrstuvwxyz"
    upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    for i in range(len(lower)):
        if s[-1] == lower[i]:
            return i
    for j in range(len(upper)):
        if s[-1] == upper[j]:
            return j

s = input()
ans = s.split()
ans = sorted(ans, key = reverse)
print(ans)
```

## 錯誤訊息

runtime error
## 問題描述

我在編譯器有跑出範例的正確output，但在judge上顯示runtime error
想請問是在哪個地方出錯?是不是funtion那邊沒有正確的結束funtion?謝謝

**Comment by jeffery12697** [comment]
用 key = def 排序的原理是程式會把 list 裡的每個元素丟到 def 跑一次，然後用回傳值來排序，如果是數字就比大小，如果是字串他就比字母序。
所以sorted 這個函式要對 list才能使用， 才必須先split 再 sort
