### ISSUE TITLE
[Homework 2] 矩陣變形

### ISSUE THREAD

**Issue by b04310041** [coding-coworking-club/python-2020-spring#229]
## 提交連結

https://judge.ccclub.io/contest/48/problem/001201
## 程式碼

```python
mn = input()
op = input()

s = str()

for i in range(int(mn[0])):
    n = input()
    s = s + " " + n
s = s.split()


op = op.split()


for j in range(int(op[0])):
    ans = []
    for k in range(int(op[1])):
        z = int(op[1]) * j + k
        ans.append(s[z])
    print(" ".join(ans))
```

## 錯誤訊息

runtime error
## 問題描述

在編譯器上跑都有跑出正確的output也沒有其他錯誤訊息，但judge顯示 runtime error，不知道哪邊出問題QQ謝謝助教

**Comment by chun9425** [comment]
請參考 [GitHub Issue](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 教學將內文格式修正。
請不要自創標題格式。
