### ISSUE TITLE
[General] 綜合1-2：一奇多偶

### ISSUE THREAD

**Issue by k07224115** [coding-coworking-club/python-2020-spring#230]
## 提交連結

https://judge.ccclub.io/status/3b026b2b45013b4c777e6aae455ed3f6

## 程式碼

```python
num = [int(i) for i in input().split()]
even = []
for j in num:
    if j in even: 
        continue
    elif num.count(j) % 2 == 1: 
        print(j)
        break
    elif num.count(j) % 2 == 0: 
        even.append(j)

```

## 錯誤訊息

Time Limit Exceeded

## 問題描述

這題我有想盡辦法加快程式的進行，出現過的數字不要再算，找到奇數次的數字後也直接離開迴圈，

但還是TLE，不知道還有哪邊能夠加速~?

**Comment by jeffery12697** [comment]
如果是 `1 1 1 1 1 1 2` 這種測資 你 1 會算很多次， 可以設計算過的數字就不再算的方式

**Comment by k07224115** [comment]
@jeffery3756  我的程式已經有記錄過出現偶數次的數字，然後append到even的list，跑for迴圈時遇到list裡的數字就continue~

**Comment by jeffery12697** [comment]
抱歉我眼殘ＱＱ應該是不要用 count 函式，因為他相當於是把 list 從頭到尾遍歷一次算個數，如果呼叫三次 count 相當於是遍歷三次 list 醬會花很多時間，你可以遍歷 list 一次就把所有數字的出現個數記下來，之後再檢查是不是出現奇數次

**Comment by k07224115** [comment]
Thanks !
