### ISSUE TITLE
[Homework 1] 小明來造句

### ISSUE THREAD

**Issue by jenh326** [coding-coworking-club/python-2020-spring#231]
## 提交連結
https://judge.ccclub.io/status/d708f18d3497375480b89ee790af74bb

## 程式碼

```python
str1 = str.split(input())
str2 = str.split(input())
str3 = str.split(input())
for i in range(len(str1)):
    for j in range(len(str2)):
        for k in range(len(str3)):
            print(str1[i],"\t",str2[j],"\t",str3[k])
```

## 錯誤訊息
Wrong Answer
<img width="360" alt="截圖 2020-04-04 上午12 23 07" src="https://user-images.githubusercontent.com/63113174/78383461-017e6580-760b-11ea-9af9-010fb870b706.png">

## 問題描述
在jupyter跑沒有問題 ，但在作業區出現Wrong Answer
想請問有哪環節錯了嗎><

感謝

**Comment by pin428** [comment]
我不是助教，但是推測是因為你最後一行單字中間會有兩個空格。
把\t 去掉應該就可以。
如果直接打print(str1[i],str2[j],str3[k]) ，輸出的中間就會有空格了

**Comment by jenh326** [comment]
@pin428 喔喔～對齁，有可能><
目前好像還沒辦法更改作業，等之後測試看看
感謝了

**Comment by pin428** [comment]
Problem裡面也有這個題目，可以丟進去試試看

**Comment by jenh326** [comment]
可以了！！！(原來在最後一頁)
謝謝
