### ISSUE TITLE
[General] 字串字典

### ISSUE THREAD

**Issue by pin428** [coding-coworking-club/python-2020-spring#233]
## 提交連結

https://judge.ccclub.io/status/f4adb0ef638a61cc9ad2264da7658f4b

## 程式碼

```
s=[i.lower() for i in input()]
s=sorted(s)
a="abcdefghijklmnopqrstuvwxyz"

for i in s:
    if i in a:
        S.update({i:s.count(i)})
    else:
        continue

for key, value in S.items():
    print(key,value,sep="",end=" ")

```

## 錯誤訊息

Runtime Error
## 問題描述

先將input全部變成list並轉為小寫，，再用sorted排序；
將key設為abc字母，value設為個數，並排除非字母的元素。
自行測試沒發現甚麼特殊問題，收到的錯誤訊息卻是runtime error，
令人不知從何修改起。請助教大人開示，感謝。

**Comment by Peterorr** [comment]
@pin428 第一行 `s = sorted(s)`，請問 s 是什麼呢？
妳得先指派值給 s ，才能做排序喔！

如果妳用 jupyter notebook 測沒問題，
建議妳按 `kernel` -> `Restart & Clean Output` 後再重新測試，
應該會發現 `name 's' is not defined` 這樣的錯誤訊息。

**Comment by pin428** [comment]
抱歉，沒貼好
我的第一行是
s=[i.lower() for i in input()]

我測試的時候第一行有加S.clear()
因為之前測試的東西都會一直壘加上去

**Comment by Peterorr** [comment]
@pin428

**Comment by Peterorr** [comment]
@pin428 可以試一下上面說的步驟嗎？
看起來妳在進入迴圈做字典更新前，並沒有 `S = { }`
應該會產生 `name 'S' is not defined`
所以就 `runtime error` 了

**Comment by pin428** [comment]
感謝，我用上述方法之後就會出現S={ }不存在的問題了。
但是經修正就變成wrong answer
有把輸出最後一個空格消除，但是還是錯誤的，不知道還有甚麼要注意的地方嗎?

s=[i.lower() for i in input()]
s=sorted(s)
a="abcdefghijklmnopqrstuvwxyz"
S={ }
for i in s:
    if i in a:
        S.update({i:s.count(i)})
    else:
        continue
result=""
for key, value in S.items():
    result+=key+str(value)+" "

print(result[:-1])


![image](https://user-images.githubusercontent.com/62340515/78423521-6f716e00-7699-11ea-99a0-4e016423b68a.png)

**Comment by Peterorr** [comment]
@pin428 可以提供提交連結嗎？
圖片或妳給的程式碼沒辦法直接看耶

**Comment by pin428** [comment]
https://judge.ccclub.io/status/483b521ee62fcb88c2cf5648fa6d25e9

連結如附，感謝

**Comment by Peterorr** [comment]
@pin428 
在 Python 3.7 以前，對 dictionary 跑 loop 的時候，
key (or value) 取出來的順序是隨機的，所以你們的解法沒辦法保持字母順序。
而 jupyter 會自行優化這一塊，所以你們看到的會是對的。
