### ISSUE TITLE
[Homework 2] 矩陣變形

### ISSUE THREAD

**Issue by DindinWang** [coding-coworking-club/python-2020-spring#236]
## 提交連結

https://judge.ccclub.io/contest/48/problem/001201
## 程式碼

```python
MN=[i for i in input().split()]
OP=[i for i in input().split()]
lst=[]
for i in range(int(MN[0])):
    i=input().split()
    lst+=i
n=0
m=int(OP[1])-1
for i in range(int(OP[0])):
    for j in range(int(OP[1])):
        if (j+1)/int(OP[1])==0:
            print(lst[m],sep='')
            m=m*2+1
        else:
            print(lst[n],end=' ')
            n+=1
```

        
## 問題描述
 if (j+1)/int(OP[1])==0:
            print(lst[m],sep='')
            m=m*2+1
以上是想處理換行的問題，我的想法是當該行最後一個字元，回傳值跟跳行的動作，
不過還是無法跳行

**Comment by chun9425** [comment]
```python
if (j+1)/int(OP[1])==0:
```
這邊 j+1的值永遠都不會等於零，
所以拿 j+1當被除數所得到的商也永遠不會為零，
因此這邊這個條件判斷不會被滿足。

我猜你想要用的方法是餘數為零，
但符號用錯了，
相除取餘數的符號應該用 % 才對。
