### ISSUE TITLE
[General] 關於 a. split用法

### ISSUE THREAD

**Issue by Jasper1012** [coding-coworking-club/python-2020-spring#24]
## 程式碼

```python
list= input()
list= list. split("u")
print (list1)
```

## 問題描述

我以為split("u"), 是以u來分割我input的string
如果我input的string是 jasper is smart
預想的print應該會是["jasperuisusmart"]
但結果是["jasper is smart"]
我好像理解錯了split的用法
求解釋。

**Comment by hyusterr** [comment]
我以為split("u"), 是以u來分割我input的string
-> 你理解的沒有錯
預想的print應該會是["jasperuisusmart"]
-> " " <- 空白也是一個字串喔~

**Comment by Jasper1012** [comment]
但我print不出來["jasperuisusmart"]呢
下面是我的截圖
<img width="518" alt="螢幕快照 2020-03-15 下午1 17 50" src="https://user-images.githubusercontent.com/61902209/76695872-69522800-66bf-11ea-86d9-262856d4a61d.png">

**Comment by alexypdu** [comment]
Ref: https://www.programiz.com/python-programming/methods/string/split
