### ISSUE TITLE
[Homework 2] 小明打魯石

### ISSUE THREAD

**Issue by johnson2724** [coding-coworking-club/python-2020-spring#240]
## 提交連結

https://judge.ccclub.io/status/5f4630ae47761e7af0cb7a0bf60c6670

## 程式碼

```python
character1 = [ str(i) for i in input().split()]
character2 = [ str(i) for i in input().split()]
attack1 = int(character1[1])
life1 = int(character1[2])
attack2 = int(character2[1])
life2 = int(character2[2])

while life1 and life2 > 0:
    life1 = life1 - attack2
    life2 = life2 - attack1

if life1 > life2 and life1 > 0:
    print(character1[0], attack1, life1)
elif life2 > life1 and life2 > 0:
    print(character2[0], attack2, life2)
else:
    print("tie")
```

## 錯誤訊息

<img width="559" alt="Screen Shot 2020-04-04 at 11 39 38 PM" src="https://user-images.githubusercontent.com/62508116/78454913-a95c6780-76cd-11ea-8af1-6770201c6739.png">

## 問題描述

邏輯是利用while迴圈將一方的生命值減掉對方的攻擊力，直到任一方的生命值<或=0
再藉由比較雙方生命值的高低決定勝利者
在Jupyter上用題目的值跑出來都對，但丟到Judge裡面跑出Wrong Answer
想請問是哪邊沒考慮到還是有什麼問題

**Comment by jeffery12697** [comment]
`while life1 and life2 > 0:` 這行改 `while life1 > 0 and life2 > 0:`
