### ISSUE TITLE
[General] 11-2：字串字典

### ISSUE THREAD

**Issue by mengguo57** [coding-coworking-club/python-2020-spring#241]
## 提交連結

https://judge.ccclub.io/status/9847b5f2134df271823278adf6c0c5d7

## 程式碼

```python
string=sorted(list(input().lower()))
d={}
outcome=[]

for i in string:
    if i.isalpha():
        if str(i) in d.keys():
            d[str(i)]=d[str(i)]+1
        else:
            d.update({str(i):1})
            
for key in d:
    outcome.append(key+str(d[key]))
    
print(" ".join(outcome))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/62021733/78457010-d6167c00-76d9-11ea-92bc-f8fa2621fa69.png)

## 問題描述

我的寫法是先將輸入的字串變成一個按字母順序的 list
再藉由字典的分類去數每個字元的個數
有用批改系統中的兩個sample試過了，都沒有問題
但不知道為何還是出現wrong answer😥

**Comment by jeffery12697** [comment]
#219 我猜問題一樣

**Comment by mengguo57** [comment]
> #219 我猜問題一樣

瞭解了！
剛剛重新調整過code，已成功，謝謝助教！
