### ISSUE TITLE
[General] 3-4：自己回文

### ISSUE THREAD

**Issue by zhao2935** [coding-coworking-club/python-2020-spring#247]
## 提交連結

eda1a4c67bcc
## 程式碼

s=input()
print(s[:]+s[len(s)-1:])
```python

```

## 錯誤訊息
wrong answer

## 問題描述
s是輸入的一行字串，印出從頭到尾+從尾到頭
不明白為何不能這麼做

**Comment by jeffery12697** [comment]
請參考 GitHub Issue 教學將內文格式修正。
