### ISSUE TITLE
[Homework 2] 小明找大腿

### ISSUE THREAD

**Issue by LeeWayne1994** [coding-coworking-club/python-2020-spring#248]
## 提交連結

https://judge.ccclub.io/status/b64c93b7cbbb176c1e16ff6863d1ea3b

## 程式碼

```python
#  小明找大腿

n = int(input())

save = []

for i in range(n):
    s = input().split()
    save.append(s)

def distant(x):
    return int(x[3]) / int(x[1])**2 + int(x[2])**2

a = sorted(save, reverse = True,  key = distant)

def ability(x):
    return int(x[-1])

b = sorted(a, reverse = True, key = ability)

for h in range(len(b)):
    print(b[h][0])

```

## 問題描述

不知道怎麼儲存多重輸入的值，所以開了一個save list，把接下來輸入的一股腦存進去，會變成save list中有input list。

接下來，定義一個distant函式，把save list的內容依照input list中的「戰力／距離x平方 +距離y平方」方式排序，命名為a list。

但當數值相同時，以戰力高的為準，所以再設一個 b list 依照排序過後的a list，再以戰力排序一次，並印出b list 中 input list的第一個內容（名字）。

試了幾次跟sample input好像跑得起來，但系統WA，不太確定問題在哪><

**Comment by cyhsieh264** [comment]
要注意是在 `戰力/距離` 一樣的情況下，才會就 `戰力` 進行比較。你的 list b 純粹是依據 `戰力` 進行排序，可能會將原先的順序打亂。

舉個例子，假設今天有A同學（`戰力/距離=1`，`戰力=13`），以及B同學（`戰力/距離=0.8`，`戰力=20`），照理說結果應該是A排在B前面。但在目前的寫法中，經過第二次排序以後，出來的結果會是B排在A前面。

**Comment by LeeWayne1994** [comment]
```
n = int(input())

save = []

for i in range(n):
    s = input().split()
    save.append(s)

def distant(x):
    return int(x[3]) / int(x[1])**2 + int(x[2])**2

def ability(x):
    return (distant, int(x[3]))

a = sorted(save, reverse = True, key = ability)

for h in range(len(a)):
    print(a[h][0])
```
@cyhsieh264 我後來參照了多重排序的方式，把len(s)替換成distant, s替換成第二個排序條件「戰力」，也就是 (x[3])，但還是WA，求解QQ

![image](https://user-images.githubusercontent.com/61942248/78577330-7dbdb680-7860-11ea-843f-2f63c94cb65d.png)

**Comment by cyhsieh264** [comment]
@LeeWayne1994  

> ```
> n = int(input())
> 
> save = []
> 
> for i in range(n):
>     s = input().split()
>     save.append(s)
> 
> def distant(x):
>     return int(x[3]) / int(x[1])**2 + int(x[2])**2
> 
> def ability(x):
>     return (distant, int(x[3]))
> 
> a = sorted(save, reverse = True, key = ability)
> 
> for h in range(len(a)):
>     print(a[h][0])
> ```

**第一個問題：**
```
def ability(x):
    return (distant, int(x[3]))
```
這裡只寫出了 `distant` 這個函式名稱，但並沒有呼叫使用，應該改成 `distant(x)`。

**第二個問題：**
```
def distant(x):
    return int(x[3]) / int(x[1])**2 + int(x[2])**2
```
`int(x[1])**2 + int(x[2])**2` 前後沒有加括號，運算順序會出錯（一開始我也沒留意到這個XD）。

**Comment by LeeWayne1994** [comment]
@cyhsieh264 啊啊我太粗心了，感謝學姊QQ
