### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by Linchihmin** [coding-coworking-club/python-2020-spring#25]
## 提交連結

https://judge.ccclub.io/status/8e3b7b607572a697f43eed0e14760894

## 程式碼

```python
list1 = ("apple pen")
list2 = ("pineapple pen")
list1 = list1.split(" ")
list2 = list2.split(" ")
list = list1 + list2
s = "pen"
print(s in list)
```

## 問題描述

我用jupyter跑的結果似乎可以檢驗字串s能否在 list1 或 list2 找到，並輸出 True或 False，但提交作業時持都是Wrong，不知可否煩請助教協助說明？謝謝。

**Comment by alexypdu** [comment]
下次發問請注意問題分類及標題！

**Comment by alexypdu** [comment]
你的程式碼沒有讀取輸入 `input()` 的部分。

**Comment by Linchihmin** [comment]
謝謝，下次會注意標題。
