### ISSUE TITLE
[General] 小華的抽籤程式

### ISSUE THREAD

**Issue by k07224115** [coding-coworking-club/python-2020-spring#256]
## 提交連結

https://judge.ccclub.io/status/f79638a1f1e7ca52bcca745e220736a0
## 程式碼

```python
import random as rd
a, b = rd.randint(1, 1000000000), rd.randint(1, 1000000000)
c = rd.randint(1, 10000)
r0 = int(input())
number = int(input())
for i in range(number):
    r0 = ((a * r0) + b) % c
    print(r0)
```

## 錯誤訊息

Runtime Error

## 問題描述

這題不知道錯在哪裡，每次迴圈都有使用新算出來的r0~

**Comment by chun9425** [comment]
你可以跑看看你的程式，
會發現每次跑都會出現不一樣的結果，
這就是為什麼題目要指定 random seed 的原因，
他可以固定每次隨機抽樣的結果，
你可以查查看 random.seed()的用法。

另外這題的輸入只有一個，
random seed 跟抽籤人數兩個用空格分開。

**Comment by k07224115** [comment]
@chun9425 抱歉輸入的地方沒注意到。但是我發現用了random.seed()之後連a, b, c的值都會固定。所以我改成把a, b, c的值放在迴圈裡設定，但還是錯誤，我有試過把random.seed()放在迴圈裡，但是這樣的話值會重複出現四次。不太清楚random.seed()的位置應該放哪邊?
```python
import random as rd
r0, number = [int(i) for i in input().split()]
rd.seed(r0)
for j in range(number):    
    a, b = rd.randint(1, 1000000000), rd.randint(1, 1000000000)
    c = rd.randint(1, 10000)
    print ((a*r0+b)%c)
```

**Comment by chun9425** [comment]
a, b, c 的值是固定的沒錯喔。
按照題意，改變的是 r ，例如：
r1 = (a * r0 + b) % c
r2 = (a * r1 + b) % c
r3 = (a * r2 + b) % c
像這樣依序更新下去。

**Comment by k07224115** [comment]
了解了，非常感謝~
