### ISSUE TITLE
[Week 6] 母音個數排序

### ISSUE THREAD

**Issue by chenyu0217** [coding-coworking-club/python-2020-spring#268]
## 程式碼

```python
words = []
def find_vowel_number(string):
    vowel = "AEIOUaeiou"
    counter = 0
    for i in string:
        if i in vowel:
            counter += 1
    return counter


while True:
    try:
        word = input()
        vowel_number = find_vowel_number(word)
        words.append([word,vowel_number])
    except:
        break
    
    words.sort(key = lambda d:d[1])
    
print("\n".join([i[0] for i in  words])
```

## 問題描述

雖然助教帶討論的時候有講過，但還是沒有弄懂KeyboardInterrupt跟try還有except之間的關聯性，如果說KeyboardInterrupt是屬於except的一種，那應該在按下interrupt之後就經由except跳至break就跳出迴圈，但實際上好像按下Intertupt之後還是會跳出下一個input，再按一次enter就噴error了。
註：最後面的print好像也有點問題

**Comment by r05323045** [comment]
@chenyu0217 

不太確定 `如果說KeyboardInterrupt是屬於except的一種` 想表達的意思，但如果想快速了解exception的分類可以參考 [Exception hierarchy](https://docs.python.org/3/library/exceptions.html#exception-hierarchy)，不過我想你的理解大致沒錯，except會捕捉到所有的exception包含KeyboardInterrupt，所以依照你的code，按下interrupt後會break跳出迴圈。

我實際跑你的code並沒有出現 `按下Intertupt之後還是會跳出下一個input，再按一次enter就噴error了` 的問題，你再跑跑看如果再出現error可以貼在**錯誤訊息**喔～

註：你的print只是少一個右括號而已
