### ISSUE TITLE
[Homework1] 優惠券

### ISSUE THREAD

**Issue by f629** [coding-coworking-club/python-2020-spring#27]
## 提交連結

https://judge.ccclub.io/status/983abafc05302be326c9eface6ea0bb2
## 程式碼

coupon1=input()
coupon2=input()
coupon3=input()
coupon4=input()
coupon5=input()
total=int(input())

if (coupon1[0:2]) == ("$ "):
    coupon1=int(coupon1[2:])
    total=(total-coupon1)
else:
    coupon1=int(coupon1)
    total=round(total*(coupon1/10))
    #print(total)
    
if (coupon2[0:2]) == ("$ "):
    coupon2=int(coupon2[2:])
    total=(total-coupon2)
else:
    coupon2=int(coupon2)
    total=round(total*(coupon2/10))
    #print (total)
    
if (coupon3[0:2]) == ("$ "):
    coupon3=int(coupon3[2:])
    total=(total-coupon3)
    #print(total)
else:
    coupon3=int(coupon3)
    total=round(total*(coupon3/10))
    #print (total) 
    
if (coupon4[0:2]) == ("$ "):
    coupon4=int(coupon4[2:])
    total=(total-coupon4)
    #print(total)
else:
    coupon4=int(coupon4)
    total=round(total*(coupon4/10))
    #print (total)     
    
if (coupon5[0:2]) == ("$ "):
    coupon5=int(coupon5[2:])
    total=(total-coupon5)
    #print(total)
else:
    coupon5=int(coupon5)
    total=round(total*(coupon5/10))
    
if total < 0 :
    total=0

print (total) 

```python

```

## 錯誤訊息

Wrong Answer
Time: 28ms Memory: 8MB Lang: Python3 Author: 3822356@gmail.com

## 問題描述

請問
因為資料輸入5筆有折價及打折二種，應用目前所學的資料分割，如有$ 以減價計算，否則以打折計算，經過5次計算後求得結帳金額。於編輯器可求解。
於judge出現以上錯誤訊息？
請問程式是否另有未完善事項，謝謝。

**Comment by alexypdu** [comment]
@f629  請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將標題及內文格式修正唷！

**Comment by f629** [comment]
![image](https://user-images.githubusercontent.com/34017734/76701399-c79cfc00-66fb-11ea-9df6-d8f391a7560d.png)
謝謝 已更正。
