### ISSUE TITLE
[Homework 3] 小明排工作

### ISSUE THREAD

**Issue by ToboboTobobo** [coding-coworking-club/python-2020-spring#277]
## 提交連結

https://judge.ccclub.io/status/36c3dfee2d1eeac0df195eef8806eca6
## 程式碼

```python
n = int(input())
work_list = []
work_clean = []
cycle = []
for i in range(n):
    work_list.append(input().split())
    if int(work_list[i][1]) > 0:
        cycle.append(int(work_list[i][1]))
        work_clean.append(work_list[i])
        
def lcm(a,b):
    for i in range(1,a+1):
        if a % i ==0 and b % i ==0:
            f = i
    cm = int(a * b / f)
    return cm

if len(cycle) == 1:
    cm = cycle[0]
elif len(cycle) >= 2:
    cm = lcm(cycle[0],cycle[1])
    for i in range(2, len(cycle)):
        cm = lcm(cm, cycle[i])

ans = []
for i in range(1,cm+1):
    ans.append([i])
    for j in work_clean:
        if i % int(j[1]) == 0:
            ans[i-1].append(j[0])
for i in ans:
    if len(i) > 1:
        for j in i:
            print(j, end = " ")
        print()
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/62058972/78984408-b7403b80-7b58-11ea-882b-fffca11f6d68.png)

## 問題描述

解題邏輯：
1. 將使用者輸入的工作名稱、週期放入一個list(work_list)
2. 將週期小於等於0的工作剔除後，放入另一個list(work_clean)，並將純粹只有週期的資料轉成整數放入一個list(cycle)
3. 建立一個函式lcm，其功能為丟入兩個數字，算出兩個數字的最小公倍數
4. 運用點3的函式，算出 list(cycle) 的最小公倍數(cm)
5. 建立一個ans 的list，將1到cm 及該時間為死線的所有工作名稱，以時間為一組分別存在ans 中
6. 最後印出

測資是對的，有考慮到如果使用者輸入測資的週期是小於等於0就會把他剔除，但還是wrong answer，請問原因為何？

**Comment by f629** [comment]
前面問題，有多則相似情形，整體邏輯及程式是OK的。
但輸出的每一行 “行未” “行未” “行未” 
print(j, end = " ")
多一個空格 ，就判定Wrong Answer。
提供參考看看。
