### ISSUE TITLE
[General] 關於sort()的用法

### ISSUE THREAD

**Issue by JOE-CHOU88** [coding-coworking-club/python-2020-spring#28]
## 程式碼

```python
a=[1.2,2.0,-5,18]
a.sort()
sorted_list=sorted(list_a)
print(a)
print(sorted_list)
```

## 錯誤訊息

![關於sort()的用法](https://user-images.githubusercontent.com/62171839/76699026-01620880-66e4-11ea-9e89-ef0280ddc434.png)

## 問題描述

第三行為何錯誤?還是sort()的用法本來不是這樣?

**Comment by alexypdu** [comment]
你的程式碼裡面並沒有 `list_a` 這個變數，所以會出現錯誤：`NameError: name 'list_a' is not defined` 代表該變數沒有定義。

**Comment by JOE-CHOU88** [comment]
那請問怎麼樣才能讓sorted()達到效果?(以下兩種好像都沒有把之前a的串列存起來)
![sorted()1](https://user-images.githubusercontent.com/62171839/76856493-5c376380-688e-11ea-9ac8-a0a0292aa360.png)
![sorted()2](https://user-images.githubusercontent.com/62171839/76856502-60638100-688e-11ea-9ebc-2118674125b7.png)

**Comment by Kevinweisl** [comment]
`sorted` 和 `.sort` 在行為上不太一樣喔。

`.sort` 是 in place 的排序，白話文就是你會直接將給定的串列排序，會直接改動到它自己的順序。（排序前的資訊是會不見得）
`sorted` 則會把你要排序的串列複製一份，然後幫你把複製那份排好。除非你把他 assign 給原本的變數名稱，不然它是不會把原本的串列覆蓋掉的。

可以思考一下，在這邊如果你不想動到原本的串列 a ，該怎麼做呢？
