### ISSUE TITLE
[Homework 2] 小明找大腿

### ISSUE THREAD

**Issue by MeBlu** [coding-coworking-club/python-2020-spring#282]
## 提交連結

https://judge.ccclub.io/status/584df03e4e5074ae62cdcfbabee35424

## 程式碼

```python


k = 0
from operator import itemgetter

n = int(input())
a = [[0] * 4 for i in range(n)]
b = [[0] * 5 for i in range(n)]

while k < n:
  student = [str(i) for i in input().split()]
  a[k] = student[0], student[1], student[2], student[3]
  x = int(student[1])
  y = int(student[2])
  attack = int(student[3])
  decision = attack/(x ** 2 + y ** 2)
  b[k] = student[0], student[1], student[2], student[3], decision
  k += 1

c = sorted(b, key=itemgetter(4,3), reverse=True)
for j in range(n):
    print(c[j][0])

```

## 錯誤訊息

![screenshot](https://user-images.githubusercontent.com/62805273/79063177-a61b3a00-7cd2-11ea-84ab-36d457a3cb10.png)

## 問題描述

到Jupyter或visualize python上跑都沒有問題，能順利作出答案，但在系統上一直是Wrong Answer，不知道是錯在哪裡?

**Comment by alexypdu** [comment]
請參考 [GitHub Issue](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 教學將內文格式修正。

**Comment by MeBlu** [comment]
@alexypdu  已修正喔 再麻煩了!
