### ISSUE TITLE
[General] 字母接龍

### ISSUE THREAD

**Issue by yaen1105** [coding-coworking-club/python-2020-spring#289]
## 提交連結
https://judge.ccclub.io/status/4993d993ef2e36db163c84bb42538d2f

## 程式碼

```python
d={}
start=''
while True:
    _input = input()
    if len(_input) == 1:
        start=_input
        break
    else:    
        d[_input[0]]=_input[2]

#print(d)
#print(start)

ans=[]
ans.append(start)
i = start
while True: 
    ans.append(d[i])
    ans.append(d[ans[-1]])
    i = ans[-1]
    if d[ans[-1]]==start:
        break
print(' '.join(ans))
```

## 錯誤訊息
Time Limit Exceeded

## 問題描述

在visualize python有跑出來
但jupyter和judge都錯
感覺應該是while loop沒有break到對的點
但不知道應該怎麼改
請助教幫忙提點
超級感謝！
<img width="875" alt="Screen Shot 2020-04-13 at 6 35 52 PM" src="https://user-images.githubusercontent.com/61906327/79114678-76ddf900-7db6-11ea-830c-fedb6e73926f.png">

**Comment by yaen1105** [comment]
剛試著再改一下while loop的寫法，
結果jupyter可以了，但judge還是Time Limit Exceeded
請助教幫忙瞧瞧，謝謝
https://judge.ccclub.io/status/896819c4d9ad6ef9b50d37eaae2c95b0
<img width="399" alt="Screen Shot 2020-04-13 at 8 54 55 PM" src="https://user-images.githubusercontent.com/61906327/79121988-33d95100-7dc9-11ea-9f78-2a548750e131.png">

**Comment by yaen1105** [comment]
@alexypdu 這個也是還沒回答就被關了，麻煩您感謝！

**Comment by yaen1105** [comment]
@alexypdu 這個沒有人回我 嗚嗚 麻煩了，謝謝！

**Comment by yaen1105** [comment]
請問這個有助教可以幫我回一下嗎？困在這很久了，謝謝！ @alexypdu

**Comment by alexypdu** [comment]
第一個 while loop 有點多餘，既然已經知道會有 20 行輸入，可以用 for loop 就好！
