### ISSUE TITLE
[General] 迴圈--while 1的定義問題

### ISSUE THREAD

**Issue by JOE-CHOU88** [coding-coworking-club/python-2020-spring#29]
## 程式碼

```python
sequences = [0, 1, 2, 3, 4, 5]
i = 0
while 1: 
    print(sequences[i], end = " ")
    i = i + 1
    if i == len(sequences):
        print("No elements left.")
        break

```

## 問題描述

while 1(條件判斷為1)為何能保證迴圈永遠成立?
還是他原本定義就是這樣?
while 2, while 3, while 4是不是也能達成相同效果?

**Comment by alexypdu** [comment]
```python
while (condition)
```

會將 `while` 後面的 value 轉成 boolean 來判斷是否進入 `while` 內部的程式碼。
在 Python 裡面，以下 value 會被判斷為 `False`：

- constants defined to be false: `None` and `False`.
- zero of any numeric type: `0`, `0.0`, `0j`, `Decimal(0)`, `Fraction(0, 1)`
- empty sequences and collections: `''`, `()`, `[]`, `{}`, `set()`, `range(0)`

其餘基本上都是判斷為 `True`。以你的問題來說，`while 2`、`while 3`、`while 4` 都是一樣的效果。

**Comment by JOE-CHOU88** [comment]
所以是只要while後面接的是>1的整數轉換成布林值後都可以進入while程式碼嗎?

**Comment by alexypdu** [comment]
> 所以是只要while後面接的是>1的整數轉換成布林值後都可以進入while程式碼嗎?

是的。
