### ISSUE TITLE
[Homework 3] OO下載器

### ISSUE THREAD

**Issue by LeeWayne1994** [coding-coworking-club/python-2020-spring#294]
## 提交連結

https://judge.ccclub.io/status/d78370188823f491412a0a435553b200
## 程式碼

```python
# OO下載器

n = int(input())   
info = [i for i in input().split()]
dic = {}
i = 0
while i < len(info):
    dic.update({info[i]:int(info[i+1])})   # {'西遊記': 35, '紅樓夢': 50, '哈利波特': 21, '暮光之城': 43}
    i += 2
    
m = int(input())
dic_type = {}

for i in range(m):
    c = input().split()
    total = 0
    for x in range(len(c)):
        if c[x] in dic:
            total += int(dic[c[x]])
    dic_type.update({c[0]:int(total)})    #{'奇幻': 56, '西洋': 64, '小說大全': 149}

k = int(input())
lst = []
for i in range(k):
    j = input().split()
    if j[0] in dic_type:
        lst.append(int(dic_type[j[0]])//int(j[1]))

for i in lst:
    print(i)
```

## 問題描述

測資跑得出來，但系統WA，不太清楚為什麼...跟 #284 一樣

**Comment by cyhsieh264** [comment]
看起來問題可能出在這：
```
    for x in range(len(c)):
        if c[x] in dic:
            total += int(dic[c[x]])
```
若剛好有 `組合名` 跟 `資源名` 一樣的情況（題意當中並沒有排除這種可能），算出來 `total` 就會有誤。

建議在上面range的部分做調整。

**Comment by LeeWayne1994** [comment]
@cyhsieh264 我考慮了組合名與資源名一樣的情況重寫一次，這次用visualize python跑一次看過，在組合包名與資源名相同的情況下，不會將組合包計入total，但還是WA...

https://judge.ccclub.io/status/4535d26f4692708e666023d4e5175342

```
n = int(input())
sourse = input().split() # [西遊記, 35, 紅樓夢, 50, 哈利波特, 21, 暮光之城, 43]
sourse_dic = {}
b = 0
while b < n*2 :
    sourse_dic.update({sourse[b]:sourse[b+1]})
    b += 2

m = int(input())
dic = {}
for i in range(m):
    x = input().split() # [奇幻 西遊記 哈利波特], [紅樓夢 紅樓夢 哈利波特 暮光之城 西遊記]
    total = 0
    for j in x:
        if j is not x[0] and j in sourse_dic:
            total += int(sourse_dic[j])
    dic.update({x[0]:total})

k = int(input())
lst = []
for v in range(k):
    c = input().split()
    if c[0] in dic:
        lst.append(int(dic[c[0]])//int(c[1]))

for i in lst:
    print(i)
```

**Comment by cyhsieh264** [comment]
一樣是 `組合名` 與 `資源名` 可能重複的問題，在你的第一個寫法中，加出來的total會比預期的多；但在第二個寫法中，由於完全排除了 `組合名` 與 `資源名` 重複的情況，因此加出來的total會比預期的少。

舉個例子：
---
我們有資源名及資源大小（假設value在存入時，已轉為int型態）如下：
```
source_dic = {"西遊記": 1, "紅樓夢": 2, "哈利波特": 3, "暮光之城": 4} 
```
組合包名及其內容（假設已將input處理為list）如下：
```
lst = ["紅樓夢", "紅樓夢", "哈利波特", "暮光之城", "西遊記"]  # 第一個 "紅樓夢" 為組合包名
```

（接下來計算「紅樓夢」這個組合包的資源大小）

在你的第一個寫法中：
```
total = 12  # 2+2+3+4+1
```
在你的第二個寫法中：
```
total = 8  # 3+4+1
```
但根據題意，我們要的結果應該是：
```
total = 10  # 2+3+4+1
```
---

實際上在你的第一個寫法中，只要改變range的取值範圍即可，也就是從 x = 1 開始，即 (1, len(c))。

**Comment by LeeWayne1994** [comment]
@cyhsieh264 可是我跑過，就算組合包名與資源名重複，他也不會算到組合包名或省略資源名

![image](https://user-images.githubusercontent.com/61942248/79995299-a8a73c00-84e9-11ea-938e-37ac631cbd65.png)

**Comment by cyhsieh264** [comment]
喔喔，我大概知道問題在哪了！

如果是這樣寫：
```
source_dic = {"西遊記": 1, "紅樓夢": 2, "哈利波特": 3, "暮光之城": 4} 

# 以  紅樓夢 紅樓夢 哈利波特 暮光之城 西遊記  進行測試
```
跑起來沒有問題。但如果變成：
```
source_dic = {"a": 1, "b": 2, "c": 3, "d": 4} 

# 以  b b c d a  進行測試
```
會發現計算結果有誤，這也是為什麼仍然WA的原因。

---
關鍵在於，你寫的是 `if j is not x[0]`，而非 `if j != x[0]` 。如果在你的寫法中，將 `is not` 換成 `!=` ，應該會發現算出來的結果不一樣了。

實際上在Python當中，`==` 和 `is` 的意義是不同的，`==` 是用來判斷兩個物件的值是否相等，`is` 則是用來判斷兩個物件在記憶體當中所佔的位置是否相同（可以用 id(object) 來查物件所分配到的記憶體位置，例如在你的 for loop 中比對 `id(j)` 和 `id(x[0])`，將結果輸出看一下）。至於為什麼上面的結果會有差異，應該是涉及到比較深層的資料存放及編碼問題，有興趣可以自己再查查。

因此，如果是要判斷兩個物件的值是否相等，建議使用 `==` 和 `!=` ，而非 `is` 和 `is not` ，用途上有些不同。再回到這題來看，會建議就原先的寫法對range進行修改，應該會快一些。

**Comment by LeeWayne1994** [comment]
@cyhsieh264 瞭解，感謝助教～
