### ISSUE TITLE
[Homework 3] 小明上菜啦

### ISSUE THREAD

**Issue by yaen1105** [coding-coworking-club/python-2020-spring#296]
## 提交連結
https://judge.ccclub.io/status/d19633f440f2fe3213d24bc953fbca9b

## 程式碼

```python
_inv = int(input())
inv_lst = input().split()
inv_d={}
for i in range(_inv*2):
    if i%2==0:
        inv_d[inv_lst[i]]= int(inv_lst[i+1]) #建立一個食材庫存量的dic 叫inv_d[種類]=[數量]

_menu = int(input())
_=1
allrecipe_d={}
while _<=_menu:
    name, *recipe=input().split()
    for i in range(len(recipe)):
        if i%2==0:
            allrecipe_d.setdefault(name,{})[recipe[i]]=recipe[i+1]  #建立數個食譜合併的dic中有dic 叫allrecipe_d[菜名name]={recipe食材:數量,食材:數量,...}
    _+=1
    
_order = int(input())
_=1
order_lst=[]
mid={}
cal={}
while _<=_order:
    order=input()
    if order in allrecipe_d.keys():
        mid[order]=allrecipe_d[order]
        for value in mid.values():
            cal=value
            #print(mid)
            #print(cal)           
        if cal.keys() == invent_d.keys():
            for key in cal:
                if invent_d.get(key):
                    ans[key] = int(invent_d[key])-int(cal[key])
                    invent_d.update(ans)
                else:
                    ans[key] = int(invent_d[key])
                    invent_d.update(ans)
            if int(ans[key])<0:
                print ('False')
            else:
                print('True')
        else:
            print ('False')
    _+=1
```

## 錯誤訊息

Runtime Error

## 問題描述

jupyter測試是對的，
但runtime error
不太確定是漏掉什麼
<img width="665" alt="Screen Shot 2020-04-15 at 9 03 09 PM" src="https://user-images.githubusercontent.com/61906327/79340698-497f7f80-7f5d-11ea-9d40-f75257725584.png">

**Comment by yaen1105** [comment]
再測了發現若連續點了同樣的菜名，
第二的菜名的食材數量答案是根據沒有扣掉之前的數量？
不曉得該從哪邊著手改？感覺是invent.update那邊有問題？
請助教幫忙提點，謝謝！
<img width="393" alt="Screen Shot 2020-04-15 at 9 10 50 PM" src="https://user-images.githubusercontent.com/61906327/79341110-dc201e80-7f5d-11ea-86c9-b6851ea4847c.png">

**Comment by jeffery12697** [comment]
`invent_d` `inv_d` 感覺你下面有些地方寫錯變數值，或是你`invent_d`沒有初始的assign值

**Comment by yaen1105** [comment]
感謝 @jeffery3756 
重新檢視過後，修改了成這樣：https://judge.ccclub.io/status/6e935a7505a25092efe17dc6699f3266
結果噴了WrongAnswer
雖然jupyter測試是對的...不曉得又漏掉什麼了，請再幫我看看，大感謝！
<img width="572" alt="Screen Shot 2020-04-17 at 10 52 28 PM" src="https://user-images.githubusercontent.com/61906327/79582621-977fb900-80fe-11ea-82f3-3718a74cfc28.png">

**Comment by yaen1105** [comment]
@alexypdu @jeffery3756 還沒回答就被關了... 再麻煩了謝謝

**Comment by jeffery12697** [comment]
不要用 for 跑字典順序會亂掉，用` if 食材 in 食譜字典:` 就可以檢查有無該食材，不用拿出字典的東西在看有沒有一樣
設 ans 字典有點多餘，你直接相減食材後，去指向invent_d[key]，就可以做到更新現有的存貨量了
