### ISSUE TITLE
[Homework 3] OO下載器

### ISSUE THREAD

**Issue by secretrw** [coding-coworking-club/python-2020-spring#298]
## 提交連結

https://judge.ccclub.io/status/bc550a7b300fe4254a1842fe61de3f46
## 程式碼

```python
d={}
n=int(input())
lst=[i for i in input().split()]
for i in range(0,2*n,2):
    d[lst[i]]=int(lst[i+1])
lst1=[]
m=int(input())
for i in range(m):
    lst1.append([j for j in input().split()])
l=int(input())
lst2=[]
for i in range(l):
    lst2.append([j for j in input().split()])
for i in lst2:
    for j in lst1:
        o=0
        if i[0]==j[0]:
            for l in range(1,len(j)):
                o+=d[j[l]]
            o=o//int(i[1])
            print(o)
            break
```

## 問題描述
wrong answer，用jupyter跑可以，也試過其他組合都沒問題

**Comment by cyhsieh264** [comment]
@secretrw 感謝提問，目前題目敘述已作補充。由於可能會有組合名重複的情況，若用目前的寫法，在最後跑for loop時，抓到的組合包資訊可能會有誤，建議用dictionary來對組合包進行存取。

**Comment by cyhsieh264** [comment]
@secretrw 

補充：在Python當中，split() 這個用法本身回傳的就是一個list了，因此不須寫成 `lst = [i for i in input().split()]` （這樣寫相當於多做一次功，效能較差），直接寫 `lst = input().split()` 即可。
