### ISSUE TITLE
[General] Jupyter notebook 疑似運算異常

### ISSUE THREAD

**Issue by LeeWayne1994** [coding-coworking-club/python-2020-spring#3]
## 程式碼

```python

```

## 錯誤訊息

![12](https://user-images.githubusercontent.com/61942248/76167138-8a86b600-619f-11ea-930a-84ba1dd2d4da.PNG)

![擷取](https://user-images.githubusercontent.com/61942248/76167086-0fbd9b00-619f-11ea-81e1-0a6f3ecbf3ee.PNG)

## 問題描述

原本照著medium文章練習，在Jupyter notebook上都很順利可以算出來，但過一段時間再輸入之後，同一段程式碼卻顯示value error等問題，重新開啟Jupyter notebook也無法解決...請問可以怎麼處理？

**Comment by alexypdu** [comment]
你是不是有在notebook 某處將內建的 `print` function 改成 `float` 相關的函式呢？

**Comment by Kevinweisl** [comment]
錯誤產生的方式上面助教已經回答了
建議解決方式：Jupyter notebook 上方 `Kernel` => `Restart & clear output`
然後重新執行你的程式，應該就會正常了

**Comment by LeeWayne1994** [comment]
謝謝兩位，經過Restart & clear output已經修復成功
@alexypdu 我也不太清楚是怎麼調到的，我好像除了在他的空白處coding以外，沒有調動其他東西
