### ISSUE TITLE
[General] input函數問題

### ISSUE THREAD

**Issue by chris0416** [coding-coworking-club/python-2020-spring#30]
## 程式碼

```python
s1 = input()
s2 = input()
print(s1 + s2)
```

## 問題描述

我的input函數出來的數並非預設的字串，而是變成實數
比如說輸入5和2，出來的並非是52而是7。

**Comment by alexypdu** [comment]
我無法重現你說的問題。如果你是使用 Jupyter Notebook 的話可以試試看點選上方功能表：`Kernel` => `Restart and Clear Output` 再試試看。

**Comment by chris0416** [comment]
我是使用Sublime Text輸入程式，儲存後在終端機執行
結果就出現這種狀況

**Comment by alexypdu** [comment]
我相信你如果用 Jupyter Notebook 或是 [線上編輯器](https://repl.it/languages/python3) 應該是沒辦法重現這個問題的。
