### ISSUE TITLE
[Homework 3] 神奇翻譯機

### ISSUE THREAD

**Issue by TZU-LING** [coding-coworking-club/python-2020-spring#301]
## 程式碼

```python
dic_num = int(input())
dic = {}
for i in range(dic_num):
    key, value = input().split(" ")
    dic.update({key : value})
#print(dic)
lookup = input().split()
for key in range(len(lookup)):
    print(dic[key], end = " ")
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/36917812/79529090-5fe12480-809e-11ea-9c44-82a3db3fc817.png)

## 問題描述

上網查看到噴KeyError: 0代表key值不存在字典裡，但我前面print過dic確定要搜尋的key值有在字典裡，不懂為什麼還會噴error呢~? 謝謝!

**Comment by Neptune2901** [comment]
```Python
for key in range(len(lookup)):
    print(dic[key], end = " ")
```
這個會依次帶入key = 0, 1, 2, ..., len(lookup) - 1
而不是你要的key值唷
