### ISSUE TITLE
[General] 天數相差

### ISSUE THREAD

**Issue by TZU-LING** [coding-coworking-club/python-2020-spring#304]
## 程式碼

```python
from datetime import time
date_begin = datetime.strptime(input(), "%Y %m %d")
date_end = datetime.strptime(input(), "%Y %m %d")
date_diff = abs(date_end - date_begin)
print(date_diff.days)
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/36917812/79625528-4a323480-815c-11ea-85c8-a760f386b1f1.png)

![image](https://user-images.githubusercontent.com/36917812/79625547-59b17d80-815c-11ea-9d4e-63a26ebbcfeb.png)

## 問題描述

在jupyter上執行正常，但在judge上runtime error，到visualization上發現也有錯，但不太懂它說strptime not found or not supported的意思，以及應該如何改善~?

**Comment by hyusterr** [comment]
https://docs.python.org/3/library/datetime.html#datetime-objects
看了一下文件，要引用該方法應該是要呼叫 `datetime.datetime.strptime` ㄛ
同時 記得先 `import datetime`

**Comment by TZU-LING** [comment]
![image](https://user-images.githubusercontent.com/36917812/79758741-58e13d00-8350-11ea-8db4-be012f05526a.png)
呼叫datetime.datetime.strptime後，似乎跑出了另一個新問題: type object 'datetime.datetime' has no attribute 'datetime'~是哪邊又出錯了嗎XD?

在jupyter系統上跑的連結如下: 
https://judge.ccclub.io/problem/181301

**Comment by Neptune2901** [comment]
![image](https://user-images.githubusercontent.com/61959224/80178197-3ab95c80-8630-11ea-821c-0708ca708ce2.png)

是不是3.8以前不能用XD
