### ISSUE TITLE
[General] 11-2：字串字典

### ISSUE THREAD

**Issue by shaq2000** [coding-coworking-club/python-2020-spring#317]
## 提交連結

https://judge.ccclub.io/status/aa4a97415099ef698cd53662fa8eedb8
## 程式碼

```python
s=input()
a_dict={}
a=[]
for i in range(97,123):
    a_dict.update({chr(i):0})
for i in s.lower():
    if i not in a_dict:
        continue
    a_dict[i]+=1
for i in a_dict:
    if a_dict[i]!=0:
        a.append(i+str(a_dict[i]))
a=' '.join(a)
print(a)
```

## 錯誤訊息

Wrong Answer
## 問題描述

想法如下
1.輸入字串s，建一個空字典和空字串
2.讓字典裏面有a-z 對應到值是0
3.讓輸入字串s轉小寫，出現一次讓字典對應值+1
4.輸出字典對應值不為0的數
5.讓輸出最後一格不是空白

試了幾組test都沒問題QQQ，麻煩助教解惑

**Comment by chun9425** [comment]
dict 裡的資料是沒有順序的，
```python
for i in a_dict:
    if a_dict[i]!=0:
        a.append(i+str(a_dict[i]))
```
以上面這段程式來看，
不會依照字母的順序將資料加到 a 裡面，
因此需要再對 a 進行排序。

**Comment by shaq2000** [comment]
了解，通過了，太感謝


chun9425 <notifications@github.com>於 2020年4月24日 週五，上午10:22寫道：
