### ISSUE TITLE
[Homework 1] 數字數

### ISSUE THREAD

**Issue by purcreation0802** [coding-coworking-club/python-2020-spring#32]
## 提交連結

https://judge.ccclub.io/contest/40/problem/041103
## 程式碼

```python
sentence = input("")
list_sentence = sentence.split(" ")
volcabulary = len(list_sentence)
print(volcabulary)

str_sentence = "".join(list_sentence)
str_sentence = str_sentence.lower()
letter = "abcdefghijklmnopqrstuvwxyz"
num = 0

for i in str_sentence :
    if i in letter :
        num += 1
print(num)
```

## 錯誤訊息

僅在 judge 系統顯示 wrong answer
## 問題描述

思路：
1. 將 input 的 str 包裝成 list，利用 len(list) 來判斷「單字個數」
2. 使用 .join 將 list 轉換回 str 後，將 str 中的字母都轉成小寫，初始字母個數 (num) 設為0
3. 用 for 迴圈，將 str_sentence 中的字母和 letter 中 a-z 進行比對
4. 若 str_sentence 的 i 在 letter 中也有出現，就讓 num += 1，以此計算「字母個數」

問題：
若 input 是 ( Hello, world! ) ，output 就沒問題；但若 input 是 ( "空格" Hello, world! )，輸出的單字個數就會多一個，也就是電腦亦將空格視為一個單字，請問該怎麼修正呢？感謝

**Comment by alexypdu** [comment]
請將第二行的

```python
list_sentence = sentence.split(" ")
```

換成

```python
list_sentence = sentence.split()
```

`str.split()` 沒有給任何參數的時候，會將所有的空白字元（包含：空白鍵、Tab、換行符號等等）排除，字串頭尾如果有空白字元也會清乾淨：

```python
a = '   This \t is a \n pen \t\n'
print(a.split())  # ['This', 'is', 'a', 'pen']
```

如果給定 delimiter，例如空白鍵，則結果為：

```python
a = '   This \t is a \n pen \t\n'
print(a.split(' '))  # ['', '', '', 'This', '\t', 'is', 'a', '\n', 'pen', '\t\n']
```

**Comment by purcreation0802** [comment]
> 請將第二行的
> 
> ```python
> list_sentence = sentence.split(" ")
> ```
> 
> 換成
> 
> ```python
> list_sentence = sentence.split()
> ```
> 
> `str.split()` 沒有給任何參數的時候，會將所有的空白字元（包含：空白鍵、Tab、換行符號等等）排除，字串頭尾如果有空白字元也會清乾淨：
> 
> ```python
> a = '   This \t is a \n pen \t\n'
> print(a.split())  # ['This', 'is', 'a', 'pen']
> ```
> 
> 如果給定 delimiter，例如空白鍵，則結果為：
> 
> ```python
> a = '   This \t is a \n pen \t\n'
> print(a.split(' '))  # ['', '', '', 'This', '\t', 'is', 'a', '\n', 'pen', '\t\n']
> ```

原來是這樣～
一直誤會 split 後方一定要放分割條件，謝謝詳細回覆！

**Comment by librairde** [comment]
想請問為什麼一定要換成小寫？但是這樣key大寫字母也能算進去是為什麼？謝謝

**Comment by purcreation0802** [comment]
> 想請問為什麼一定要換成小寫？但是這樣key大寫字母也能算進去是為什麼？謝謝

其實只是我懶得在 letter 裡面再多打 26 個大寫的英文字母～
題目敘述是：判斷文章由幾個字母所組成
所以先全數轉成小寫，不會影響字母個數的計算
（轉成大寫也可以，只是指定給  letter 的物件就要換成 26 個大寫英文字母）
