### ISSUE TITLE
[General] 9-1：數字總和排序

### ISSUE THREAD

**Issue by yhyehg** [coding-coworking-club/python-2020-spring#323]
## 提交連結
https://judge.ccclub.io/status/d175a9b453dfb2d0575c5d4f5a025a70

## 程式碼

```python
S = []
result = []
def count_sum(N):
    for k in N:
        m = 0
        while k > 0:
            m+=(k%10)
            k//=10
        S.append(m)
    result = [n for _,n in sorted(zip(S,N))]
    return result

t = [int(i) for i in input().split()]
print(count_sum(t))
```

## 錯誤訊息

[截圖 2020-04-23 下午11 05 27](https://user-images.githubusercontent.com/62054960/80115127-f047c980-85b6-11ea-930a-c32dee918aa5.png)

## 問題描述

不確定要怎麼讓各個位數總和一樣的數字以正確方式排列

**Comment by Kevinweisl** [comment]
請依照 [GitHub Issue 使用教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將標題和內容格式更正。
