### ISSUE TITLE
[Homework 3] 神奇翻譯機

### ISSUE THREAD

**Issue by scourgerwill** [coding-coworking-club/python-2020-spring#330]
## 提交連結
https://judge.ccclub.io/status/fa3af8fde12450945d67d7bb5c7679ed

## 程式碼

```python
n = input()
x = 1
a = []
while x < n+1:
    x+=1
    a.append(str.split(input()))
b = str.split(input())
output=[]
for i in b:
    for j in range(0,n):
        if i == a[j][0]:
            output.append(a[j][1])
        else:
            pass
output = ' '.join(output)
print(output)
```

## 錯誤訊息
Wrong Ans

## 問題描述
jupyter 能跑出來，judge顯示錯誤，請問哪裡寫錯了。。

**Comment by fangha1216** [comment]
從你貼的連結看起來錯誤是Runtime Error
Runtime Error表示程式跑的過程中有出錯
n = input()預設會是字串形式
所以你在x<n+1這邊jupyter應該也會噴錯誤
然後split的語法是
‘你要用符號分隔的字串’.split('括弧裡面放你要用來分隔的符號')
例如：
a = 'a b c'
a_lst = a.split(' ')
a就會被分成['a','b','c']
另外建議你這題用字典會比較好處理
key是翻譯前的字 value是翻譯後的字
然後就可以用翻譯前的字直接查到翻譯後的字 不用一個一個比對
字典可以參考：
[Python 初學第九講 — 字典](https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-533b8d8d96f3)

**Comment by scourgerwill** [comment]
啊，我之前有放int()不過後來想說試下拿掉的，結果上傳錯代碼了。不過上面的代碼n我加了int()它會顯示Wrong Ans... 沒關係，我用“字典”解決了，謝謝！
