### ISSUE TITLE
[Homework 3] 小明排工作

### ISSUE THREAD

**Issue by Gracilis5** [coding-coworking-club/python-2020-spring#332]
## 提交連結

https://judge.ccclub.io/status/395f0c21edff12fce2bb346f952041a9

## 程式碼

```python
n = int(input())
d = {}
for i in range(n):
    work = input().split()
    d[work[0]] = work[1]
# d = {'A': '2', 'B': '6'}

work_name = [i for i in d.keys()]
work_DL = [int(i) for i in d.values()]
days_max = max(work_DL)

l = []    #存放所有DL時間的list
for i in work_DL:    #i='2'
    d = i
    while i <= days_max:
        if i not in l:
            l.append(i)
        i = i + d
# l = [2 ,4, 6]
        
d2 = {}
for i in l:    #i=2
    for j in work_DL:    #j=2
        if i%int(j) == 0 and i not in d2:
            d2[i] = work_name[work_DL.index(j)]
        elif i%int(j) == 0 and i in d2:
            d2[i] = d2[i] + ' ' + work_name[work_DL.index(j)]
# d2 = {2:'A', 4:'A', 6:'A B'}

arranged_lst = sorted(d2.items())
# arranged_lst = {2:'A', 4:'A', 6:'A B'} 整理好的
for i in arranged_lst:    #i=('2', 'A')
    print (i[0], i[1])
```

## 問題描述

先做出所有DL時間的list，名為「l」，存放進所有DL後，使用名為「d2」的dictionary篩選各項工作在各DL是否整除，整除的話代表該工作那該DL要做，放進「d2」，最後會得到所有答案，sorted之後印出。測資和jupyter都跑出正確答案，不知為什麼是WA，麻煩解惑，謝謝～

**Comment by Peterorr** [comment]
@Gracilis5 重新檢視一次題目所敘述的

> 在t = 6時，因為到達兩個工作的大週期(所有週期的最小公倍數)，
> 後續的排程會跟前面完全一樣，所以排程結束。

似乎被 `days_max = max(work_DL)` 這行限制住了，請重新釐清一次題目所謂的 `大週期` 哦！

**Comment by Gracilis5** [comment]
> @Gracilis5 重新檢視一次題目所敘述的
> 
> > 在t = 6時，因為到達兩個工作的大週期(所有週期的最小公倍數)，
> > 後續的排程會跟前面完全一樣，所以排程結束。
> 
> 似乎被 `days_max = max(work_DL)` 這行限制住了，請重新釐清一次題目所謂的 `大週期` 哦！

了解助教的意思，我之前沒有用最小公倍數來算，新的code寫法為先找出最小公倍數days_max（有考慮到兩個以上數字要找最小公倍數的問題，因此中間有用while loop處理），其餘寫法維持不變，不知道為何還是WA，煩請解惑！

https://judge.ccclub.io/status/2d49e590a85a580177825c9e7376437f
