### ISSUE TITLE
[Week 6] 數字交換最大值

### ISSUE THREAD

**Issue by Gracilis5** [coding-coworking-club/python-2020-spring#334]
## 提交連結

https://judge.ccclub.io/status/4b123b1b9d98b3cd7586a4521eb77631

## 程式碼

```python
s = input ()
l = [ s[i] for i in range(len(s)) ]
max_ans = [int(s)]

for i in range(len(l)): 
    for j in range(len(l)):
        l2 = l[:]    #複製的list，方便操作
        l2[i] = l[j]
        l2[j] = l[i]
        ans = ''.join(l2)
        if int(ans) > max_ans[0]:
            max_ans.remove(max_ans[0])
            max_ans.append(int(ans))
print (max_ans[0])
```

## 問題描述

數字一個一個交換、不斷跟最大的答案比較，最後得到交換後的最大值。測資和jupyter都跑出正確答案，丟到judge跑出time limit exceeded，想知道哪裡需要修正，謝謝～

**Comment by r05323045** [comment]
@Gracilis5 

你目前的做法是窮舉所有交換的結果，Sample input位數比較少還不會超時，但在實際測資會有位數很多的，所以你要想一套邏輯讓它不用窮舉全部結果來比較(就是在雙層迴圈中設置條件讓它break，或避免用雙層迴圈)

一些可能的思考方向：
1. 因為只交換一次，所以盡量讓越大的位數拿到最大的數字
2. 在找最大的數字交換時，盡量找越後面的位數交換

以1929為例：
1. 盡量讓千位數的1交換到9
2. 有兩個9，但拿個位數的9交換會讓交換結果最大

=> 9921


你可以從這個方向下手，實作有問題或其他解法再提出討論～

**Comment by Gracilis5** [comment]
> @Gracilis5
> 
> 你目前的做法是窮舉所有交換的結果，Sample input位數比較少還不會超時，但在實際測資會有位數很多的，所以你要想一套邏輯讓它不用窮舉全部結果來比較(就是在雙層迴圈中設置條件讓它break，或避免用雙層迴圈)
> 
> 一些可能的思考方向：
> 
> 1. 因為只交換一次，所以盡量讓越大的位數拿到最大的數字
> 2. 在找最大的數字交換時，盡量找越後面的位數交換
> 
> 以1929為例：
> 
> 1. 盡量讓千位數的1交換到9
> 2. 有兩個9，但拿個位數的9交換會讓交換結果最大
> 
> => 9921
> 
> 你可以從這個方向下手，實作有問題或其他解法再提出討論～

已更改成單層迴圈，也嘗試先找到最後面index的最大值，一一跟最大值交換並比較，我有用visualize看過覺得滿符合題意的，測資也都是正確答案，不知道現在為何反而變成WA，再麻煩助教解惑，謝謝！

```python
s = input ()
l = [ s[i] for i in range(len(s)) ]
max_ans = [int(s)]
max_number = max(l)
l2 = l[::-1]    #複製的相反list
index_number_reverse = l2.index(max_number)
index_number = len(l) - index_number_reverse - 1

for i in range(len(l)): 
    l3 = l[:]    #複製跟l一樣的list，方便操作
    l3[i] = max_number
    l3[index_number] = l[i]
    ans = ''.join(l3)
    if int(ans) > max_ans[0]:
        max_ans.remove(max_ans[0])
        max_ans.append(int(ans))
print (max_ans[0])
```

**Comment by r05323045** [comment]
@Gracilis5 

你的方向大致沒錯，但還需要考慮一些特殊狀況，例如同時有兩個以上最大數字的時候 e.g. 9912 (非實際測資)，你的程式無法正確輸出答案9921，你可以再多想一點edge case，讓你的程式邏輯更完整。

另外，你目前雖然只有一層迴圈，但是判斷了所有與最大數字的位數交換的狀況，這樣仍可能會TLE，你需要再思考一些條件讓迴圈能夠break，可以從我上面提供的思考方向再想想看。
