### ISSUE TITLE
[General] 7-2：加減長方形

### ISSUE THREAD

**Issue by k07224115** [coding-coworking-club/python-2020-spring#34]
## 提交連結

https://judge.ccclub.io/status/a6bfd4681c22374706f825c4e2fe27f1

## 程式碼
```python
l = int(input())
w = int(input())
for i in range(w):
    for j in range(l):
        if (i + j) % 2 == 0:
            print("+", end = "")
        else:
            print("-", end = "")
    print()
```

## 錯誤訊息

Wrong Answer

## 問題描述
問題描述要我們印出+-交錯的長方形，但Sample Output 2 卻是顯示
+-+-
+-+-
+-+-
不知道這個sample是否有誤，其他sample確實都是+-交錯

**Comment by hyusterr** [comment]
你把他拉平來看，確實是加減交錯喔～

k07224115 <notifications@github.com>於 2020年3月15日 週日，19:46寫道：

**Comment by k07224115** [comment]
哦原來是這個意思喔，感謝，因為我看Udemy上的練習，input同樣都是4 3但是output卻不一樣，謝謝
