### ISSUE TITLE
[General] 雜湊函數

### ISSUE THREAD

**Issue by k07224115** [coding-coworking-club/python-2020-spring#342]
## 提交連結

https://judge.ccclub.io/status/da41e22ebe7cea0b46d881f2c8fe85a0
## 程式碼

```python
a = int(input())
b = [int(i) for i in input().split(",")]
res = []
for j in b:
    while True:
        t = j % a
        if str(t) not in res:
            res.append(str(t))
            break
        else:
            j = t + 1
print(",".join(res))
```

## 錯誤訊息

Time Limit Exceeded
## 問題描述

這題我有查了`hash()`的用法，只知道不同的物件會有不同的hash值，但不知道要怎麼套用到這題裡，

請問這題要怎麼使用`hash()`呢~?

**Comment by jeffery12697** [comment]
要實作 hash() 這個資料結構可能要先有 class 的概念，不過這題可以不用用到，你只要設一個 dict 作為查出現過餘數，總時間就會大幅下降，因為 python 中的 dict 就是用 hash( )的原理來存儲 key 的～

**Comment by k07224115** [comment]
@jeffery3756  感謝，我後來用dictionary 跟set都有成功，是因為用list做的話時間複雜度會增加嗎? (不是很清楚我的說法對不對XD，我有查一些網路上的資料)

**Comment by jeffery12697** [comment]
對喔，可以說時間複雜度，至於為什麼會醬有點小複雜，簡單來說，就是list這個資料型態不只記資料也記資料的位置，所以查資料一定是從頭開始往後查，所以如果有n筆資料，每一次查找最悲劇的情況會查n次，但 dict 的型態是一種 hash table，查找會針對給的key值去查找，運氣好可能一次就找到了，所以總體而言會比list有效率

**Comment by k07224115** [comment]
thanks!很實用的資訊~
