### ISSUE TITLE
[General] 圈圈叉叉

### ISSUE THREAD

**Issue by chenyu0217** [coding-coworking-club/python-2020-spring#35]
## 提交連結

https://judge.ccclub.io/problem/192102

## 程式碼

```python
lst = input().split()  

if int(lst[2])-int(lst[1])==1 and int(lst[1])-int(lst[0])==1 :
    print("T")
else:
    print("F")
```

## 錯誤訊息

在jupyter notebook上執行正常，但在judge提交後卻顯示wrong answer

## 問題描述

因為固定輸入的是由小到大的值，所以先用split切成list
然後再用if, 看list內2-1跟1-0的是否=1
如果皆成立則代表是連續=>輸出T
目前想不到問題出在哪QQ

**Comment by jeffery12697** [comment]
不只橫的是 Ｔ ，直的斜的都是

**Comment by yaen1105** [comment]
而且這個寫法輸入 2 3 4 或 5 6 7 也是 True

**Comment by chenyu0217** [comment]
了解，謝謝你們!!
