### ISSUE TITLE
[Week 6] 母音個數排序

### ISSUE THREAD

**Issue by j1300000** [coding-coworking-club/python-2020-spring#350]
## 提交連結

https://judge.ccclub.io/status/44e2abd573277e4dce7051e7f1f39f5b

## 程式碼

```python
lst = []

while True:
    try:
        word = input().strip('\r\n')
        count = 0
        wordlst = []
        for i in range(len(word)):
            wordlst.append(word[i])
        for j in range(len(wordlst)):
            if wordlst[j] in 'AEIOUaeiou':
                count += 1
        lst.append([word, count])
    except:
        break
        
lst.sort(key = lambda x:x[1])

for k in range(len(lst)):
    if k == len(lst)-1:
        print(lst[k][0], end='')
    else:
        print(lst[k][0])
```

## 錯誤訊息

Time Limit Exceeded
Time: 1736ms Memory: 15MB Lang: Python3 Author: b04305005@ntu.edu.tw
## 問題描述

心很累 請問是怎麼回事QAQ

**Comment by jeffery12697** [comment]
第四行你想做什麼
可以的話說明你每個步驟想要做的事，我比較好給你建議

**Comment by j1300000** [comment]
我只是不懂為什麼我自己跑可以得到答案，但交到系統上會出現這個錯誤

**Comment by j1300000** [comment]
我試過用sys.stdin直接讀進來，也還是出現一樣的情況，只是這邊提交的是try except的寫法而已。如果問我說第四行要做什麼，就是試著在題目沒有給一個終止代碼的情況下，讓程式在有資料時運作、沒資料時自己停止。
還是是要問.strip()? 那是因為原本的題目如果用sys.stdin讀進來會出現\r\n，所以要拿掉罷了。

**Comment by jeffery12697** [comment]
好的～，我看了一下你錯了一筆測資會爆時，中間你可以直接用string跑for loop ，不用把string轉list，是一樣的效果
