### ISSUE TITLE
[Week 6] 數字交換最大值

### ISSUE THREAD

**Issue by LT-Weng** [coding-coworking-club/python-2020-spring#359]
## 提交連結

https://judge.ccclub.io/status/18e3eeed4b870e3660cd443648625069

## 程式碼

```python
num=[int(x) for x in input()]
index_max=num.index(max(num))
i=(-1)
j=0
if num.count(max(num))==1 and num[0]!=max(num):
    num[0],num[index_max]=num[index_max],num[0]
else:
    while j==0:
        if num[i]>max(num):
            y=num[i]
            i+=1
        elif num[i]==max(num):        
            j+=1
            num[0],num[i]=num[i],num[0]
        
result=[str(x) for x in num]
print(''.join(result))
```

## 錯誤訊息

<img width="768" alt="螢幕快照 2020-04-29 下午5 02 49" src="https://user-images.githubusercontent.com/62595678/80578684-6fb41d80-8a3b-11ea-87c1-58e31c2c108e.png">

## 問題描述

用jupyter notebook試起來是沒有問題的，只是到judge上面會超時，想不出來應該怎麽更簡化才好，想請助教指教。

**Comment by r05323045** [comment]
Hi @LT-Weng 
你的程式在有兩個以上最大值的狀況會輸出錯誤的答案，超時的問題可以參考其他同學的提問
#334
