### ISSUE TITLE
[General] 11-2：字串字典

### ISSUE THREAD

**Issue by Lipet-dw** [coding-coworking-club/python-2020-spring#36]
## 提交連結

[https://judge.ccclub.io/status/ba6312627dd52263524ed9a68e1cb6f9](https://judge.ccclub.io/status/ba6312627dd52263524ed9a68e1cb6f9)

## 程式碼

```python
def count_num(s):
    num=["a","b","c","d","e",
         "f","g","h","i","j",
         "k","l","m","n","o",
         "p","q","r","s","t",
         "u","v","w","x","y","z"] #用來篩選是不是英文字母
    s=s.lower() #避免大寫英文字母
    s=sorted(s)#讓最終輸出可以照順序
    ans={}
    a=[]
    aa=str()
    for i in s: #把每個字母數量依順序存到字典ans
        if i in num:
            if i not in ans:
                ans[i]=1
            else:
                ans[i]+=1
    for i in ans: #把字典的條目跟數值存放在一起
        a.append(i+str(ans[i]))

    for i in range (len(a)): #將list轉回字串，其實也可以用join做，但當初寫的時候忘記了
        if i==0:
            aa+=a[i]
        else:
            aa+=" "+a[i]
    return aa #輸出最終字串

x=input()
print (count_num(x))
```

## 錯誤訊息

<img width="1122" alt="截圖 2020-03-16 17 55 53" src="https://user-images.githubusercontent.com/62240054/76744690-9b42b780-67af-11ea-8c9c-4959ce2511c0.png">

## 問題描述

我自己用sample跟自己想一些單字進去測試的時候都沒有問題，但丟到judge就是顯示wrong answer，可能有哪個地方漏掉了，還請各位助教協助檢查，感謝。

**Comment by jeffery12697** [comment]
字典這個資料型態沒有順序性，所以跑 for-loop key不會以放進去的順序被拿出，輸出結果跟測資一樣是 jupyter notebook 做的優化，讓字典照字母序跑for，但 judge 就不會有這個優化了
