### ISSUE TITLE
[Week 6] 數字交換最大值

### ISSUE THREAD

**Issue by ray801090** [coding-coworking-club/python-2020-spring#365]
## 提交連結
https://judge.ccclub.io/status/e3dbec14eeefe0561adb1cba679c5c6d

## 程式碼

```
x=input()
a=[]
for i in x:
    a.append(i)
c=sorted(a,reverse=True)
d=a[::-1]
a[0],a[len(x)-d.index(c[0])-1]=a[len(x)-d.index(c[0])-1],a[0] #(數字最大且位數最小的那一位數字)和第一位交換
print(int("".join(a)))

```

## 錯誤訊息
Wrong Answer

## 問題描述
jupyter有跑出來，不確定錯在哪裡

**Comment by r05323045** [comment]
@ray801090 
你的程式在有兩個以上最大值的狀況會輸出錯誤的答案 e.g.9912 (非實際測資)，可以再多想一下怎麼處理各種特殊狀況

**Comment by ray801090** [comment]
@r05323045  謝謝你!已經解決問題了
