### ISSUE TITLE
[Homework 2] 台灣大公園

### ISSUE THREAD

**Issue by lucyyyychen** [coding-coworking-club/python-2020-spring#369]
## 提交連結
https://judge.ccclub.io/contest/48/problem/001204

## 程式碼
```python
n= int(input())
dic={}

for i in range(n):
    ing = input().split()
    dic[ing[0]]=ing[1]

wishlist=input().split()
wishlist.sort(key=lambda x: dic[x])

duck=int(input()) 

for i in range(duck):
    print(wishlist[i][0] , end=' ' if i != duck -1 else'')
```

## 問題描述
1. jupyter測試正確，但judge是WA。
2. 題目沒有說，如果兩個區域人數相同，要怎麼辦？

**Comment by chun9425** [comment]
因為各區域目前所在人數沒有轉成 int，
因此會以字典序的方式進行排序。
請參考 #249

另外請同學下次問問題時注意格式，
否則無法看出縮排狀況會有點困擾 > <
請參考使用教學
https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e
