### ISSUE TITLE
[General] 7-2：加減長方形

### ISSUE THREAD

**Issue by tiffany-c** [coding-coworking-club/python-2020-spring#37]
## 提交連結

https://judge.ccclub.io/status/3afbcfbd0c2a1343079398cf42ee0bef

## 程式碼

```python
l = int(input())
w = int(input())

for j in range(w):
    if j % 2 == 0:
        print("+-" * (l//2) + "+" * (l%2))
    else:
        print("-+" * (l//2) + "-" * (l%2))
```

## 錯誤訊息

jupyter跑得出來，在 judge 系統顯示 wrong answer

## 問題描述

用單層for-loop，在j%2 ==0 時印出+-+-+....
其餘印出-+-+-...
將範例代入juypter中都沒問題，不知道哪裡出錯，感謝解答

**Comment by jeffery12697** [comment]
測資2就錯摟，不一定都是單數列‘+-’複數列‘-+’開頭，這題用兩個 for 比較好解
