### ISSUE TITLE
[General] 平方和

### ISSUE THREAD

**Issue by librairde** [coding-coworking-club/python-2020-spring#38]
## 程式碼

```python
n=int(input())
total=0
for i in range(1,n+1):
    total += i**2
    print(total)
```

## 錯誤訊息

![螢幕快照 2020-03-17 12 45 37 AM](https://user-images.githubusercontent.com/62194355/76781376-97cc2200-67e9-11ea-8dc7-6fc8ec8773d5.png)

## 問題描述
試做影片中例子但是做出來是列出每次加總總和而不是一個總和？

**Comment by hyusterr** [comment]
你把 print 放在迴圈裡，因此他會一直輸出～

librairde <notifications@github.com>於 2020年3月17日 週二，00:53寫道：

**Comment by librairde** [comment]
但我打得程式跟影片介紹的一模一樣耶,為什麼影片的是總和?
以下是講義的, 講義也是這樣打的, 謝謝
sum=0
i=1
while i<=10:
    sum = sum+i
    i =i+1
    print(sum)

**Comment by hyusterr** [comment]
請問縮排是怎麼縮的呢？

librairde <notifications@github.com>於 2020年3月17日 週二，10:38寫道：

**Comment by librairde** [comment]
sum=0
i=1
while i<=10:
    sum = sum+i
    i =i+1
    print(sum)
這是講義的公式但也是列出一整個並不是講義說的總和
1
3
6
10
15
21
28
36
45
55

**Comment by alexypdu** [comment]
下次發問請注意問題分類及標題！
另外程式碼可以用：

\`\`\`python 
\# code 寫在這！
\`\`\`

包起來，大家會比較好讀。
