### ISSUE TITLE
[General] 3-1：字串長度

### ISSUE THREAD

**Issue by chris0416** [coding-coworking-club/python-2020-spring#39]
## 提交連結

https://judge.ccclub.io/problem/180005
## 程式碼

```python
s = input()
n = int(input())
len(s) == n
```

## 問題描述

這段程式我在jupyter上跑出來的都和題目要求的結果相同，但是上傳批改系統後卻顯示是wrong answer.

**Comment by hyusterr** [comment]
最後一行記得要 print 喔
jupyter notebook 會很聰明的顯示結果
但一般來說不會

chris0416 <notifications@github.com>於 2020年3月17日 週二，01:53寫道：
