### ISSUE TITLE
[Homework 3] 小明排工作

### ISSUE THREAD

**Issue by TZU-LING** [coding-coworking-club/python-2020-spring#390]
## 提交連結

https://judge.ccclub.io/status/d537af0ae30382cc2867fa222feee66b
## 程式碼

```python
#建立工作清單
job_num = int(input())
job_lst = []
for i in range(job_num):
    job_lst.append(input().split(" "))
    job_lst[i][1] = int(job_lst[i][1])
#print(job_lst)

#利用任意兩數相乘 = 最大公因數 * 最小公倍數，定義最大公因數函數
def lcm(a, b):
    #先找出最大公因數
    for j in range(1, a + 1):
        if a % j == 0 and b % j == 0:
            gcd = j
    cm = int(a * b / gcd)
    return cm

#找出最小公倍數
if job_num == 1:
    cm = job_lst[0][1]
    #print(cm)
else:
    for k in range(job_num - 1):
        cm = lcm(job_lst[k][1], job_lst[k + 1][1])
    #print(cm)
    
#印出工作時間表
ans_dic = {}
work_lst = []
for i in range(1, cm + 1):
    for j in range(job_num):
        if i % job_lst[j][1] == 0:
            work_lst.append(job_lst[j][0])
            ans_dic.update({i : work_lst})
    work_lst = []
#print(ans_dic)
for key in ans_dic:
    print(key, " ".join(ans_dic[key]))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/36917812/81077411-87017800-8f1f-11ea-99d3-2f64dd84d61f.png)

## 問題描述

測資用jupyter, visualize來跑都沒問題，但在judge上WA，不知道是哪裡沒有考慮清楚~? 謝謝助教~

**Comment by yeutong** [comment]
```
for k in range(job_num - 1):
        cm = lcm(job_lst[k][1], job_lst[k + 1][1])
```
這樣的寫法 cm（最小公倍數）只會依據倒數兩個工作週期計算噢，你是不是忘記把前面工作算出來的 cm 加進後面的迴圈計算了呢~
如果測資像這樣：
3
A 2
B 3
C 5
你可以 print 出 `cm` 看看，會發現只有 15，但最小公倍數應該是 30 才對

**Comment by TZU-LING** [comment]
提交連結:
https://judge.ccclub.io/status/aa63beaaf5aafea217aecd071026fcd4

程式碼:
`#建立工作清單
job_num = int(input())
job_lst = []
for i in range(job_num):
    job_lst.append(input().split(" "))
    job_lst[i][1] = int(job_lst[i][1])
#print(job_lst)

#利用任意兩數相乘 = 最大公因數 * 最小公倍數，定義最大公因數函數
def lcm(a, b):
    #先找出最大公因數
    for j in range(1, a + 1):
        if a % j == 0 and b % j == 0:
            gcd = j
    cm = int(a * b / gcd)
    return cm

#找出最小公倍數
if job_num == 1:
    cm = job_lst[0][1]
    #print(cm)
else:
    cm = lcm(job_lst[0][1], job_lst[1][1])
    for k in range(2, job_num):
        cm = lcm(cm, job_lst[k][1])
    #print(cm)
    
#印出工作時間表
ans_dic = {}
work_lst = []
for i in range(1, cm + 1):
    for j in range(job_num):
        if i % job_lst[j][1] == 0:
            work_lst.append(job_lst[j][0])
            ans_dic.update({i : work_lst})
    work_lst = []
#print(ans_dic)
for key in ans_dic:
    print(key, " ".join(ans_dic[key]))`

錯誤訊息:
![image](https://user-images.githubusercontent.com/36917812/81087559-76a3ca00-8f2c-11ea-86cf-9c1249e270c0.png)

問題描述:
將以上狀況考慮進去後，仍然WA耶~是不是還有什麼沒考慮到呢QQ?

**Comment by k07224115** [comment]
最後面不能對字典跑迴圈，字典是沒有順序的
