### ISSUE TITLE
[Homework 3] OO下載器

### ISSUE THREAD

**Issue by Judy-huang11** [coding-coworking-club/python-2020-spring#392]
## 提交連結

https://judge.ccclub.io/status/ce610d21bb076939357b5a0bdf8daa66
## 程式碼

```python
n = int(input())
download = input().split()
dic = dict()
i = 0
while i < len(download):
    dic[download[i]] = int(download[i+1])
    i += 2
m = int(input())
dic2 = dict()
for _ in range(1, m+1):
    pack = input().split()
    dic2[pack[0]] = pack[1: ]
k = int(input())
user_dic = dict()
lst3 = list()
for _ in range(1, k+1):
    user = input().split()
    lst.append(user[0])
    lst3.extend(user)
def sum(x):
    sum = 0
    for y in x:
        sum += y
    return sum
lst2 = list()
j = 0
while j < len(lst3):
    a = dic2[lst3[j]]
    for k in a:
        b = dic[k]
        lst2.append(b)
    print(sum(lst2)//int(lst3[j+1]))
    j += 2
    lst2 = []
```

## 錯誤訊息

wrong answer

## 問題描述

邏輯：
將下載資源跟組合包各放入字典，並將使用者提出之要求放入串列。

列一個函數是將使用者所要求之組合包的資源大小相加。

然後用for loop跑將每一個使用者要求的組合包之資源大小總和除使用者的網速。

作業已經來不及交了......但是還是想知道哪裡寫錯QAQ

**Comment by cyhsieh264** [comment]
你給的「提交連結」不是這題的喔，可參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e)  進行修正

**Comment by Judy-huang11** [comment]
> 你給的「提交連結」不是這題的喔，可參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 進行修正

不好意思QAQ已修改~

**Comment by cyhsieh264** [comment]
你有一行寫了 `lst.append(user[0])` ，不過前面似乎沒有宣告過 `lst` ？ 

另外，python當中對於list的操作，本來就有sum()這個function，或許可以不用再自己定義一次，感覺code可以再整理一下。

**Comment by Judy-huang11** [comment]
嗚嗚嗚感謝~真的很蠢沒看到。把那行刪掉就對了QAQ
好的我會再把code整理一下，非常感謝。
