### ISSUE TITLE
[Homework 1] 小明幾歲

### ISSUE THREAD

**Issue by JOE-CHOU88** [coding-coworking-club/python-2020-spring#399]
## 提交連結

https://judge.ccclub.io/contest/56/problem/000005
## 程式碼

```python
little_age=int(input())
age_addition=int(input())
print(f"I'm Little Ming, I'm {little_age} years old.")
older_age=str(little_age+age_addition)
print(f"I'm Little Ming's brother, I'm {older_age} years old.")
```

## 錯誤訊息

![homework 1-1](https://user-images.githubusercontent.com/62171839/81493712-4e71ed80-92d5-11ea-9578-393831e8f97f.jpg)

## 問題描述

jupyter測試ok，但是judge跑出compile error，請問助教是甚麼意思?

**Comment by chun9425** [comment]
Judge 的版本較舊，
無法支援 f-string，
因此會出現 compile error
