### ISSUE TITLE
[General] 2-1：數字及字串和

### ISSUE THREAD

**Issue by rock9500** [coding-coworking-club/python-2020-spring#4]
## 提交連結

https://judge.ccclub.io/status/1ccea82f29bb2145ec35369b152742ab

## 程式碼

```python
a=15
b=87
print(a+b)
print("a"+"b")
```

## 錯誤訊息

Wrong Answer

## 問題描述

想請問我這樣寫錯在哪，謝謝

**Comment by waylen0818** [comment]
1.你沒有寫input(影片2-7)
2.資料轉換沒寫(python第二講)

**Comment by rock9500** [comment]
已解決！謝謝！
我修正後成功的程式碼如下 供大家參考><
a=input()
b=input()
print(int(a)+int(b))
print(str(a+b))
