### ISSUE TITLE
[General] 球員成績分析

### ISSUE THREAD

**Issue by k07224115** [coding-coworking-club/python-2020-spring#406]
## 提交連結

https://judge.ccclub.io/status/c480ff0c4b83763c0c39460a67393e14
## 程式碼

```python
a = [int(i) for i in input().split()]
res = []
for j in range(len(a) - 1):
    count = 0
    for k in range(j + 1, len(a)):
        count += 1
        if a[k] > a[j]:
            res.append(count)
            break
        elif k == len(a) - 1:
            res.append(0)
res = [str(k) for k in res + [0]]
print(" ".join(res))
```

## 錯誤訊息

Time Limit Exceeded
## 問題描述

這題我看了Hint中用list實作stack以及從尾巴往前解的提示，還是不太懂該怎麼解，於是就用自己的

方法解但超時了，請問助教們能否給個簡單的例子說明Hint中的提示呢~?

**Comment by alexypdu** [comment]
以 sample input 1 為例：`scores = [89, 56, 78, 9, 81, 7]`
倒著看回來並列舉每一步 stack 的狀態，其中想法要靠你自己補齊。

For clarity, the stack only contains indices `i`, but we will write the value of `scores[i]` beside it in brackets, such as `0 (89)`.

* When `i = 5`, `stack = [5 (7)]`.
* When `i = 4`, `stack = [4 (81)]`.
* When `i = 3`, `stack = [4 (81), 3 (9)]`.
* When `i = 2`, `stack = [4 (81), 2 (78)]`.
* When `i = 1`, `stack = [4 (81), 2 (78), 1 (56)]`.
* When `i = 0`, `stack = [0 (89)]`.

**Comment by ghost** [comment]
不好意思，看了版面上所有問這一題的討論後，還是不太懂這一題stack的運作。（看得懂網路上說的Push、pop，但是還是有點不太明白要如何在這一題使用）
像是上面列出來i=5到0的stack，不曉得用怎麼對應到題目要的答案「0 1 2 1 0 0」，不知道要怎麼找到對應的間隔。

**Comment by alexypdu** [comment]
精神是從尾巴開始看，並記存一個成績遞減（的 index）的 stack。當下一個成績進來時，從 stack pop 出比它小的成績，直到遇到比它大的成績為止，並透過 index 的差距得出答案。
