### ISSUE TITLE
[Week 9] 台大考古題

### ISSUE THREAD

**Issue by JOE-CHOU88** [coding-coworking-club/python-2020-spring#408]
## 程式碼

```python
import requests
import os
from bs4 import BeautifulSoup
url="https://exam.lib.ntu.edu.tw/graduate/term/332%20331%201336%20184%20182%20183%20330%201333%2085%20187%20308%201335%201334%20186%2084%20185%20333%201332%2087%2086%20188%2081%2082%2083"
path=r"C:\Users\Danny\Desktop\PythonSample"
re=requests.get(url)
soup=BeautifulSoup(re.text,"html.parser")
file_set=set()
table=soup.find("tbody")
for row in table.findAll("tr"):
    td=row.findAll("td")
    year=td[0].text.strip()
    dep=td[1].text.strip()
    course=td[2].text.strip()
    link=td[3].a["href"].split("file=")[1].split("&")[0]
    if link not in file_set:
        file_set.add(link)
        file_name=r"PythonSample\{}\{}_{}_{}.pdf".format(course,year,dep,course)
        if not os.path.exists(os.path.join(path,course)):
            os.makedirs(os.path.join(path,course))
        with open("file_name","wb") as f:
            r=requests.get(link)
            f.write(r.content)
            r.close()
            f.close()
```

## 錯誤訊息

![weekly review 9-1 ](https://user-images.githubusercontent.com/62171839/82049539-11e52e00-96e9-11ea-9f6a-fdca7c2b9f50.jpg)
![weekly review 9-2 ](https://user-images.githubusercontent.com/62171839/82049550-17427880-96e9-11ea-994c-babfde04372e.jpg)

## 問題描述

助教你好，我有兩點投影片上的疑慮和一點個人問題想要請教。

投影片上的疑慮
（1）投影片上url的連結好像是2010年的台大考古題，網頁已遭移除，正確的連結應為https://exam.lib.ntu.edu.tw/graduate/term/332%20331%201336%20184%20182%20183%20330%201333%2085%20187%20308%201335%201334%20186%2084%20185%20333%201332%2087%2086%20188%2081%2082%2083
（以第一頁為例）
（2）投影片上「with open(file_name,"wb") as f:」應更正為「with open("file_name","wb") as f:」
※以上的改正若有錯誤還請包涵～～

個人問題
執行上述程式碼後，執行結果如「錯誤訊息」中的兩張圖顯示。有成功創立資料夾，但顯然在複寫檔案時沒有成功把檔案裝進資料夾，請問是哪裡發生了錯誤？
（補充：
path=r"C:\Users\Danny\Desktop\PythonSample" 和
file_name=r"PythonSample\{}\{}_{}_{}.pdf".format(course,year,dep,course)
會多加入"r"是為避免"\"轉義）

**Comment by Kevinweisl** [comment]
Duplicate of #427
