### ISSUE TITLE
[Homework 4] 小甜的少女時代

### ISSUE THREAD

**Issue by nien-j** [coding-coworking-club/python-2020-spring#411]
## 提交連結

https://judge.ccclub.io/status/3089c0265529fdbf032a0b1af6a779a4 

## 程式碼

```python
ok_time = int(input())
rain_lst = [int(item) for item in input().split()]

tmp_lst = []
for i in range(0, 25 - ok_time):  # 1~24
    rain_prob = 1
    for j in range(ok_time):
        rain_prob *= (rain_lst[i+j] / 100)
    tmp_lst.append(rain_prob)

ans_lst = list(enumerate(tmp_lst))

min_rain = 1
for item in ans_lst:
    if item[1] < min_rain:
        min_rain = item[1]
        play_time = item[0]

try:
    print(play_time)
except NameError:
    print()
```

## 錯誤訊息

![tmp](https://user-images.githubusercontent.com/62075027/82119799-eb3ff980-97b3-11ea-9f58-aa75a8fde16c.PNG)

## 問題描述

測資測完看起來都是正確的，試過其他數字看起來也是正確的，但噴WA。

目前想到可能的問題有2個：
(1) 當天學長沒空打球
我的處理是print()，只換行，不輸出東西。
(2) 有兩個時段去打球的降雨機率都一樣低
例如若7點和21點去打球的降雨機率一樣，我的處理是只print 較前面的時段，只輸出7。

請問有誰知道是哪裡出錯了嗎? (我看到已經有2位同學AC了)

**Comment by nien-j** [comment]
沒事了，我發現我就是數學不好的那種人......

「整段時間都不下雨的機率」
「整段時間都不下雨的機率」
「整段時間都不下雨的機率」

**Comment by k07224115** [comment]
你好~請問你後來看出來的盲點是在哪~我也不知道我哪裡出錯，思考邏輯都跟你的一樣~

**Comment by k07224115** [comment]
你好 請問你後來找出的盲點是在哪裡? 我思考邏輯都跟你一樣一直不知道錯在哪

**Comment by LeeWayne1994** [comment]
我也是數學不好的那種人，請問「整段時間都不下雨的機率」是什麼意思QQ

我的邏輯也是，如果學長有空三小時，那就從0～2 、 1～3這幾段時間的降雨機率下去乘，測資OK但也WA。

但我不確定是不是我沒搞懂題目的意思，因為如果這樣算下去，如果有兩段時間的降雨機率分別是'100、0、100'、'1、1、1'，怎麼看都應該要選後者去打球...

**Comment by nien-j** [comment]
> 我也是數學不好的那種人，請問「整段時間都不下雨的機率」是什麼意思QQ
> 
> 我的邏輯也是，如果學長有空三小時，那就從0～2 、 1～3這幾段時間的降雨機率下去乘，測資OK但也WA。
> 
> 但我不確定是不是我沒搞懂題目的意思，因為如果這樣算下去，如果有兩段時間的降雨機率分別是'100、0、100'、'1、1、1'，怎麼看都應該要選後者去打球...


你應該也是不小心把各時段的「降雨機率」直接相乘了，題目要求的是「不降雨」機率喔！
