### ISSUE TITLE
[Homework 4] 小甜的少女時代

### ISSUE THREAD

**Issue by Judy-huang11** [coding-coworking-club/python-2020-spring#412]
## 提交連結

https://judge.ccclub.io/status/eec2a18db6c2af3eda7e90b7ec1d845b

## 程式碼

```python
n = int(input())
m = input().split()
lst1 = list()
for i in m:
    a = 100 - int(i)
    lst1.append(a)
k = 0
b = 1
lst2 = list()
for k in range(0,24):
    for j in lst1[k:k+n]:
        b *= j
    lst2.append(b)
    b = 1
y = 0
dic = dict()
for x in lst2:
    dic[x] = y
    y += 1
lst2 = sorted(lst2, reverse = True)
print(dic[lst2[0]])

```

## 錯誤訊息

wrong answer

## 問題描述

邏輯：

先把24小時的降雨機率換成不降雨機率並放進lst1。然後用for loop跑，從lst1的第一項開始，每n個乘在一起放進lst2。
最後把lst2放進dic，values是時間。先把lst2排序並找出最大值，然後列出此值在dic中的value，就是答案。

在jupyter上跑可以列出正確答案。不知道在邏輯上有沒有什麼錯誤或是沒想到的地方，亦或是我對題意有理解錯誤之處，麻煩大家的幫忙了QAQ

**Comment by chun9425** [comment]
這邊 range 的設定出問題了
```python
for k in range(0,24):
    for j in lst1[k:k+n]:
        b *= j
    lst2.append(b)
    b = 1
```
如果用 sample2 的測資來看，
總共應有 3 段時間的降雨機率，
時段分別是 0-21, 1-22, 2-23， 
但如果依照你這邊的設定，
會出現 24 段時間的降雨機率，
時段分別是 0-21, 1-22, 2-23, 3-23, 4-23, ......，
因此要再修改一下這邊的程式碼喔 ^ ^

**Comment by Judy-huang11** [comment]
原來如此，謝謝><~我又修改了一下......好像還是錯誤QAQ

我把它改成如果「整段時間」的結束時間超過24小時，就會變成(星星*)放進lst2裡面，再把(星星*)從lst2刪掉。

## 提交連結


https://judge.ccclub.io/status/6452ad5cbe0827b87ddadbff54e11952

## 程式碼



```python
n = int(input())
m = input().split()
lst1 = list()
for i in m:
    a = 100 - int(i)
    lst1.append(a)
k = 0
b = 1
lst2 = list()
for k in range(0,24):
    for j in lst1[k:k+n]:
        if k+n < 25:
            b *= j
        else:
            b = '*'
    lst2.append(b)
    b = 1
for x in range(len(lst2)-1,-1,-1):
    if lst2[x] == '*':
        lst2.remove('*')
    else:
        pass
y = 0
dic = dict()
for x in lst2:
    dic[x] = y
    y += 1
lst2 = sorted(lst2, reverse = True)
print(dic[lst2[0]])

```

**Comment by chun9425** [comment]
```python
y = 0
dic = dict()
for x in lst2:
    dic[x] = y
    y += 1
lst2 = sorted(lst2, reverse = True)
print(dic[lst2[0]])
```
這邊用多建立一個 dict 處理排序會有問題，
因為 dict 的 key 是唯一的，
如果有很多時段不下雨的機率相同，
依照你程式的寫法，
dic 裡面只會記錄到最後的那個時段。
你可以試試看下面這筆測資：

3
50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50

會發現 dic 裡面只有記錄到 1 筆資料，
但其實應該會有 22 筆才對。

p.s. 若有多個時段降雨機率相同，會選擇較早的時段打球

**Comment by Judy-huang11** [comment]
原來是這樣><經過修改就成功了~

真的非常感謝~
