### ISSUE TITLE
[Homework 4] 小明發便當

### ISSUE THREAD

**Issue by LeeWayne1994** [coding-coworking-club/python-2020-spring#416]
## 程式碼

```python

```

## 問題描述

題目說「保證便當數量和人數相同」，測資2給的便當只有8個，但喜歡A與喜歡B的人數加起來卻有11個@@？

這是說人總共有8個，但有人既喜歡A又喜歡B嗎？（也不對，只算B也有10個人）
還是要我們考慮人數多於便當的情況下，先拿便當的先贏？所以在測資2來說，最理想的情況便當全部領完，也還有3個人會餓肚子？

**Comment by yeutong** [comment]
感謝提醒，題幹敘述有誤，我們會盡快修正，這部分非常抱歉。這題請以便當數不一定與人數相同來考慮。你的理解是對的，以測資二來說，在最理想的情況下便當全部領完也還有3個人餓肚子~

**Comment by ghost** [comment]
想請問說便當數小於人數時要怎麼計算？問為什麼以測資二來說，在最理想的情況下還是有三個人沒便當？謝謝！

**Comment by LeeWayne1994** [comment]
@15millilitre 便當小於人數時，如果便當拿得完，就是剩下的人得餓肚子，例如AABB 2A 4B，就是兩個B要餓肚子；如果便當拿不完，如AABB 1A 4B，就是4個B要餓肚子

測資二是AABBABAB，便當全部拿完的條件是A、B至少各四，但因為總人數是11個人（1A 10B），所以就算滿足便當拿完的條件像是A5 B6 或 A4 B7，但便當總共就是8個，還是會有3個人拿不到便當吃

雖然我寫完了測資也對，但我一直找不到自己的BUG在哪裡QQ

**Comment by yeutong** [comment]
@LeeWayne1994  感謝幫忙回答！不知道你還沒過是因為 Wrong Answer 還是 Time Limit Exceeded 呢？後者的話可能是因為有個測資比較長容易超時，可以想一下怎麼寫更省時間噢~
