### ISSUE TITLE
[Homework 4] 小甜的少女時代

### ISSUE THREAD

**Issue by chenyu0217** [coding-coworking-club/python-2020-spring#418]
## 提交連結

https://judge.ccclub.io/status/bb8dde1f7feeb8829f1ff348451f155d

## 程式碼

```python
time_len = int(input())
probability_24hr = [int(pro) for pro in input().split()]

def acc_probability(timestart, timelen, list_24hr):  #給定開始時間、時間長度、24小時機率的list => 算出此段時間降雨機率
    acc_pro = 1
    for i in range(timelen):
        acc_pro = acc_pro * list_24hr[timestart]
        timestart += 1
    return acc_pro

acc_probability_list = []  #各個時段機率乘機

for time in range(24-time_len+1):
    acc_probability_list.append(acc_probability(time,time_len,probability_24hr))
    
print(acc_probability_list.index(min(acc_probability_list)))
```

## 問題描述

整體邏輯：用for loop去計算每個時間點開始，持續到整個打球時間所有降雨機率的乘積(用函式計算)→存成一個list並去找最小值出現在哪個index

題目並無特別說明，但這樣寫code的話有兩個前提：
(1)不會跨日打球
(2)如果機率相同，會優先選前面的時段

結果：wrong answer
測資皆通過，仍在想是什麼邊界條件沒有想到。

**Comment by nien-j** [comment]
是要計算「整段時間都『不下雨』的機率」喔，妳直接用input的數字相乘會是降雨機率

**Comment by nien-j** [comment]
掰惹位~ 雖然不影響這題答案，但妳for loop裡計算機率那行漏除以100了

**Comment by chenyu0217** [comment]
我本來想說不下雨機率最高=下雨機率最低，除以100因為每個都要除所以不影響
原來會有差嗎？(原來是數學問題啊)
那我再試試看

**Comment by chenyu0217** [comment]
這樣試之後就AC了，謝謝你！
但還沒想通「不下雨機率最高=下雨機率最低」這個不成立的邊界條件是什麼QQ

**Comment by lptwnb1** [comment]
我也有一樣疑問@@

**Comment by chun9425** [comment]
有沒有除以 100 其實沒有差別，
另外不下雨機率最高不會等於下雨機率最低，
這個大家可能就要去看一下機率了...
但可以簡單提供一個資料讓大家理解
假設有五個時段，
下雨機率分別是 95% 100% 30% 99% 99%
前三個時段都會下雨的機率是 0.95 * 1 * 0.3 = 0.285
時段二至四都會下雨的機率是 1 * 0.3 * 0.99 = 0.297
時段三至五都會下雨的機率是 0.3 * 0.99 * 0.99 = 0.29403
因此下雨機率最低的是時段一至三。
若是考慮不下雨的機率，
前三個時段是 0.05 * 0 * 0.7 = 0
時段二至四是 0 * 0.7 * 0.01 = 0
時段三至五是 0.7 * 0.01 * 0.01 = 0.00007
因此不下雨機率最高的是時段三至五。
