### ISSUE TITLE
[General] cookpad爬蟲卡關

### ISSUE THREAD

**Issue by yaen1105** [coding-coworking-club/python-2020-spring#420]
## 提交連結
https://github.com/iniakunhuda/api-cookpad?fbclid=IwAR3SKlZyx_k2uGtfXq3X3-adTOsr8g1F86EQzUMalhhsUgQUT7XwxmbFlgU

## 程式碼

```python
import requests
r = requests.get('https://cookpad.com/tw/%E6%90%9C%E5%B0%8B/%E7%94%9C%E8%8F%9C%E6%A0%B9') 
print(r.status_code)
```

## 錯誤訊息
403

## 問題描述

我們這組要做的是爬食譜網站的食譜資料下來、做整理，讓使用者可以透過chatbot找到適合自己食材需求、時間、器材、營養的食譜。
現在卡關的地方是，丟request 給https://cookpad.com/tw 這個網站的時候，回傳403
但是有找到一個非官方的api 
https://github.com/iniakunhuda/api-cookpad?fbclid=IwAR3SKlZyx_k2uGtfXq3X3-adTOsr8g1F86EQzUMalhhsUgQUT7XwxmbFlgU
卻完全不知道1.這是可以用的嗎？2.怎麼安裝使用?

我照著裡面README.md的步驟，第二項Go to your “project directory” then run composer install
這裡就卡住，不知道要怎麼輸入在terminal裡面
我們這組共有4個組員，但也沒人知道怎麼操作
也不知道卡關應該去哪問，只好來這裡抱助教大腿，
請各位助教幫幫忙，感激不盡！
@kevinwei @alexypdu

**Comment by Kevinweisl** [comment]
我剛剛試了一下，應該是因為沒有帶 user agent 所以對方網站直接不給你爬
嘗試使用下面程式碼看看
```python
import requests
url = 'https://cookpad.com/tw'
u = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'
re = requests.get(url, headers={'user-agent': u})
print(re.status_code)
```
應該會得到 200 的 status code

**Comment by Kevinweisl** [comment]
你列的那個 api 應該是別人用 PHP 這個語言寫的
我沒有實際安裝不確定能否用，或許你可以找看看有沒有別人寫過的 python 版本爬蟲
