### ISSUE TITLE
[Homework 5] AND virus

### ISSUE THREAD

**Issue by beanli1202** [coding-coworking-club/python-2020-spring#429]
## 提交連結
https://judge.ccclub.io/status/41ffef24c9ccd2c9a4ff1a2557a01885

## 程式碼

```python
#找出感染的起始點
def Find_Start(virus, cell):
    for y in range(len(cell)):
        for x in range(len(cell[y])):
            if cell[y][x] == virus:
                start_y = y
                start_x = x
                return start_y, start_x 
            
#感染程序
def Change_Cell(y, x, num_row, num_column, cell):
    spots = [] #儲存所有會繼續感染其上下左右的位置
    spots.append([y, x]) #從起始點開始
    finished = [] #儲存已經感染過的位置，用來確認
    while(len(spots) > 0):
        for spot in spots:
            for i in range(-1, 2, 2):
                if int(num_row) - 1 >= spot[0] + i >= 0: #確保index沒有超出cell的範圍
                    if [spot[0] + i, spot[1]] not in finished: #確定這個點沒被感染過
                        if cell[spot[0] + i][spot[1]] != -1:
                            cell[spot[0] + i][spot[1]] = (cell[spot[0] + i][spot[1]] & cell[y][x])
                            spots.append([spot[0] + i, spot[1]])
                elif int(num_column) - 1 >= spot[1] + i >= 0: #確保index沒有超出cell的範圍
                    if [spot[0], spot[1] + i] not in finished: #確定這個點沒被感染過
                        if cell[spot[0]][spot[1] + i] != -1:
                            cell[spot[0]][spot[1] + i] = (cell[spot[0]][spot[1] + i] & cell[y][x])
                            spots.append([spot[0], spot[1] + i])
            
            spots.remove(spot) #已經傳給上下左右的點，可以移除
            finished.append(spot) #另外儲存
            
    for j in range(len(cell)): #列印結果
        for k in range(len(cell[j])):
            if k == len(cell[j]) - 1:
                print(cell[j][k])
            else:
                print(cell[j][k], end = " ")

num_row, num_column = input().split() #輸入cell長跟寬
cell = []
for row in range(int(num_row)):
    column = [int(x) for x in input().split()] #輸入cell的內容
    cell.append(column)   
virus = int(input())
y, x = Find_Start(virus, cell) #找出起始點
Change_Cell(y, x, num_row, num_column, cell) #感染



```

## 錯誤訊息
Runtime Error

## 問題描述
用測資在jupyter notebook上面試答案是對的，不知道是漏掉了什麼條件

**Comment by Kevinweisl** [comment]
請解釋你的寫法方便助教幫你找到問題的癥結點

**Comment by beanli1202** [comment]
不好意思，想先請問一下，ˊ題目中說"virus 是病毒代號，他會從該二維 list 裡找出跟自己一樣的值"，跟virus一樣的值有可能有兩個以上嗎?? 想要先釐清一下想法，謝謝!!

**Comment by lptwnb1** [comment]
這題題目我也看不太懂，請問是要寫一個function, return 感染後的cell 算是完成； 還是寫了function, 然後要在最下面take input 將結果print出來？ 謝謝

**Comment by jeffery12697** [comment]
> 不好意思，想先請問一下，ˊ題目中說"virus 是病毒代號，他會從該二維 list 裡找出跟自己一樣的值"，跟virus一樣的值有可能有兩個以上嗎?? 想要先釐清一下想法，謝謝!!

誒我不確定測資內有沒有兩個以上 >< 但應該不會影響，所以就當有吧～

**Comment by jeffery12697** [comment]
> 這題題目我也看不太懂，請問是要寫一個function, return 感染後的cell 算是完成； 還是寫了function, 然後要在最下面take input 將結果print出來？ 謝謝

要 print 出來喔～

**Comment by beanli1202** [comment]
我的這個寫法是先用一個函式在cell這個輸入好的二維陣列裡面找出和virus一樣的值，然後將他的座標回傳。之後再到另一個函式處理cell的改變，首先建立兩個list，一個用來儲存要被感染的座標，並且把起始座標加入這個list，另一個則儲存被感染過的座標。從起始座標開始檢查上下左右的座標位置(if跟elif分別用來在x跟y座標+-1，也就是分別檢查上下跟左右)，先檢查這個座標在不在cell的範圍當中，接著確定這個點沒被感染過(不在finished當中)，再看值是不是-1，如果都通過就感染這個座標對應的值(binary and)，並把該座標加到待傳染的list。最後把這個已經傳染給上下左右的座標從待傳染的list(spots)中移除，並且加入已傳染的list(finished)。當spots裡面已經沒有座標，代表全部感染完，就print改變後的cell。

**Comment by beanli1202** [comment]
後來怕是因為找起始座標的函式只會回傳第一個找到的座標，所以有改成另一個寫法，結果變成wrong answer...所以想先處理檢查條件的部分，再看看這個部分有沒有需要改...謝謝助教!!

**Comment by jeffery12697** [comment]
> 我的這個寫法是先用一個函式在cell這個輸入好的二維陣列裡面找出和virus一樣的值，然後將他的座標回傳。之後再到另一個函式處理cell的改變，首先建立兩個list，一個用來儲存要被感染的座標，並且把起始座標加入這個list，另一個則儲存被感染過的座標。從起始座標開始檢查上下左右的座標位置(if跟elif分別用來在x跟y座標+-1，也就是分別檢查上下跟左右)，先檢查這個座標在不在cell的範圍當中，接著確定這個點沒被感染過(不在finished當中)，再看值是不是-1，如果都通過就感染這個座標對應的值(binary and)，並把該座標加到待傳染的list。最後把這個已經傳染給上下左右的座標從待傳染的list(spots)中移除，並且加入已傳染的list(finished)。當spots裡面已經沒有座標，代表全部感染完，就print改變後的cell。
> 
> 
> 
> 
> 
> 

如果 if 已經判斷正確就不會再進入 elif 判斷，所以elif 下的程式碼可能不會跑到，這樣應該不會跑完上下左右的點

**Comment by beanli1202** [comment]
已解決問題! 非常感謝~
