### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by yhyehg** [coding-coworking-club/python-2020-spring#43]
## 提交連結

https://judge.ccclub.io/status/ee840f585783ece86050b175a3ee9bb3

## 程式碼

```python
lst1 = input().split()
lst2 = input().split()
s = input()
print(s in lst1) or (s in lst2)
```

## 問題描述

在Jupyter Notebook可以跑，不確定錯誤在哪個部分，再麻煩助教解答，謝謝

**Comment by fangha1216** [comment]
print()
只會執行括弧裡面的程式
所以這樣寫的話只會判斷有沒有在lst1裡
如果s只出現在lst2的話答案會錯
