### ISSUE TITLE
[Homework 4] 歌詞網合戰

### ISSUE THREAD

**Issue by 4m3li3** [coding-coworking-club/python-2020-spring#434]
## 提交連結
https://judge.ccclub.io/status/43eac26e4fe222fb8ea25f00745bf67a

## 程式碼

```python

import json  #使用模組
a = input()
b = input()
ajson = json.loads(a) #令兩個dictionary
bjson = json.loads(b)

for k1,v1 in ajson.items():
    v2 = bjson[k1]
    lista = list(v1)  #將歌詞每字分開
    listb = list(v2)
    ind = 0
    diff = 0
    while ind < len(lista):  
        if lista[ind] != listb[ind]:  #每字對應比較
            if diff == 0:    #若已有印過歌名不重複印出
                print(k1)
                diff += 1
            print(ind, lista[ind], listb[ind])
        ind += 1


```

## 錯誤訊息

Runtime Error
<img width="604" alt="螢幕快照 2020-06-02 下午4 49 29" src="https://user-images.githubusercontent.com/50198726/83500261-1e42f680-a4f1-11ea-9868-151946989e51.png">

## 問題描述

不知如何解決runtime error的問題，麻煩助教指點一下～～～～

**Comment by jeffery12697** [comment]
歌詞長短可能會不一樣，要排序

**Comment by 4m3li3** [comment]
@jeffery3756 謝謝助教，但還是有點不懂，是指說像是第三首歌的歌詞兩個網站的不一樣長度嗎？還是不一樣的地方的結果要依照字母排序？

**Comment by jeffery12697** [comment]
喔不是那是兩件事，一個是歌詞長短可能會不一樣，一個是你可能忽略掉題目有說要排序的事～
