### ISSUE TITLE
[Homework 5] 子字串辨識

### ISSUE THREAD

**Issue by JOE-CHOU88** [coding-coworking-club/python-2020-spring#435]
## 提交連結

https://judge.ccclub.io/status/57b20e65200f2e1abad3d56b3a03dd8b
## 程式碼

```python
def isSubStr(s, t):
    from itertools import combinations
    lst_s=[]
    lst_t=[]
    for i in s:
        lst_s.append(i)
    for j in t:
        lst_t.append(j)
    if len(s)==len(t):
        if s==t:
            return True
        else:
            return False
    elif len(s)>len(t):
        return False
    elif len(s)<len(t):
        lst=[c for c in combinations(lst_t,len(s))]
        for m in range(len(lst)):
            if list(lst[m])==lst_s:
                return True
            else:
                continue
        return False
```

## 錯誤訊息

![homework 5-1](https://user-images.githubusercontent.com/62171839/83501917-6bc06300-a4f3-11ea-9617-7517cb803a68.jpg)

## 問題描述

我導入了itertools.combinations幫助我列出所有可能的排列組合情形
（如測資
ace
abcde
總有一天會從abcde取到ace）
想請問助教是否因為把所有的排列組合情形列出，而導致了runtime error
如果是的話能否提供一些方向幫助解決

**Comment by Kevinweisl** [comment]
請提供你正確的提交連結（你貼成題目的連結了）
BTW `runtime error` 不是程式跑太久，跑太久是 `time limit error`

**Comment by JOE-CHOU88** [comment]
提交連結已修正

**Comment by jeffery12697** [comment]
誒我看錯誤是超出記憶空間。這種題目都不能直接用硬爆的，可以想一些方法讓程市省去一些不必要運算，給你一個方向，首先從題目確認讓程式判斷 True 的條件，第一，字串 s 的所有元素，字串 t 都要有 ，第二，字串 s 中的所有元素的相對位置，在字串 t 中一樣，題目簡化一下就大概是這樣，那麼你在確認第一的過程就可以順便檢查第二，如果錯了就可以直接 break 回傳 False

**Comment by JOE-CHOU88** [comment]
## 程式碼



```python
def isSubStr(s, t):
    lst_s=[]
    lst_t=[]
    for i in s:
        lst_s.append(i)
    for j in t:
        lst_t.append(j)
    if len(s)==len(t):
        if s==t:
            return True
        else:
            return False
    elif len(s)>len(t):
        return False
    elif len(s)<len(t):
        lst=[]
        for k in lst_s:
            if k not in lst_t:
                return False
            else:
                lst.append(lst_t.index(k))
        lst_sort=sorted(lst)
        if lst==lst_sort:
            return True
        else:
            return False 
```

## 問題描述


助教你好：
其實我之前的思路原本是這樣（所以寫出上述的code），但是系統給我wrong answer，後來我想到了一個例子s=aba, t=aabaa會回傳錯誤的答案，所以才導入itertools.combinations幫我解決，但似乎會有memory的問題
想問如果回到之前的思路，有沒有其他方向可以顧慮到滿足上面助教提出的一、二兩點又可以解決s=aba, t=aabaa此例子的錯誤？

**Comment by jeffery12697** [comment]
可以解釋一下思路嗎><

**Comment by JOE-CHOU88** [comment]
elif len(s)<len(t)後，我先用迴圈確認s字串的每個字母有沒有在t字串裡，若有則回傳字母在t字串的位置(方便確認相對位置），舉例來說，若s字串有三個字母，而回傳在t字串的index位置是2、3、5(由小到大)，則符合子字串的條件。最後的sorted只是確認是否有小到大排列。但是當字串裡有重複的字母時(如s=aba,t=aabaa)就容易出錯，有方法能避免這個錯誤嗎？

**Comment by jeffery12697** [comment]
欸你的方法我有點想不到可以解決重複的點，我的想法會比較無腦，我會是把 s 所有元素照順序一個一個拿出來，然後檢查有沒有在t 字串如果有下一個就只要檢查一樣的地方往後的字串就好，因為下一個如果是出現在前面就不成立，之後就慢慢遍歷，有錯就直接 break 就好

**Comment by JOE-CHOU88** [comment]
謝謝助教，我換一種寫法就成功了
