### ISSUE TITLE
[General] 圈圈叉叉

### ISSUE THREAD

**Issue by yaen1105** [coding-coworking-club/python-2020-spring#44]
## 提交連結

https://judge.ccclub.io/problem/192102

## 程式碼

xlst= input().split()
x = ('').join(xlst)
if x=="123" or x=="456" or x=="789":
    print ("True")
elif x=="147" or x=="258" or x=="369":
    print ("True")
elif x=="159" or x=="357":
    print ("True")
else:
    print ("False")

## 錯誤訊息

Wrong Answer

## 問題描述

在Jupyter可以跑得出來，但在Judge裡面是Wrong Answer

**Comment by chun9425** [comment]
請注意輸出的要求是 T 或是 F，
而不是 True 或是 False喔

另外提醒一下，
提交連結需從status裡面複製而非直接複製問題當頁的網址，
另外程式碼也請按照指示包起來，不然無法得知程式縮排的狀況，謝謝！
(詳細的用法請參閱學員須知
https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e)

**Comment by yaen1105** [comment]
原來是這個小細節，謝謝
