### ISSUE TITLE
[General] zip函式

### ISSUE THREAD

**Issue by JOE-CHOU88** [coding-coworking-club/python-2020-spring#442]
## 程式碼

```python
matrix=[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
matrix_new=list(zip(*matrix))
print(matrix_new)
```

## 錯誤訊息

![general 2](https://user-images.githubusercontent.com/62171839/83965843-2207bc00-a8e9-11ea-9c39-934f2977e42c.jpg)

## 問題描述

homework 5 的補充資料說可以用zip的功能，但實作時好像會噴typeerror?

**Comment by Kevinweisl** [comment]
你重啟 jupyter 的 kernel 試試看
我剛剛試你的 code 是不會噴 error 的
![image](https://user-images.githubusercontent.com/12825883/84221925-e51a1000-ab08-11ea-9820-6dd34e8a9717.png)

**Comment by JOE-CHOU88** [comment]
真的耶！謝謝助教，不過我還是很好奇當時為什麼會噴error，純粹是jupyter notebook的問題嗎？

**Comment by sc090410** [comment]
應該不是jupyter notebook的問題，我猜是你前面可能有用過 `list` 當作變數名稱之類的，所以現在電腦會覺得這邊的 `list(zip(*matrix))` 當中的 `list` 是前面的那個變數，所以才會 not callable

**Comment by JOE-CHOU88** [comment]
了解，謝謝助教
