### ISSUE TITLE
[Homework 5] 球員成績分析

### ISSUE THREAD

**Issue by JOE-CHOU88** [coding-coworking-club/python-2020-spring#443]
## 提交連結

https://judge.ccclub.io/status/f68b6fc855b1c6de204c31192a2dc305
## 程式碼

```python
point=[int(i) for i in input().split()]
for j in range(len(point)):
    lst=[]
    point_edition=point[:]
    if j==len(point)-1:
        print(0)
    else:
        for k in range(len(point)-j-1):
            if point[j]<point_edition[-1]:
                lst.append(point.index(point_edition[-1])-j)
                point_edition.pop()
            else:
                point_edition.pop()
        if len(lst)>0:
            lst=sorted(lst)
            print(lst[0],end=" ")
        elif len(lst)==0:
            print(0,end=" ")
```

## 錯誤訊息

wrong answer
## 問題描述

思路：用Stack的作法檢查point中個元素後有無更大的分數（從尾至該分數為止），若有則儲存更大的分數與該分數的index差距，最後取出最小的差距值
請問助教可以給我方向或更多測資，讓我檢驗我的code錯在哪邊嗎？

**Comment by alexypdu** [comment]
See the [comment](https://github.com/coding-coworking-club/python-2020-spring/issues/406#issuecomment-630209006) in #406

**Comment by JOE-CHOU88** [comment]
## 提交連結


https://judge.ccclub.io/contest/63/problem/001501
## 程式碼



```python
point=[int(i) for i in input().split()]
if len(point)==1:
    print(0)
else:
    point.reverse()
    lst=[]
    for j in range(len(point)):
        if j==0:
            lst.append(0)
        else:
            for k in range(j):
                if point[j-k-1]>point[j]:
                    lst.append(k+1)
                    break
                else:
                    if k==j-1:
                        lst.append(0)
    lst.reverse()
    for m in range(len(lst)):
        if m==len(lst)-1:
            print(lst[m])
        else:
            print(lst[m],end=" ")
```

## 錯誤訊息


runtime error
## 問題描述


助教你好：
我改了作法，這次從後面開始把距離其最近的更大分數找出來，直接回傳index的差異值。
我有去看406篇的討論，但還是疑惑我的code有沒有用到stack的觀念。stack只需要簡單認識到.append() / .pop() 的應用時機就好了嗎，還是不能只是使用串列，要用參考資料文中提及的連結串列或矩陣呢？

**Comment by alexypdu** [comment]
只需要用到串列即可，本題的時間複雜度要在 O(n)。

**Comment by JOE-CHOU88** [comment]
助教所提及的線性函式階，指的是在輸入資料時，順便跟已輸入的分數比較大小，直接列出所有比它大的分數嗎？

**Comment by alexypdu** [comment]
> 助教所提及的線性函式階，指的是在輸入資料時，順便跟已輸入的分數比較大小，直接列出所有比它大的分數嗎？

`O(n)` 指的是執行的時間應該跟串列長度 `n` 成正比，也就是應該只會有一層的 for-loop（兩層的就是 `O(n^2)` 了）。
