### ISSUE TITLE
[General] 6-3：母音種類個數

### ISSUE THREAD

**Issue by forng** [coding-coworking-club/python-2020-spring#45]
## 程式碼

s = input()
v = ['a','e','i','o','u','A','E','I','O','U']
n = 0

for i in s:
        if i in v:
        n += 1
print(n)

問題描述
想不出辦法  如何把重複的母音次數剔除?
如 zoo  我就會顯示2  
AAoo 就會顯示4

**Comment by chun9425** [comment]
可以用一個新的list存放出現過的母音，
這樣就可以用來判斷母音是否已經出現過了

另外提醒一下，
下次發問請注意問題標題並附上提交連結喔！
另外程式碼也請按照指示包起來，不然無法得知程式縮排的狀況，謝謝！
(詳細的用法請參閱學員須知
https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e)

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文修正。

**Comment by librairde** [comment]
請問 教練建議的是要用什麼方法？？謝謝
可以用一個新的list存放出現過的母音，來判斷母音是否已經出現過了

**Comment by chun9425** [comment]
新增一個 list (以下用 ans_lst 表示)放已經出現過的母音可以幫助判斷母音是否已經出現過了，
舉例來說，
如果新的字母已經透過你原先程式碼的 v = ['a','e','i','o','u','A','E','I','O','U'] 判斷為是母音了，
你可以再利 ans_lst 去判斷這個母音是否已經出現過，
如果之前沒有出現過就把它新增到 ans_lst 裡面，
而如果已經出現過了就不再新增，
這樣 ans_lst 就有所有出現過的母音，而且不會重複。

**Comment by librairde** [comment]
n=input()
letter = 'aeiouAEIOU'
lst = []
sum =0

for i in n:
    if i in letter:
        lst += i
        
    for j in lst:
        if j == i:
            sum += 1
print(sum)
請問那裡錯誤？不知道判斷母音是否出現過怎麼表示？謝謝

**Comment by chun9425** [comment]
同學不好意思，
可以貼一下提交連結嗎，
另外麻煩把整段程式碼都包起來，
不然沒有辦法理解縮排狀況，謝謝~
