### ISSUE TITLE
[Homework 1] 數字數

### ISSUE THREAD

**Issue by librairde** [coding-coworking-club/python-2020-spring#46]
## 程式碼

```python
n=input().split()
print(len(n))
sum=0
for i in n:
    sum+= len(i)
print(sum)

```

## 問題描述
請問該如何排除標點符號
![螢幕快照 2020-03-18 12 24 53 AM](https://user-images.githubusercontent.com/62194355/76879004-987bbb80-68b0-11ea-8d8a-469804678528.png)

**Comment by jeffery12697** [comment]
一一排除標點符號會有點麻煩，也許可以直接判斷是否為字母
