### ISSUE TITLE
[General] Python 安裝套件失敗

### ISSUE THREAD

**Issue by pissaq** [coding-coworking-club/python-2020-spring#5]
按照商管女孩的影片，執行到安裝jupyter notebook時出現下圖錯誤，並也試過在pip前加上！
也還是一樣失敗，請問哪邊需要重新下載或調整嗎？
<img width="572" alt="截圖 2020-03-09 下午11 23 29" src="https://user-images.githubusercontent.com/61981032/76229526-51ad1680-625d-11ea-8155-5db29700a21a.png">

**Comment by sean2249** [comment]
#### 針對內文
1. 有安裝 jupyter notebook 時的錯誤訊息嗎？從上方的圖看起來是 pip upgrade 失敗。

#### 針對截圖上回覆
1. 上面的錯誤訊息，因為沒辦法看到當時你輸入的指令，只從錯誤訊息來看的話，你這個帳戶沒有管理者權限，所以沒辦法更新 pip 。因此 pip 系統建議你安裝在自己的家目錄下，詳細可參看下方網站
> https://stackoverflow.com/questions/42988977/what-is-the-purpose-pip-install-user

2. 針對下方的 pip 升級，可試看看下面的指令，但不確定是否會遇到上一點的問題。
```sh
$ python3 -m pip install --upgrade 
```
> 關於 `pip` 與 `python -m pip` 的差異，可參考下方網站
> https://medium.com/@sean22492249/%E4%BD%BF%E7%94%A8-python-m-pip-%E5%8F%96%E4%BB%A3-pip-7eee70df7fb8

**Comment by pissaq** [comment]
直接從anaconda中開啟jupyter notebook即可，已沒問題
