### ISSUE TITLE
[Homework 1] 數字數

### ISSUE THREAD

**Issue by sunmi3172** [coding-coworking-club/python-2020-spring#50]
## 提交連結

https://judge.ccclub.io/status/8ac38ad980e82459afee559fca71c394
## 程式碼

```python
s = input()

def replaceSybols(string):
    for char in string:
        if char in "~!@#$%^&*()[]{},=-+\/?<>:;''": #特殊字元
            string = string.replace(char,'')
    return string
ss = replaceSybols(s) #以移除標點符號
#print(ss)
ss_list = ss.split() #以單字為單位
#print(ss_list)
print(len(ss_list)) #單字數

count = 0
for i in range(len(ss_list)):
    count += len(ss_list[i])
print(count)
```

## 問題描述

我修改了標點符號的問題 (hello-world在移除符號後是一個單字，it's 在移除符號後也是一個單字)
但judge還是報錯QQ

**Comment by jeffery12697** [comment]
像 hello-world, it's 這種標點符號不會被去掉的字，下面字母數會算錯

**Comment by sunmi3172** [comment]
@alexypdu 我修改了標點符號的問題 (hello-world在移除符號後是一個單字，it's 在移除符號後也是一個單字)
但judge還是報錯QQ

**Comment by alexypdu** [comment]
這題不用去處理標點符號，你想得太複雜了 XD  你要不要先搜尋一下這題的其他 issue 找個方向？

**Comment by sunmi3172** [comment]
好的
我用不處理標點符號的方式解出來了XD
感謝!!!
