### ISSUE TITLE
[General] 字串加密

### ISSUE THREAD

**Issue by yaen1105** [coding-coworking-club/python-2020-spring#55]
## 提交連結

https://judge.ccclub.io/status/5b1d364246cf33e4bb5d27c07a739527

## 程式碼

```python
#將輸入的字串加密
s = input()
ords = []

#將每個字轉成一個+1的ord數字, 並成為一個新的串列ords
for char in s: 
    ords = ord(char)+1

#將每個新的數字，用chr轉回字母
news = []
for num in ords:
    news = chr(num)
print (news)
```
## 錯誤訊息

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-52-8f08f17a31a2> in <module>
      9 #將每個新的數字，用chr轉回字母
     10 news = []
---> 11 for num in ords:
     12     news = chr(ords)
     13 print (news)

TypeError: 'int' object is not iterable
```

## 問題描述

跑到成為一個新串列ords都還可以，但之後要把數字用chr轉回字母就不行了，不知道最後一個迴圈哪裡錯了

**Comment by cyhsieh264** [comment]
TypeError表示資料型態錯誤，按照你目前的寫法，在跑完第一個for迴圈以後，ords變成了一個整數，而非串列。整數本身不是可迭代（iterable）的對象，所以會報錯。

若要生成存有一串數字的串列，需要將 `ord(char)+1`的結果回傳至ords串列，可以運用append()函式，寫成`ords.append(ord(char)+1)`，建議修改第一個迴圈後再測試一下。

提醒：下次請注意發文格式（可參考[GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e)），記得提交連結，並以正確格式貼上程式碼。

**Comment by yaen1105** [comment]
自己還是想不出來，昨天分組時有同學分享了作法：

```python
s = input()
code_s = []
for i in range(0,len(s)):
    code_s.append(chr(ord(s[i])+(i+1)))
print ("".join(code_s))
```

看不懂第四行的 s[i] ， 為什麼不是寫 ord(i)就好呢？ 謝謝回覆

**Comment by alexypdu** [comment]
你要轉換成 ASCII code 的是 `s` 字串的第 `i` 個字元，所以是 `s[i]`。

**Comment by yaen1105** [comment]
了解，所以也就是說只有寫ord(i)的話，因為i 是沒有任何指定或任何意義的，所以電腦會看不懂，這樣的意思吧。再次感謝

**Comment by alexypdu** [comment]
> 了解，所以也就是說只有寫ord(i)的話，因為i 是沒有任何指定或任何意義的，所以電腦會看不懂，這樣的意思吧。再次感謝

只有 `ord(i)` 的話因為 `i` 是整數，`ord()` 預期的參數是字串，所以程式會報錯。

**Comment by yaen1105** [comment]
喔喔原來是這樣，懂了，謝謝
