### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by ChuanChuanHsu** [coding-coworking-club/python-2020-spring#56]
## 提交連結

https://judge.ccclub.io/status/cca5d17ab3d616d9f3c04e4be3ee0397
## 程式碼

```python
lst1 = input()
lst2 = input()
s = input()
lst1 = lst1.split(" ")
lst2 = lst2.split(" ")
print(s in (lst1 or lst2))
```

## 問題描述

我知道如果把最後改成print((s in lst1) or(s in lst2))是可以的，不過我想知道為什麼我的不行，是因為程式只執行到了or前面的內容嗎？
上次的練習還是隨堂作業好像也有一樣的問題，有在小組討論時留言提出，不過好像沒被看到。

**Comment by Kevinweisl** [comment]
還記得在 boolean 運算中我們曾經介紹了 and, or, not 三種運算式嗎？
這三個運算式在做運算時，會把其他東西依照布林值的規則去運算，然後把相對應的結果回傳。

對於這三個運算式
如果他運算的對象是 `int`，那 `0` 會被視為 False，非 0 會被視為 True
如果他運算的對象是 `str`，那 `""` (空字串) 會被視為 False，非空字串 會被視為 True
如果他運算的對象是 `list`，那 `[]` (空串列) 會被視為 False，非空串列 會被視為 True

回到你的寫法，你針對兩個 list 做 or，對於 or 來說，只有兩個值都是 False 的情況下，才會輸出 False
在這裡，你的 lst1 不是 False 的狀況下， `lst1 or lst2` 的結果其實是 lst1
(你可以自己在 jupyter 中測試，把 `lst1 or lst2` 印出來看看，或是利用 week3 上課補充時介紹的 Trace code 工具追蹤看看每個狀態程式是不是都照你的思路在執行)

總而言之，`s in (lst1 or lst2)` 和你想的行為不一樣。
你可以改成 `(s in lst1) or(s in lst2)` ，或是改成 `s in lst1+lst2`
