### ISSUE TITLE
[Homework 1] 優惠券

### ISSUE THREAD

**Issue by bytchen** [coding-coworking-club/python-2020-spring#57]
## 提交連結

https://judge.ccclub.io/status/cb15fb6455f1216286b309856436c6a8

## 程式碼

```python
dc = []
for i in range(5):
    str_temp = input().split()
    if len(str_temp)!=1:
        dc.append(int(str_temp[1]))
    else:
        dc.append(int(str_temp[0]))
price=int(input())
for i in range(5):
    if dc[i] <10:
        price = price*(dc[i]*0.1)
    else:
        price = price - dc[i]
if price<=0:
    price=0
print(int(price))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/61926309/76953334-813cdc80-6949-11ea-9a1b-b476747438c6.png)

## 問題描述

我的想法是：先將優惠的程度讀進一個list（dc）裡面，之後再從這個list判斷到底是直接減少價格還是打折，在notebook測試是對的，但不知道為什麼WA，請助教解惑，謝謝！

**Comment by jeffery12697** [comment]
減少的價格也有可能小於十，不一定都是打折

**Comment by Peterorr** [comment]
是的，請注意自己的判斷式是否會將「折價 9 元」誤判成「打 9 折 」
