### ISSUE TITLE
[Homework 1] 二十六進位

### ISSUE THREAD

**Issue by Julieliu81** [coding-coworking-club/python-2020-spring#58]
## 提交連結

https://judge.ccclub.io/status/b74d534feb6366c0f415552c8a22e88a
## 程式碼

```python
number = int(input())
if (number > 26**2 ) and (number > 26 ):
    print(chr(number // 26**2 + 65)+chr(number // 26 + 65)+chr(number % 26 + 65))
elif (number < 26**2 ) and (number > 26 ):
    print(chr(number // 26 + 65)+chr(number % 26 + 65))
elif (number < 26 ):
    print(chr(number + 65))


```

## 錯誤訊息

Runtime Error
## 問題描述

想請問是哪裡出問題了呢？( 是需要考慮26**3等等，還是現有程式碼有錯呢？
感謝！

**Comment by Kevinweisl** [comment]
請正確排版你的程式碼，方便助教幫你解惑。
使用教學請參考：
https://www.notion.so/ccclub/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e

**Comment by Julieliu81** [comment]
不好意思，已更正排版！

**Comment by alexypdu** [comment]
今天如果給你一個很大的數字，例如 `100000000`，你的程式就會出錯了。
