### ISSUE TITLE
[Week 3] 小明來數數

### ISSUE THREAD

**Issue by ChuanChuanHsu** [coding-coworking-club/python-2020-spring#59]
## 程式碼

```python
x = input()
a = x.split(" ")
ans1 = []
ans2 = 0
while int(a[0]) <= int(a[1]):
    ans1.append(a[0])
    ans2 += int(a[0])
    a[0] = str(int(a[0]) + int(a[2]))
for i in range(len(ans1)-1):
    print(ans1[i], end = " ")
print(ans1[-1])
print(ans2)
```

## 問題描述

輸出跑時都沒問題，但繳交作業時wrong answer。
這樣的做法偏向土法煉鋼，課堂教的更快更好，但我還是想知道這樣做哪裡不對。

**Comment by Kevinweisl** [comment]
題目理解錯誤，題目中提到：
「從首項開始列出這個數列的每一項數值，_**直到下一項大於或等於最大上限為止**_，並且同時計算出等差數列的和。」

**Comment by r05521230** [comment]
我也是答案對但wrong answer，請問是哪邊出錯呢？

A = input()
a = A.split(" ")

max = int(a[0])
all = []
all.append(a[0])


while max+int(a[2]) <= int(a[1]):
    max += int(a[2])
    all.append(str(max))

s = 0
for i in range(0,len(all)):
    s += int(all[i])
    

ALL = " ".join(all)
print(ALL)
print(s)

**Comment by alexypdu** [comment]
@r05521230 留言的程式碼不要忘記用

\`\`\`python
\# code
\`\`\`

包起來唷！

**Comment by ChuanChuanHsu** [comment]
@Kevinweisl 感謝！已得到解答，不過上面還有其他同學的提問，我該直接關閉提問嗎？

**Comment by alexypdu** [comment]
@ChuanChuanHsu 直接關掉吧。
@r05521230 如果還有疑問請另外開一篇唷。
