### ISSUE TITLE
[General] 3-4：自己回文

### ISSUE THREAD

**Issue by waylen0818** [coding-coworking-club/python-2020-spring#6]
## 程式碼

```python
s = str(input())
print(s[ : ] + s[::-1])
```

## 問題描述
此題想不到解法，看udemy裡面有之前同學提供的解
請問為何s[::-1]可以當作回文字串?
謝謝

**Comment by dada8397** [comment]
Python list slice 的用法是 `s[a:b:c]`
a 與 b 代表你想要的區間，c 代表在區間內的間隔數
例如 `s[1:5:2]` 代表從 index = 1 ~ index = 5 每兩個值取一次
而如果是帶負數進去的話就代表從尾巴開始算
所以 `s[::-1]` 的意思是「從尾巴開始每一個值取一次」
可以參考[這篇](https://sites.google.com/site/ezpythoncolorcourse/indexwithslice)

**Comment by waylen0818** [comment]
> Python list slice 的用法是 `s[a:b:c]`
> a 與 b 代表你想要的區間，c 代表在區間內的間隔數
> 例如 `s[1:5:2]` 代表從 index = 1 ~ index = 5 每兩個值取一次
> 而如果是帶負數進去的話就代表從尾巴開始算
> 所以 `s[::-1]` 的意思是「從尾巴開始每一個值取一次」
> 可以參考[這篇](https://sites.google.com/site/ezpythoncolorcourse/indexwithslice)

謝謝!!
以解決我的問題~

**Comment by wenchilin-m** [comment]
呈上
```python
list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
list[0:10:2]
```
list[0:10]顯示[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] -> 理解
若list[0:10:2]的2指的是隔兩位取list[0:10]資料，顯示[0, 2, 4, 6, 8] -> 理解

回到原題目
```python
s = str(input())
print(s[::-1])
```
s輸入Hello，從最後一位取input資料，往前取到第一位，顯示[olleH] -> 理解

但是如下時
```python
list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] #或 list = str("0123456789")
list[0:10:-1] 
```
從最後一位取input資料，往前取到第一位，應顯示[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
結果卻顯示 [] -> 還是list邏輯不一樣？謝謝！

**Comment by dada8397** [comment]
@wenchilin-michelle 這邊你可以想成它先把 `list[0:10]` copy 出來之後， `由第 0 項開始往前每一項取一項`
如果要有你預期的結果的話就要改成 `list[9::-1]`
不過這邊要注意的是 `list[a:b:c]` 有包含 a 但是沒有包含 b，也就是實質上會取 a~(b-1) 項
這也是因此為什麼要用 `9::-1` 而不是 `10:0:-1`（雖然超過 index 的話 python 也會幫你從最大的 index 開始取）
另外建議變數命名要避開 python 的[保留字](https://www.programiz.com/python-programming/keywords-identifier)或是 [built in function](https://docs.python.org/3/library/functions.html) name，list 就是其中一個 python 的 built in function

**Comment by dada8397** [comment]
另外有空的話可以玩玩看 `[9::-1]` `[2::-1]` `[2:]` `[:2:-1]` 這些的差別 XD

**Comment by wenchilin-m** [comment]
回好快！好的，以後會注意避開保留字列表(built-in function name)～謝謝！
`[9::-1] [2::-1] [2:]` 可以理解，如下我理解`[:2:-1] `指的是「切掉[:2]資料、倒序顯示」對嗎？
有試過`[ :2:-1: 2]`是錯誤訊息，應該沒有三種冒號的用法了吧，Slicing好複雜 :flushed:

```python
d1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
d1[:2:-1]
```
output `[9, 8, 7, 6, 5, 4, 3]`

```python
d2 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
d2[:3:-1]
```
output `[9, 8, 7, 6, 5, 4]`
