### ISSUE TITLE
[General] 1-1：輸出兩次

### ISSUE THREAD

**Issue by topinal** [coding-coworking-club/python-2020-spring#60]
## 提交連結

https://judge.ccclub.io/problem/180001

## 程式碼

```python
s1 = "Pine"
s2 = "Apple"
print(s1 + s2,"\n",s1 + s2,sep="")

s1 = "Python"
s2 = "Class"
print(s1 + s2,"\n",s1 + s2,sep="")
```

## 問題描述

我在jupyter notebook上分別跑這兩段程式碼都可以跑出答案，不知為何在作業批改系統上輸入上述程式碼後就一直顯示錯誤...

**Comment by hyusterr** [comment]
s1 s2 要改成吃 input() ㄛ
不然不管給你什麼字串，你都輸出一樣的答案

**Comment by alexypdu** [comment]
發問前請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將**標題**、**內文**、**程式碼**都調整好唷
