### ISSUE TITLE
[Week 3] 冠亞軍分數差

### ISSUE THREAD

**Issue by huajenshen** [coding-coworking-club/python-2020-spring#61]
## 提交連結

https://judge.ccclub.io/status/a400f4ca48c6b93c0d9748f90301d008

## 程式碼

```python
a=input().split()
b=max(a)
a.remove(max(a))
c=max(a)
print(int(b)-int(c))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/62345179/76977118-d8ee3e80-696f-11ea-999f-465a281c205a.png)

## 問題描述

在Jupyter上的結果看起來都符合題目的要求，但在批改系統是錯的，不知道為什麼。
剛剛有問助教這一方，好像是字串、整數沒有轉換的問題，但我還是不太明白癥結點。

**Comment by hyusterr** [comment]
字串的比大小跟整數的比大小是不一樣的，例如：
'1111' < '112'
1111 > 112
因此，你要先把 input 裡面的東西都轉成數字，才有辦法選出正確的最大值

huajenshen <notifications@github.com>於 2020年3月18日 週三，23:29寫道：

**Comment by wewewei** [comment]
> ## 提交連結
> https://judge.ccclub.io/status/a400f4ca48c6b93c0d9748f90301d008
> 
> ## 程式碼
> ```python
> a=input().split()
> b=max(a)
> a.remove(max(a))
> c=max(a)
> print(int(b)-int(c))
> ```
> 
> ## 錯誤訊息
> ![image](https://user-images.githubusercontent.com/62345179/76977118-d8ee3e80-696f-11ea-999f-465a281c205a.png)
> 
> ## 問題描述
> 在Jupyter上的結果看起來都符合題目的要求，但在批改系統是錯的，不知道為什麼。
> 剛剛有問助教這一方，好像是字串、整數沒有轉換的問題，但我還是不太明白癥結點。

可以參考上課講義中的：a= [int(i) for i in input().split()]

**Comment by huajenshen** [comment]
感謝！知道bug在哪裡了
