### ISSUE TITLE
[General] 2-2：偶數

### ISSUE THREAD

**Issue by Monika-NTU** [coding-coworking-club/python-2020-spring#65]
## 程式碼

```python
a=input()
b=0
print((a%2)==b)
```

## 錯誤訊息

![螢幕快照 2020-03-19 上午1 37 17](https://user-images.githubusercontent.com/62351088/76990282-ab5ec080-6982-11ea-81d5-dc6426a5fcd2.png)

## 問題描述
不知道哪裡出現問題，到了第三行就出現錯誤了。

**Comment by alexypdu** [comment]
同學請不要自創標題，發問前請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e).

**Comment by Monika-NTU** [comment]
> 同學請不要自創標題，發問前請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e).

因為我的google網頁有自動翻譯，所以看範例時沒有特別注意到它已經把general翻譯，造成困擾不好意思。

**Comment by alexypdu** [comment]
你的 `a = input()` 並沒有轉型成 `int`，所以直接 `% 2` 會出錯。
