### ISSUE TITLE
[General] 6-2：完全平方數

### ISSUE THREAD

**Issue by waylen0818** [coding-coworking-club/python-2020-spring#66]
## 程式碼
n = int(input())
for i in range(1,n+1):
    if i**2<n:
        print(i**2)

```python

```

## 問題描述

為何第四列
print(i**2)才是對的?
寫pirnt(i)答案是錯誤
不太懂此邏輯
謝謝

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。
