### ISSUE TITLE
[Week 3] 小明來數數

### ISSUE THREAD

**Issue by bytchen** [coding-coworking-club/python-2020-spring#67]
## 提交連結

https://judge.ccclub.io/status/fe6b8bf9663b6c0dfb43abe83b295a50

## 程式碼

```python

str1 = [int(i) for i in input().split()]
sum=0
for i in range(str1[0], str1[1], str1[2]):
    #if i!=str1[0]:
     #   print(' ', end='')
    print(i, end=' ')
    sum+=i
print('')
print(sum)
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/61926309/77024501-aa04b680-69c9-11ea-8f50-232431b9a2e6.png)

## 問題描述

測試的sample是對的，但不知道為什麼出來是WA，請助教解惑，謝謝！

**Comment by alexypdu** [comment]
Duplicates #70.
