### ISSUE TITLE
[Homework 1] 數字數

### ISSUE THREAD

**Issue by Isaac-Chu** [coding-coworking-club/python-2020-spring#72]
## 提交連結

https://judge.ccclub.io/status/d1f00f2ff9eec9ac6183b694de83b2d9
## 程式碼

```python
words=input()
lst1=words.split()
print(len(lst1))
sum=0
lst2=["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
str2=",".join(lst2)
for i in words:
    if i in str2:
        sum=sum+1
print(int(sum))

```

## 錯誤訊息

![rrr](https://user-images.githubusercontent.com/62022637/77065267-f0830100-6a1b-11ea-8f62-858b0adf4453.JPG)

## 問題描述

這是我該題的第一個寫法，想法如下:
for 數字數:
設一個words字串
把字串轉成list
用len看list裡有幾個字然後輸出
for字母數:
定義sum
設一個字母字串
把字母字串用join轉成string
用for loop 把words字串裡的拿來跟字母的string比，有的話sum+1
輸出sum值

以上方法jupyter上試了幾個句子是可以的，但是批改系統跑wrong anawer
而我再troubleshooting 時想到，如果直接打letter字串(letter="很多字母")，直接以兩字串來對，程式碼可以更整潔，試一下發現這樣做批改系統是accept的，但我不知道我原本的方法(如上程式碼部分)，可能是物件類型之類的，錯在哪

**Comment by jeffery12697** [comment]
可以不用轉 string ，直接用`if i in lst2: `也行
