### ISSUE TITLE
[Week 3] 小明來數數

### ISSUE THREAD

**Issue by yaen1105** [coding-coworking-club/python-2020-spring#73]
## 提交連結

https://judge.ccclub.io/status/c707bccdfe589cec2eb275419fdce633
## 程式碼

```python
lst = [int(i) for i in input().split()]
start = lst[0]
end = lst[1]
step = lst[2]
newlst = []
total = 0

while start < end:
    newlst.append(start)
    start += step
    total += start
    
print (' '.join([str(_) for _ in newlst]))
print(total)
```

## 問題描述

想問兩個問題：
1. 第10行和第11行，如果順序不同為什麼會不一樣：
例如先寫 total += start,  再寫 start += step 最後相加答案就是對的
但先寫 start += step 才寫 total += start 最後相加的答案就是錯的
2. 最後join的語法，為什麼不能寫成
print (' '.join(newlst))就好？
謝謝

**Comment by jeffery12697** [comment]
1. 可以自己測試幾個數字試試，如果上下顛倒第一次迴圈的時候第一個數字雖然有被 append 但再被加入 total 之前就加 step 了，所以等於 total 少加初始數字
2. string.join() 函式處理的資料裡面都要是 string ，如果有 int 在裡面會噴 error，所以才要轉換資料型態

**Comment by yaen1105** [comment]
懂了，謝謝！
