### ISSUE TITLE
[Week 3] 小明來數數

### ISSUE THREAD

**Issue by tiffany-c** [coding-coworking-club/python-2020-spring#76]
## 提交連結

https://judge.ccclub.io/status/4328ad7ae1f3b2dd09bba07e50d6e6b3

## 程式碼

```python
lst = [int(num) for num in input().split()]
total = 0
n = lst[0]

print(n, end = " ")

while n <= lst[1]:
    total += n
    n += lst[2]
    
    if n > lst[1]:
        break
    if n > lst[1]-lst[2]:
        print(n, end = "")
    else:
        print(n, end = " ")
print()
print(total)
```

## 錯誤訊息
wrong answer

## 問題描述
在jupyter上兩個範例都可以跑，但judge上wrong answer，
用    if n > lst[1]-lst[2]: 的想法是最後一項應該落在(最大上限-差)和(最大上限)之間，所以n>lst[1]-lst[2]應該是最後一項，也可以避免最後項有空格的問題。不知道是哪裡寫錯還是理解有誤，感謝解答！

**Comment by alexypdu** [comment]
Duplicate of #77
