### ISSUE TITLE
[Homework 1] 二十六進位

### ISSUE THREAD

**Issue by yvet57** [coding-coworking-club/python-2020-spring#79]
## 提交連結

https://judge.ccclub.io/status/e1746b52c85b36129b957f0ac4eb3411

## 程式碼

```python
x = int(input())

i = x
z = []
n = 1
while i // 26 >= 26:
    z.insert(-n, chr(i % 26 + 65))
    n = n + 1
    i = i // 26
z.insert(-n, chr(i % 26 + 65))
z.insert(-n-1, chr(i // 26 + 65))
for item in z:
    print(item, end="")
```

## 錯誤訊息

在judge系統顯示wrong answer

## 問題描述

在judge系統顯示wrong answer，但是在jupyter notebook測試都可以跑出答案，不知道是哪裡出了問題(?
我是先創一個空白list z，然後從最後一個index開始往前把餘數和除以26的結果往前擺

**Comment by alexypdu** [comment]
請提供提交連結。

**Comment by yvet57** [comment]
> 請提供提交連結。

我把judge的連結貼上去了> <

**Comment by alexypdu** [comment]
如果輸入小於 26 呢？

**Comment by yvet57** [comment]
!懂了，沒注意到，謝謝
