### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by f629** [coding-coworking-club/python-2020-spring#8]
## 提交連結

https://judge.ccclub.io/status/f67cb25313cc72111d2772c7c32eb78c
## 程式碼

```python
str1="apple pen"
str2="pineapple pen"
s="apple"
lst1=str1.split()
lst2=str2.split()
print((s in lst1) or(s in lst2))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/34017734/76319244-e70de080-6319-11ea-98dc-828b00ca6286.png)
Wrong Answer
## 問題描述

一、依照題目建議嘗試使用 string.split() 這個函式，前兩行包含了兩組字串，字串間皆以空格分開，請將其轉換成兩串列 lst1 和 lst2，而第三行則是一個字串 s，如果能在 lst1 或 lst2 找到 s ，則輸出 True，否則輸出 False。
於編輯器可執行至輸出 True，但於批改系統Wrong Answer。 
二、依發問模板練習提問。謝謝。

**Comment by hyusterr** [comment]
str1 str2 是吃 input 喔~
這樣會造成不論輸入是什麼他都回傳固定的答案喔~

**Comment by f629** [comment]
謝謝 了解。
str1=input() 
str2=input() 
s=input() 
lst1=str1.split()
lst2=str2.split()
print((s in lst1) or(s in lst2))
