### ISSUE TITLE
[Homework 1] 小明查單字

### ISSUE THREAD

**Issue by yaen1105** [coding-coworking-club/python-2020-spring#80]
## 提交連結

https://judge.ccclub.io/status/c250745b5ee7f724b8d1e49a8cb24dc1

## 程式碼

```python
words_lst = input().split()
prefix = input()
for word in words_lst:
    if word[0:(len(prefix))] == prefix: 
        print (words_lst)
```

## 問題描述

我先用只有一個單字的方式去想，寫出來的code如下，有測試成功：
word = input()
prefix = input()
if word[0:(len(prefix))] == prefix:
    print (word)
else:
    print ("none")

但換成list和for loop的方式寫出如最上方的程式碼就錯了
在jupyter上跑的結果變這樣：
apple big appear
app
['apple', 'big', 'appear']
['apple', 'big', 'appear']
覺得應該是for loop寫錯，但不曉得該怎麼改。

**Comment by alexypdu** [comment]
你的第五行：

```python
print (words_lst)
````

會把整個 list 印出來啊！你應該是要把符合條件的字印出來，並用空格分開。

**Comment by yaen1105** [comment]
原來是這樣!! 我增加了一個List，再用append把找到的字加進去那個List，然後用join輸出，調整縮排，就可以了。謝謝！
