### ISSUE TITLE
[Homework 1] 數字數

### ISSUE THREAD

**Issue by yu-chieh-chang** [coding-coworking-club/python-2020-spring#81]
## 提交連結

https://judge.ccclub.io/contest/40/problem/041103

## 程式碼

```python
sen = [str(i) for i in input("").split()]
voc = len(sen)
print(voc)

sum = 0
letter = ['a','b','c','d','e','f','g','h','i','j','k','l','m','m','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
for i in sen:
    sum = sum+1
print(int(sum))

```

## 錯誤訊息

wrong answer

## 問題描述

有成功輸出單字數，但數字母數的時候卻還是輸出單字數
目前的做法是用迴圈去對照字母的清單，然後算對照了幾個

**Comment by cyhsieh264** [comment]
目前你在 for迴圈 裡並沒有用到 letter串列 ，實際只是在重複執行 `sum += 1` ，最後輸出的結果，相當於是在數 sen串列 中有幾個元素。

依照你的邏輯，看起來有兩件要做的事：
1. 逐一取 sen串列 當中的字串。
2. 在取出的字串中，逐一驗證每一個字元是否在 letter 當中。

目前的迴圈已可以做到使 i 依序等於 sen串列 當中的字串，然而接下來你就沒有用到 i 了。

若要再逐一驗證 i 當中的每一個字元，則需要再跑一層 for迴圈 ，如 `for char in i:` ，使得 char 變數 依序等於 i 當中的字元。接著在第二層迴圈當中，才會需要確認每一個字元是否在 letter 中，因此可以運用條件判斷式 `if char in letter:` ，在這個條件判斷當中，再去執行 `sum += 1` ，如此一來便可以計算出總字母數。

另外，sum變數的type已是整數，不需再用 `int()` 轉換～
