### ISSUE TITLE
[Homework 1] 優惠券

### ISSUE THREAD

**Issue by yaen1105** [coding-coworking-club/python-2020-spring#82]
## 提交連結

https://judge.ccclub.io/status/c982bd544c025ee6610807db44abf685

## 程式碼

```python
coupon_lst = [input(),input(),input(),input(),input()]
origin = int(input())
total = 0

for coupon in coupon_lst:
    if coupon[0:1] == "$":
        total = origin - int(coupon[2:])
    if len(coupon) == 1:
        total = int(total * (int(coupon[0:1])*0.1))
if total <0 :
    total = 0
print (total)
```

## 問題描述

Kevin3/19星期四晚上的直撥漏了這題的提示。
我的思考方向是1.優惠卷輸入成一個List 2.迴圈List算出折價後的值
但問題應該是出在 第七行和第九行 (if下面的statement)
因為不曉得怎麼讓他去用上一個計算的“結果”來算下一次(而不是用原價)
請提供這題的提示或可能會用到的敘述，謝謝。

**Comment by jeffery12697** [comment]
可以設定一個變數來做計算，或是直接用你接入原始價錢的變數，你每一次的迴圈都會對他做運算，等於是每一次的回圈結束那個變數就會有新的值，也就是你所說上一個計算的結果

**Comment by yaen1105** [comment]
試著改了total這個變數的指定為 origin
但還是WrongAnswer，結果後來發現total是最後在print的時候加上int就行了，感謝協助！
