### ISSUE TITLE
[General] 讓jupyter在google雲端硬碟存取檔案

### ISSUE THREAD

**Issue by linchengyuan1985** [coding-coworking-club/python-2020-spring#83]
## 程式碼

```python

```

## 問題描述

因為使用習慣的關係，會同時使用桌機、筆電，請問有沒有辦法讓jupyter檔案的存取在雲端硬碟上執行，這樣就可以讓編寫的檔案同步。謝謝

**Comment by jeffery12697** [comment]
可以每次寫完存成.py 檔上傳雲端，要用再開檔就好
