### ISSUE TITLE
[Week 3] 小明來數數

### ISSUE THREAD

**Issue by forng** [coding-coworking-club/python-2020-spring#85]
## 程式碼

```python
seq_params = [int(i) for i in input().split()]
seq = []
now = seq_params[1]
while now < seq_params[1]:
    seq.append(now)
    now = now + seq_params[2]
print(" ".join(str(i) for i in seq))
print(sum(seq))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/62025548/77219272-22f14300-6b6f-11ea-855a-ce2d2cd4583e.png)

## 問題描述

不懂最後的'int' object is not callable怎麼解決

**Comment by jeffery12697** [comment]
`now = seq_params[1]` 這句應該是放 0 
`" ".join([str(i) for i in seq])` 如果要用 list comprehension 要用中括號刮起來
