### ISSUE TITLE
[General] 綜合1-2：一奇多偶

### ISSUE THREAD

**Issue by k1012ken** [coding-coworking-club/python-2020-spring#89]
## 提交連結

https://judge.ccclub.io/status/15351b0c1e89bf75be54799e71a17f32

## 程式碼

```python
while True:
    
    int_nums = [int(x) for x in input().split(" ")] # 輸入為一行，包含數個整數，以空格分隔，裝到 list 裡
    dict_nums = dict() # 創造一個空字典， key 為整數， value 為次數


    for i in int_nums:
        if i not in dict_nums.keys(): # 假如整數原本不在字典的 key 裡，該整數的次數(value)指定為 1 次
            dict_nums[i] = 1
        else:  # 假如整數在字典的 key 裡，該整數的次數(value)指定為次
            dict_nums[i] += 1

    odd_lst = [j for j in dict_nums.keys() if dict_nums[j]%2 != 0] # 創造一個字串，假如 字典的 value(次數) 為奇數 ， 就把字典的 key(整數)塞進 list裡 

        
    if len(odd_lst) == 1: # 最後輸出為一行，包含一個整數，且該整數為奇數。 odd_list只塞  1 個數時，才能跳出迴圈
        print(odd_lst[0])
        break

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/61833109/77221890-ed595380-6b88-11ea-9468-8399b70f4e4f.png)

## 問題描述

輸入為一行，包含數個整數，以空格分隔，裝到 list (int_nums) 裡

創造一個空字典(dict_nums)， key 為整數， value 為次數

假如整數原本沒在字典的 key 裡，就將它 value 指定為 1 次，否則就將 value 直接累加 1 次

再來把字典的次數(value) 為奇數 的 key 值，塞進 1 個 list(odd_lst) 裡

當odd_lst 的長度為 1 ，代表只有唯一一個奇數，就跳出迴圈，否則繼續跑回圈。

Jupyter Notebook上能跑，批改系統為 Runtime Error，不知哪裡出錯

**Comment by chun9425** [comment]
題目敘述已經保證只有一個元素出現過奇數次，
不需要再判斷是否只有一個奇數，
因此最外層的 while loop 以及最後的 if statement 都可以刪掉。

另外請將第二行
```python
int_nums = [int(x) for x in input().split(" ")]
```
改成
```python
int_nums = [int(x) for x in input().split()]
```
這應該是造成 runtime error 的原因
詳細說明可參考 #32

**Comment by k1012ken** [comment]
感謝助教協助！
