### ISSUE TITLE
[General] 關於.upper() 

### ISSUE THREAD

**Issue by tom192180** [coding-coworking-club/python-2020-spring#9]
## 程式碼

```
s = "leraningisgood"
print(s.upper())

```

## 問題描述

想請教為什麼像是.upper() or .lower()，他們是接續在string後面，而不是像是type()、int()把string放在括號內，不知道這樣設計有什麼緣故嗎~

**Comment by hyusterr** [comment]
在 python 裡，這種形式的東西叫做 method ，可以理解成接在特定物件後面的函數，做出特定的運算。可以先嘗試讀讀看這一篇
https://www.tutorialspoint.com/difference-between-method-and-function-in-python
至於一些比較看不懂的觀念，後面上完 function 之後會比較懂~

**Comment by tom192180** [comment]
好的!!謝謝h大~
