### ISSUE TITLE
[General] 字串轉為list的用法

### ISSUE THREAD

**Issue by DindinWang** [coding-coworking-club/python-2020-spring#90]
## 程式碼

```python
list=['aa','bb']
list_str=','.join(list)
print(list_str)
new_list=list_str.split(" ")
print(new_list)
```

## 問題描述

`new_list=list_str.split(" ")`，再空格裡無論輸入什麼內容，字串變回list還是以
`list_str=','.join(list)`，join的method內以`","`為主，就不太懂`split(" ")`裡面的意義是什麼

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將標題及內文格式修正。

**Comment by DindinWang** [comment]
已經重新提交再麻煩校閱，謝謝

**Comment by alexypdu** [comment]
`split` 跟 `join` 並沒有對應關係，你可以再 Google 一下 `split` 的用法
