### ISSUE TITLE
[Week 2] 母音種類個數

### ISSUE THREAD

**Issue by librairde** [coding-coworking-club/python-2020-spring#92]
## 程式碼
n=input()
letter = 'aeiouAEIOU'
lst = []
sum =0

for i in n:
    if i in letter:
        lst += i
        
    for j in lst:
        if j == i:
            sum += 1
print(sum)

```python

```

## 問題描述
請問要如何踢除判定重複出現的字母？能否舉個實際example,有時候單用解說還是想不出來,謝謝

**Comment by alexypdu** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將內文格式修正。
