### ISSUE TITLE
[Homework 1] 數字數

### ISSUE THREAD

**Issue by r05521230** [coding-coworking-club/python-2020-spring#93]
## 提交連結

https://judge.ccclub.io/status/93ed66f7cad753cf13b6f230e9cb799a

## 程式碼

```python
sentence = input()
word = sentence.split(" ")

sum = 0
for num in range(0,len(sentence)):
    if sentence[num].isalpha():
        sum += 1

print(len(word))
print(sum)
```

## 錯誤訊息

Wrong Answer
## 問題描述

用範例的結果是對的，但不知為何是Wrong Answer，請問問題出在哪，感謝。

**Comment by cyhsieh264** [comment]
可以參考 #32

**Comment by r05521230** [comment]
把sentence.split(" ")改成sentence.split()就可以了
但一般句子的頭尾應該不會有空白字元，還是覺得原本的寫法就有符合需求，不太明白為什麼一定寫成sentence.split()

**Comment by cyhsieh264** [comment]
題意是給定一段文章，也許會有分段或換行等問題，就是盡量考慮到所有可能的狀況囉😉

**Comment by r05521230** [comment]
原來如此，感謝！
