### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by w52wendy** [coding-coworking-club/python-2020-spring#95]
## 提交連結
https://www.udemy.com/course/ccclub-python-for-beginners/learn/quiz/4391652#bookmarks

## 程式碼
 a=list1 [:]
b=list2 [:]
c=int(input())
    a.count(c)
    b.count(c)
    if   (a. count(c)!=0) or (b. count(c)!=0):
    print("True")
    else:
    print("Flase")

```python

```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/62502198/77247658-1c95c080-6c6e-11ea-8379-e43bdc038db8.png)

## 問題描述
若list為未知該如何輸入？

**Comment by chun9425** [comment]
請參考 [GitHub Issue 教學](https://www.notion.so/GitHub-Issue-9ac0b74bd8314cc091184bdf0173b66e) 將標題及內文格式修正。
