### ISSUE TITLE
[Homework 1] 小明來造句

### ISSUE THREAD

**Issue by Jasper1012** [coding-coworking-club/python-2020-spring#96]
## 提交連結

https://judge.ccclub.io/status/850a54bc2e97bb8ae5a8a2a2a914a94f

## 程式碼

```python
subject=input().split( )
verb=input().split( )
object=input().split( )
for s in subject:
    for v in verb:
        for o in object:
            print(f'{s} {v} {o}')
```

## 錯誤訊息

<img width="741" alt="螢幕快照 2020-03-22 下午10 04 00" src="https://user-images.githubusercontent.com/61902209/77251483-8a9bb100-6c89-11ea-9774-b7d925ae1ee9.png">

## 問題描述

程式已經在jupyter可以跑出來了，
但最後跑出Compile Error，
是最後一句缺了什麼嗎？

**Comment by fangha1216** [comment]
object是保留字 命名的時候要避開不然很容易出錯
要看單字是不是保留字你打的時候會發現他不是黑色
在jupyter會是綠色的字
表示他預設是有功能的所以你隨意的改他 他就會出一些錯誤

**Comment by alexypdu** [comment]
批改系統的 Python 版本是不支援 f-strings 的。

**Comment by Jasper1012** [comment]
原來如此，修正後成功了！thx～
