### ISSUE TITLE
[Homework 1] 二十六進位

### ISSUE THREAD

**Issue by TZU-LING** [coding-coworking-club/python-2020-spring#98]
## 程式碼

```python
s = int(input())
inte = s // 26
rest = s % 26
lst = [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R,
       S, T, U, V, W, X, Y, Z]

print(lst[inte] + lst[rest])  
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/36917812/77254565-b7a58f00-6c9c-11ea-8bc7-67d4e8429741.png)

## 問題描述

不懂name 'A'  is not defined實際上是什麼錯誤，這邊跟定義應該無關? 另外，想請問這題有辦法運用zip嗎?  覺得跟zip有點類似，但不太知道如何運用於此~謝謝!

**Comment by jeffery12697** [comment]
`"A", A` 這兩個是不同的東西，前者資料型態是為string ， 後者是變數，如果沒有在前面給他賦值的話，是不能被使用的。
這題用 while 比較好解 ，如果不了解26進位，可以去查 2 進位 或 16進位 的解法再以此類推
